// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package offlineregistry binds the Windows.Wdk.System.OfflineRegistry API surface.
package offlineregistry
