// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package offlineregistry

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32security "github.com/deploymenttheory/go-bindings-win32/bindings/win32/security"
)

var (
	modOFFREG = win32.NewDLL("OFFREG.dll")
)

var (
	procORCloseHive        = modOFFREG.NewProc("ORCloseHive")
	procORCloseKey         = modOFFREG.NewProc("ORCloseKey")
	procORCreateHive       = modOFFREG.NewProc("ORCreateHive")
	procORCreateKey        = modOFFREG.NewProc("ORCreateKey")
	procORDeleteKey        = modOFFREG.NewProc("ORDeleteKey")
	procORDeleteValue      = modOFFREG.NewProc("ORDeleteValue")
	procOREnumKey          = modOFFREG.NewProc("OREnumKey")
	procOREnumValue        = modOFFREG.NewProc("OREnumValue")
	procORGetKeySecurity   = modOFFREG.NewProc("ORGetKeySecurity")
	procORGetValue         = modOFFREG.NewProc("ORGetValue")
	procORGetVersion       = modOFFREG.NewProc("ORGetVersion")
	procORGetVirtualFlags  = modOFFREG.NewProc("ORGetVirtualFlags")
	procORMergeHives       = modOFFREG.NewProc("ORMergeHives")
	procOROpenHive         = modOFFREG.NewProc("OROpenHive")
	procOROpenHiveByHandle = modOFFREG.NewProc("OROpenHiveByHandle")
	procOROpenKey          = modOFFREG.NewProc("OROpenKey")
	procORQueryInfoKey     = modOFFREG.NewProc("ORQueryInfoKey")
	procORRenameKey        = modOFFREG.NewProc("ORRenameKey")
	procORSaveHive         = modOFFREG.NewProc("ORSaveHive")
	procORSetKeySecurity   = modOFFREG.NewProc("ORSetKeySecurity")
	procORSetValue         = modOFFREG.NewProc("ORSetValue")
	procORSetVirtualFlags  = modOFFREG.NewProc("ORSetVirtualFlags")
	procORShutdown         = modOFFREG.NewProc("ORShutdown")
	procORStart            = modOFFREG.NewProc("ORStart")
)

// ORCloseHive calls OFFREG!ORCloseHive.
func ORCloseHive(Handle ORHKEY) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORCloseHive.Addr(), uintptr(Handle))
	return win32foundation.WIN32_ERROR(r1)
}

// ORCloseKey calls OFFREG!ORCloseKey.
func ORCloseKey(KeyHandle ORHKEY) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORCloseKey.Addr(), uintptr(KeyHandle))
	return win32foundation.WIN32_ERROR(r1)
}

// ORCreateHive calls OFFREG!ORCreateHive.
func ORCreateHive(HORKey *ORHKEY) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORCreateHive.Addr(), uintptr(unsafe.Pointer(HORKey)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORCreateKey calls OFFREG!ORCreateKey.
func ORCreateKey(KeyHandle ORHKEY, lpSubKey string, lpClass string, dwOptions uint32, pSecurityDescriptor win32security.PSECURITY_DESCRIPTOR, phkResult *ORHKEY, pdwDisposition *uint32) win32foundation.WIN32_ERROR {
	_lpSubKey := win32.UTF16Ptr(lpSubKey)
	_lpClass := win32.UTF16Ptr(lpClass)
	r1, _, _ := syscall.SyscallN(procORCreateKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(_lpSubKey)), uintptr(unsafe.Pointer(_lpClass)), uintptr(dwOptions), uintptr(pSecurityDescriptor), uintptr(unsafe.Pointer(phkResult)), uintptr(unsafe.Pointer(pdwDisposition)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORDeleteKey calls OFFREG!ORDeleteKey.
func ORDeleteKey(Handle ORHKEY, lpSubKey string) win32foundation.WIN32_ERROR {
	_lpSubKey := win32.UTF16Ptr(lpSubKey)
	r1, _, _ := syscall.SyscallN(procORDeleteKey.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(_lpSubKey)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORDeleteValue calls OFFREG!ORDeleteValue.
func ORDeleteValue(Handle ORHKEY, lpValueName string) win32foundation.WIN32_ERROR {
	_lpValueName := win32.UTF16Ptr(lpValueName)
	r1, _, _ := syscall.SyscallN(procORDeleteValue.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(_lpValueName)))
	return win32foundation.WIN32_ERROR(r1)
}

// OREnumKey calls OFFREG!OREnumKey.
func OREnumKey(Handle ORHKEY, dwIndex uint32, lpName win32foundation.PWSTR, lpcName *uint32, lpClass win32foundation.PWSTR, lpcClass *uint32, lpftLastWriteTime *win32foundation.FILETIME) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procOREnumKey.Addr(), uintptr(Handle), uintptr(dwIndex), uintptr(unsafe.Pointer(lpName)), uintptr(unsafe.Pointer(lpcName)), uintptr(unsafe.Pointer(lpClass)), uintptr(unsafe.Pointer(lpcClass)), uintptr(unsafe.Pointer(lpftLastWriteTime)))
	return win32foundation.WIN32_ERROR(r1)
}

// OREnumValue calls OFFREG!OREnumValue.
func OREnumValue(Handle ORHKEY, dwIndex uint32, lpValueName win32foundation.PWSTR, lpcValueName *uint32, lpType *uint32, lpData *byte, lpcbData *uint32) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procOREnumValue.Addr(), uintptr(Handle), uintptr(dwIndex), uintptr(unsafe.Pointer(lpValueName)), uintptr(unsafe.Pointer(lpcValueName)), uintptr(unsafe.Pointer(lpType)), uintptr(unsafe.Pointer(lpData)), uintptr(unsafe.Pointer(lpcbData)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORGetKeySecurity calls OFFREG!ORGetKeySecurity.
func ORGetKeySecurity(Handle ORHKEY, SecurityInformation uint32, pSecurityDescriptor win32security.PSECURITY_DESCRIPTOR, lpcbSecurityDescriptor *uint32) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORGetKeySecurity.Addr(), uintptr(Handle), uintptr(SecurityInformation), uintptr(pSecurityDescriptor), uintptr(unsafe.Pointer(lpcbSecurityDescriptor)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORGetValue calls OFFREG!ORGetValue.
func ORGetValue(Handle ORHKEY, lpSubKey string, lpValue string, pdwType *uint32, pvData unsafe.Pointer, pcbData *uint32) win32foundation.WIN32_ERROR {
	_lpSubKey := win32.UTF16Ptr(lpSubKey)
	_lpValue := win32.UTF16Ptr(lpValue)
	r1, _, _ := syscall.SyscallN(procORGetValue.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(_lpSubKey)), uintptr(unsafe.Pointer(_lpValue)), uintptr(unsafe.Pointer(pdwType)), uintptr(unsafe.Pointer(pvData)), uintptr(unsafe.Pointer(pcbData)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORGetVersion calls OFFREG!ORGetVersion.
func ORGetVersion(pdwMajorVersion *uint32, pdwMinorVersion *uint32) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORGetVersion.Addr(), uintptr(unsafe.Pointer(pdwMajorVersion)), uintptr(unsafe.Pointer(pdwMinorVersion)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORGetVirtualFlags calls OFFREG!ORGetVirtualFlags.
func ORGetVirtualFlags(Handle ORHKEY, pdwFlags *uint32) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORGetVirtualFlags.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(pdwFlags)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORMergeHives calls OFFREG!ORMergeHives.
func ORMergeHives(HiveHandles []ORHKEY, phkResult *ORHKEY) win32foundation.WIN32_ERROR {
	var _HiveHandles *ORHKEY
	if len(HiveHandles) > 0 {
		_HiveHandles = &HiveHandles[0]
	}
	r1, _, _ := syscall.SyscallN(procORMergeHives.Addr(), uintptr(unsafe.Pointer(_HiveHandles)), uintptr(len(HiveHandles)), uintptr(unsafe.Pointer(phkResult)))
	return win32foundation.WIN32_ERROR(r1)
}

// OROpenHive calls OFFREG!OROpenHive.
func OROpenHive(FilePath string, HORKey *ORHKEY) win32foundation.WIN32_ERROR {
	_FilePath := win32.UTF16Ptr(FilePath)
	r1, _, _ := syscall.SyscallN(procOROpenHive.Addr(), uintptr(unsafe.Pointer(_FilePath)), uintptr(unsafe.Pointer(HORKey)))
	return win32foundation.WIN32_ERROR(r1)
}

// OROpenHiveByHandle calls OFFREG!OROpenHiveByHandle.
func OROpenHiveByHandle(FileHandle win32foundation.HANDLE, HORKey *ORHKEY) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procOROpenHiveByHandle.Addr(), uintptr(FileHandle), uintptr(unsafe.Pointer(HORKey)))
	return win32foundation.WIN32_ERROR(r1)
}

// OROpenKey calls OFFREG!OROpenKey.
func OROpenKey(Handle ORHKEY, lpSubKey string, phkResult *ORHKEY) win32foundation.WIN32_ERROR {
	_lpSubKey := win32.UTF16Ptr(lpSubKey)
	r1, _, _ := syscall.SyscallN(procOROpenKey.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(_lpSubKey)), uintptr(unsafe.Pointer(phkResult)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORQueryInfoKey calls OFFREG!ORQueryInfoKey.
func ORQueryInfoKey(Handle ORHKEY, lpClass win32foundation.PWSTR, lpcClass *uint32, lpcSubKeys *uint32, lpcMaxSubKeyLen *uint32, lpcMaxClassLen *uint32, lpcValues *uint32, lpcMaxValueNameLen *uint32, lpcMaxValueLen *uint32, lpcbSecurityDescriptor *uint32, lpftLastWriteTime *win32foundation.FILETIME) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORQueryInfoKey.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(lpClass)), uintptr(unsafe.Pointer(lpcClass)), uintptr(unsafe.Pointer(lpcSubKeys)), uintptr(unsafe.Pointer(lpcMaxSubKeyLen)), uintptr(unsafe.Pointer(lpcMaxClassLen)), uintptr(unsafe.Pointer(lpcValues)), uintptr(unsafe.Pointer(lpcMaxValueNameLen)), uintptr(unsafe.Pointer(lpcMaxValueLen)), uintptr(unsafe.Pointer(lpcbSecurityDescriptor)), uintptr(unsafe.Pointer(lpftLastWriteTime)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORRenameKey calls OFFREG!ORRenameKey.
func ORRenameKey(Handle ORHKEY, lpNewName string) win32foundation.WIN32_ERROR {
	_lpNewName := win32.UTF16Ptr(lpNewName)
	r1, _, _ := syscall.SyscallN(procORRenameKey.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(_lpNewName)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORSaveHive calls OFFREG!ORSaveHive.
func ORSaveHive(HORKey ORHKEY, HivePath string, OsMajorVersion uint32, OsMinorVersion uint32) win32foundation.WIN32_ERROR {
	_HivePath := win32.UTF16Ptr(HivePath)
	r1, _, _ := syscall.SyscallN(procORSaveHive.Addr(), uintptr(HORKey), uintptr(unsafe.Pointer(_HivePath)), uintptr(OsMajorVersion), uintptr(OsMinorVersion))
	return win32foundation.WIN32_ERROR(r1)
}

// ORSetKeySecurity calls OFFREG!ORSetKeySecurity.
func ORSetKeySecurity(Handle ORHKEY, SecurityInformation uint32, pSecurityDescriptor win32security.PSECURITY_DESCRIPTOR) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORSetKeySecurity.Addr(), uintptr(Handle), uintptr(SecurityInformation), uintptr(pSecurityDescriptor))
	return win32foundation.WIN32_ERROR(r1)
}

// ORSetValue calls OFFREG!ORSetValue.
func ORSetValue(Handle ORHKEY, lpValueName string, dwType uint32, lpData []byte) win32foundation.WIN32_ERROR {
	_lpValueName := win32.UTF16Ptr(lpValueName)
	var _lpData *byte
	if len(lpData) > 0 {
		_lpData = &lpData[0]
	}
	r1, _, _ := syscall.SyscallN(procORSetValue.Addr(), uintptr(Handle), uintptr(unsafe.Pointer(_lpValueName)), uintptr(dwType), uintptr(unsafe.Pointer(_lpData)), uintptr(len(lpData)))
	return win32foundation.WIN32_ERROR(r1)
}

// ORSetVirtualFlags calls OFFREG!ORSetVirtualFlags.
func ORSetVirtualFlags(Handle ORHKEY, dwFlags uint32) win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORSetVirtualFlags.Addr(), uintptr(Handle), uintptr(dwFlags))
	return win32foundation.WIN32_ERROR(r1)
}

// ORShutdown calls OFFREG!ORShutdown.
func ORShutdown() win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORShutdown.Addr())
	return win32foundation.WIN32_ERROR(r1)
}

// ORStart calls OFFREG!ORStart.
func ORStart() win32foundation.WIN32_ERROR {
	r1, _, _ := syscall.SyscallN(procORStart.Addr())
	return win32foundation.WIN32_ERROR(r1)
}
