// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package foundation

// DRIVER_ADD_DEVICE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DRIVER_OBJECT, *DEVICE_OBJECT) win32foundation.NTSTATUS.
type DRIVER_ADD_DEVICE uintptr

// DRIVER_CANCEL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, *IRP).
type DRIVER_CANCEL uintptr

// DRIVER_CONTROL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, *IRP, unsafe.Pointer, unsafe.Pointer) int32.
type DRIVER_CONTROL uintptr

// DRIVER_DISPATCH is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, *IRP) win32foundation.NTSTATUS.
type DRIVER_DISPATCH uintptr

// DRIVER_DISPATCH_PAGED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, *IRP) win32foundation.NTSTATUS.
type DRIVER_DISPATCH_PAGED uintptr

// DRIVER_FS_NOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, win32foundation.BOOLEAN).
type DRIVER_FS_NOTIFICATION uintptr

// DRIVER_INITIALIZE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DRIVER_OBJECT, *win32foundation.UNICODE_STRING) win32foundation.NTSTATUS.
type DRIVER_INITIALIZE uintptr

// DRIVER_NOTIFICATION_CALLBACK_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer) win32foundation.NTSTATUS.
type DRIVER_NOTIFICATION_CALLBACK_ROUTINE uintptr

// DRIVER_REINITIALIZE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DRIVER_OBJECT, unsafe.Pointer, uint32).
type DRIVER_REINITIALIZE uintptr

// DRIVER_STARTIO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, *IRP).
type DRIVER_STARTIO uintptr

// DRIVER_UNLOAD is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DRIVER_OBJECT).
type DRIVER_UNLOAD uintptr

// FAST_IO_ACQUIRE_FILE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT).
type FAST_IO_ACQUIRE_FILE uintptr

// FAST_IO_ACQUIRE_FOR_CCFLUSH is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *DEVICE_OBJECT) win32foundation.NTSTATUS.
type FAST_IO_ACQUIRE_FOR_CCFLUSH uintptr

// FAST_IO_ACQUIRE_FOR_MOD_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, **ERESOURCE, *DEVICE_OBJECT) win32foundation.NTSTATUS.
type FAST_IO_ACQUIRE_FOR_MOD_WRITE uintptr

// FAST_IO_CHECK_IF_POSSIBLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, win32foundation.BOOLEAN, uint32, win32foundation.BOOLEAN, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_CHECK_IF_POSSIBLE uintptr

// FAST_IO_DETACH_DEVICE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*DEVICE_OBJECT, *DEVICE_OBJECT).
type FAST_IO_DETACH_DEVICE uintptr

// FAST_IO_DEVICE_CONTROL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, win32foundation.BOOLEAN, unsafe.Pointer, uint32, unsafe.Pointer, uint32, uint32, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_DEVICE_CONTROL uintptr

// FAST_IO_LOCK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, *int64, PEPROCESS, uint32, win32foundation.BOOLEAN, win32foundation.BOOLEAN, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_LOCK uintptr

// FAST_IO_MDL_READ is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, uint32, **MDL, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_MDL_READ uintptr

// FAST_IO_MDL_READ_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *MDL, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_MDL_READ_COMPLETE uintptr

// FAST_IO_MDL_READ_COMPLETE_COMPRESSED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *MDL, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_MDL_READ_COMPLETE_COMPRESSED uintptr

// FAST_IO_MDL_WRITE_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, *MDL, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_MDL_WRITE_COMPLETE uintptr

// FAST_IO_MDL_WRITE_COMPLETE_COMPRESSED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, *MDL, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_MDL_WRITE_COMPLETE_COMPRESSED uintptr

// FAST_IO_PREPARE_MDL_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, uint32, **MDL, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_PREPARE_MDL_WRITE uintptr

// FAST_IO_QUERY_BASIC_INFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, win32foundation.BOOLEAN, unsafe.Pointer, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_QUERY_BASIC_INFO uintptr

// FAST_IO_QUERY_NETWORK_OPEN_INFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, win32foundation.BOOLEAN, unsafe.Pointer, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_QUERY_NETWORK_OPEN_INFO uintptr

// FAST_IO_QUERY_OPEN is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*IRP, unsafe.Pointer, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_QUERY_OPEN uintptr

// FAST_IO_QUERY_STANDARD_INFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, win32foundation.BOOLEAN, unsafe.Pointer, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_QUERY_STANDARD_INFO uintptr

// FAST_IO_READ is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, win32foundation.BOOLEAN, uint32, unsafe.Pointer, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_READ uintptr

// FAST_IO_READ_COMPRESSED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, uint32, unsafe.Pointer, **MDL, *win32systemio.IO_STATUS_BLOCK, unsafe.Pointer, uint32, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_READ_COMPRESSED uintptr

// FAST_IO_RELEASE_FILE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT).
type FAST_IO_RELEASE_FILE uintptr

// FAST_IO_RELEASE_FOR_CCFLUSH is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *DEVICE_OBJECT) win32foundation.NTSTATUS.
type FAST_IO_RELEASE_FOR_CCFLUSH uintptr

// FAST_IO_RELEASE_FOR_MOD_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *ERESOURCE, *DEVICE_OBJECT) win32foundation.NTSTATUS.
type FAST_IO_RELEASE_FOR_MOD_WRITE uintptr

// FAST_IO_UNLOCK_ALL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, PEPROCESS, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_UNLOCK_ALL uintptr

// FAST_IO_UNLOCK_ALL_BY_KEY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, unsafe.Pointer, uint32, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_UNLOCK_ALL_BY_KEY uintptr

// FAST_IO_UNLOCK_SINGLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, *int64, PEPROCESS, uint32, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_UNLOCK_SINGLE uintptr

// FAST_IO_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, win32foundation.BOOLEAN, uint32, unsafe.Pointer, *win32systemio.IO_STATUS_BLOCK, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_WRITE uintptr

// FAST_IO_WRITE_COMPRESSED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FILE_OBJECT, *int64, uint32, uint32, unsafe.Pointer, **MDL, *win32systemio.IO_STATUS_BLOCK, unsafe.Pointer, uint32, *DEVICE_OBJECT) win32foundation.BOOLEAN.
type FAST_IO_WRITE_COMPRESSED uintptr

// PFREE_FUNCTION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PFREE_FUNCTION uintptr

// PIO_COMPLETION_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PIO_COMPLETION_ROUTINE uintptr

// PKDEFERRED_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PKDEFERRED_ROUTINE uintptr

// PWORKER_THREAD_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PWORKER_THREAD_ROUTINE uintptr
