// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package foundation

import (
	"fmt"
)

type IO_PRIORITY_HINT int32

const (
	IoPriorityVeryLow  IO_PRIORITY_HINT = 0
	IoPriorityLow      IO_PRIORITY_HINT = 1
	IoPriorityNormal   IO_PRIORITY_HINT = 2
	IoPriorityHigh     IO_PRIORITY_HINT = 3
	IoPriorityCritical IO_PRIORITY_HINT = 4
	MaxIoPriorityTypes IO_PRIORITY_HINT = 5
)

// String returns the IO_PRIORITY_HINT constant's name, or its numeric form when
// the value is not a known constant.
func (e IO_PRIORITY_HINT) String() string {
	switch e {
	case IoPriorityVeryLow:
		return "IoPriorityVeryLow"
	case IoPriorityLow:
		return "IoPriorityLow"
	case IoPriorityNormal:
		return "IoPriorityNormal"
	case IoPriorityHigh:
		return "IoPriorityHigh"
	case IoPriorityCritical:
		return "IoPriorityCritical"
	case MaxIoPriorityTypes:
		return "MaxIoPriorityTypes"
	default:
		return fmt.Sprintf("IO_PRIORITY_HINT(%d)", int32(e))
	}
}

type KSPIN_LOCK_QUEUE_NUMBER int32

const (
	LockQueueUnusedSpare0     KSPIN_LOCK_QUEUE_NUMBER = 0
	LockQueueUnusedSpare1     KSPIN_LOCK_QUEUE_NUMBER = 1
	LockQueueUnusedSpare2     KSPIN_LOCK_QUEUE_NUMBER = 2
	LockQueueUnusedSpare3     KSPIN_LOCK_QUEUE_NUMBER = 3
	LockQueueVacbLock         KSPIN_LOCK_QUEUE_NUMBER = 4
	LockQueueMasterLock       KSPIN_LOCK_QUEUE_NUMBER = 5
	LockQueueNonPagedPoolLock KSPIN_LOCK_QUEUE_NUMBER = 6
	LockQueueIoCancelLock     KSPIN_LOCK_QUEUE_NUMBER = 7
	LockQueueUnusedSpare8     KSPIN_LOCK_QUEUE_NUMBER = 8
	LockQueueIoVpbLock        KSPIN_LOCK_QUEUE_NUMBER = 9
	LockQueueIoDatabaseLock   KSPIN_LOCK_QUEUE_NUMBER = 10
	LockQueueIoCompletionLock KSPIN_LOCK_QUEUE_NUMBER = 11
	LockQueueNtfsStructLock   KSPIN_LOCK_QUEUE_NUMBER = 12
	LockQueueAfdWorkQueueLock KSPIN_LOCK_QUEUE_NUMBER = 13
	LockQueueBcbLock          KSPIN_LOCK_QUEUE_NUMBER = 14
	LockQueueUnusedSpare15    KSPIN_LOCK_QUEUE_NUMBER = 15
	LockQueueUnusedSpare16    KSPIN_LOCK_QUEUE_NUMBER = 16
	LockQueueMaximumLock      KSPIN_LOCK_QUEUE_NUMBER = 17
)

// String returns the KSPIN_LOCK_QUEUE_NUMBER constant's name, or its numeric form when
// the value is not a known constant.
func (e KSPIN_LOCK_QUEUE_NUMBER) String() string {
	switch e {
	case LockQueueUnusedSpare0:
		return "LockQueueUnusedSpare0"
	case LockQueueUnusedSpare1:
		return "LockQueueUnusedSpare1"
	case LockQueueUnusedSpare2:
		return "LockQueueUnusedSpare2"
	case LockQueueUnusedSpare3:
		return "LockQueueUnusedSpare3"
	case LockQueueVacbLock:
		return "LockQueueVacbLock"
	case LockQueueMasterLock:
		return "LockQueueMasterLock"
	case LockQueueNonPagedPoolLock:
		return "LockQueueNonPagedPoolLock"
	case LockQueueIoCancelLock:
		return "LockQueueIoCancelLock"
	case LockQueueUnusedSpare8:
		return "LockQueueUnusedSpare8"
	case LockQueueIoVpbLock:
		return "LockQueueIoVpbLock"
	case LockQueueIoDatabaseLock:
		return "LockQueueIoDatabaseLock"
	case LockQueueIoCompletionLock:
		return "LockQueueIoCompletionLock"
	case LockQueueNtfsStructLock:
		return "LockQueueNtfsStructLock"
	case LockQueueAfdWorkQueueLock:
		return "LockQueueAfdWorkQueueLock"
	case LockQueueBcbLock:
		return "LockQueueBcbLock"
	case LockQueueUnusedSpare15:
		return "LockQueueUnusedSpare15"
	case LockQueueUnusedSpare16:
		return "LockQueueUnusedSpare16"
	case LockQueueMaximumLock:
		return "LockQueueMaximumLock"
	default:
		return fmt.Sprintf("KSPIN_LOCK_QUEUE_NUMBER(%d)", int32(e))
	}
}

type OBJECT_INFORMATION_CLASS int32

const (
	ObjectBasicInformation OBJECT_INFORMATION_CLASS = 0
	ObjectTypeInformation  OBJECT_INFORMATION_CLASS = 2
)

// String returns the OBJECT_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e OBJECT_INFORMATION_CLASS) String() string {
	switch e {
	case ObjectBasicInformation:
		return "ObjectBasicInformation"
	case ObjectTypeInformation:
		return "ObjectTypeInformation"
	default:
		return fmt.Sprintf("OBJECT_INFORMATION_CLASS(%d)", int32(e))
	}
}

type POOL_TYPE int32

const (
	NonPagedPool                         POOL_TYPE = 0
	NonPagedPoolExecute                  POOL_TYPE = 0
	PagedPool                            POOL_TYPE = 1
	NonPagedPoolMustSucceed              POOL_TYPE = 2
	DontUseThisType                      POOL_TYPE = 3
	NonPagedPoolCacheAligned             POOL_TYPE = 4
	PagedPoolCacheAligned                POOL_TYPE = 5
	NonPagedPoolCacheAlignedMustS        POOL_TYPE = 6
	MaxPoolType                          POOL_TYPE = 7
	NonPagedPoolBase                     POOL_TYPE = 0
	NonPagedPoolBaseMustSucceed          POOL_TYPE = 2
	NonPagedPoolBaseCacheAligned         POOL_TYPE = 4
	NonPagedPoolBaseCacheAlignedMustS    POOL_TYPE = 6
	NonPagedPoolSession                  POOL_TYPE = 32
	PagedPoolSession                     POOL_TYPE = 33
	NonPagedPoolMustSucceedSession       POOL_TYPE = 34
	DontUseThisTypeSession               POOL_TYPE = 35
	NonPagedPoolCacheAlignedSession      POOL_TYPE = 36
	PagedPoolCacheAlignedSession         POOL_TYPE = 37
	NonPagedPoolCacheAlignedMustSSession POOL_TYPE = 38
	NonPagedPoolNx                       POOL_TYPE = 512
	NonPagedPoolNxCacheAligned           POOL_TYPE = 516
	NonPagedPoolSessionNx                POOL_TYPE = 544
)

// String returns the POOL_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e POOL_TYPE) String() string {
	switch e {
	case NonPagedPool:
		return "NonPagedPool"
	case PagedPool:
		return "PagedPool"
	case NonPagedPoolMustSucceed:
		return "NonPagedPoolMustSucceed"
	case DontUseThisType:
		return "DontUseThisType"
	case NonPagedPoolCacheAligned:
		return "NonPagedPoolCacheAligned"
	case PagedPoolCacheAligned:
		return "PagedPoolCacheAligned"
	case NonPagedPoolCacheAlignedMustS:
		return "NonPagedPoolCacheAlignedMustS"
	case MaxPoolType:
		return "MaxPoolType"
	case NonPagedPoolSession:
		return "NonPagedPoolSession"
	case PagedPoolSession:
		return "PagedPoolSession"
	case NonPagedPoolMustSucceedSession:
		return "NonPagedPoolMustSucceedSession"
	case DontUseThisTypeSession:
		return "DontUseThisTypeSession"
	case NonPagedPoolCacheAlignedSession:
		return "NonPagedPoolCacheAlignedSession"
	case PagedPoolCacheAlignedSession:
		return "PagedPoolCacheAlignedSession"
	case NonPagedPoolCacheAlignedMustSSession:
		return "NonPagedPoolCacheAlignedMustSSession"
	case NonPagedPoolNx:
		return "NonPagedPoolNx"
	case NonPagedPoolNxCacheAligned:
		return "NonPagedPoolNxCacheAligned"
	case NonPagedPoolSessionNx:
		return "NonPagedPoolSessionNx"
	default:
		return fmt.Sprintf("POOL_TYPE(%d)", int32(e))
	}
}
