// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package foundation

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

var (
	modntdll = win32.NewDLL("ntdll.dll")
)

var (
	procNtClose       = modntdll.NewProc("NtClose")
	procNtQueryObject = modntdll.NewProc("NtQueryObject")
)

// NtClose calls ntdll!NtClose.
func NtClose(Handle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtClose.Addr(), uintptr(Handle))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryObject calls ntdll!NtQueryObject.
func NtQueryObject(Handle win32foundation.HANDLE, ObjectInformationClass OBJECT_INFORMATION_CLASS, ObjectInformation []byte, ReturnLength *uint32) win32foundation.NTSTATUS {
	var _ObjectInformation *byte
	if len(ObjectInformation) > 0 {
		_ObjectInformation = &ObjectInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtQueryObject.Addr(), uintptr(Handle), uintptr(ObjectInformationClass), uintptr(unsafe.Pointer(_ObjectInformation)), uintptr(len(ObjectInformation)), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}
