// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package foundation

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32security "github.com/deploymenttheory/go-bindings-win32/bindings/win32/security"
	win32systemio "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/io"
	win32systemkernel "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/kernel"
)

// ACCESS_STATE_Privileges_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type ACCESS_STATE_Privileges_e__Union struct {
	Data [11]uint32
}

type ACCESS_STATE struct {
	OperationID             win32foundation.LUID
	SecurityEvaluated       win32foundation.BOOLEAN
	GenerateAudit           win32foundation.BOOLEAN
	GenerateOnClose         win32foundation.BOOLEAN
	PrivilegesAllocated     win32foundation.BOOLEAN
	Flags                   uint32
	RemainingDesiredAccess  uint32
	PreviouslyGrantedAccess uint32
	OriginalDesiredAccess   uint32
	SubjectSecurityContext  SECURITY_SUBJECT_CONTEXT
	SecurityDescriptor      win32security.PSECURITY_DESCRIPTOR
	AuxData                 unsafe.Pointer
	Privileges              ACCESS_STATE_Privileges_e__Union
	AuditPrivileges         win32foundation.BOOLEAN
	ObjectName              win32foundation.UNICODE_STRING
	ObjectTypeName          win32foundation.UNICODE_STRING
}

// DEVICE_OBJECT_Queue_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type DEVICE_OBJECT_Queue_e__Union struct {
	Data [9]uint64
}

type DEVICE_OBJECT struct {
	Type                  int16
	Size                  uint16
	ReferenceCount        int32
	DriverObject          *DRIVER_OBJECT
	NextDevice            *DEVICE_OBJECT
	AttachedDevice        *DEVICE_OBJECT
	CurrentIrp            *IRP
	Timer                 PIO_TIMER
	Flags                 uint32
	Characteristics       uint32
	Vpb                   *VPB
	DeviceExtension       unsafe.Pointer
	DeviceType            uint32
	StackSize             int8
	Queue                 DEVICE_OBJECT_Queue_e__Union
	AlignmentRequirement  uint32
	DeviceQueue           KDEVICE_QUEUE
	Dpc                   KDPC
	ActiveThreadCount     uint32
	SecurityDescriptor    win32security.PSECURITY_DESCRIPTOR
	DeviceLock            KEVENT
	SectorSize            uint16
	Spare1                uint16
	DeviceObjectExtension *DEVOBJ_EXTENSION
	Reserved              unsafe.Pointer
}

type DEVOBJ_EXTENSION struct {
	Type             int16
	Size             uint16
	DeviceObject     *DEVICE_OBJECT
	PowerFlags       uint32
	Dope             *DEVICE_OBJECT_POWER_EXTENSION
	ExtensionFlags   uint32
	DeviceNode       unsafe.Pointer
	AttachedTo       *DEVICE_OBJECT
	StartIoCount     int32
	StartIoKey       int32
	StartIoFlags     uint32
	Vpb              *VPB
	DependencyNode   unsafe.Pointer
	InterruptContext unsafe.Pointer
	InterruptCount   int32
	VerifierContext  unsafe.Pointer
}

// DISPATCHER_HEADER_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type DISPATCHER_HEADER_Anonymous_e__Union struct {
	Data [1]uint32
}

type DISPATCHER_HEADER struct {
	Anonymous    DISPATCHER_HEADER_Anonymous_e__Union
	SignalState  int32
	WaitListHead win32systemkernel.LIST_ENTRY
}

type DRIVER_EXTENSION struct {
	DriverObject   *DRIVER_OBJECT
	AddDevice      DRIVER_ADD_DEVICE
	Count          uint32
	ServiceKeyName win32foundation.UNICODE_STRING
}

type DRIVER_OBJECT struct {
	Type             int16
	Size             int16
	DeviceObject     *DEVICE_OBJECT
	Flags            uint32
	DriverStart      unsafe.Pointer
	DriverSize       uint32
	DriverSection    unsafe.Pointer
	DriverExtension  *DRIVER_EXTENSION
	DriverName       win32foundation.UNICODE_STRING
	HardwareDatabase *win32foundation.UNICODE_STRING
	FastIoDispatch   *FAST_IO_DISPATCH
	DriverInit       DRIVER_INITIALIZE
	DriverStartIo    DRIVER_STARTIO
	DriverUnload     DRIVER_UNLOAD
	MajorFunction    [28]DRIVER_DISPATCH
}

// ERESOURCE_Anonymous1_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type ERESOURCE_Anonymous1_e__Union struct {
	Data [1]uint16
}

// ERESOURCE_Anonymous2_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type ERESOURCE_Anonymous2_e__Union struct {
	Data [1]uint64
}

type ERESOURCE struct {
	SystemResourcesList      win32systemkernel.LIST_ENTRY
	OwnerTable               *OWNER_ENTRY
	ActiveCount              int16
	Anonymous1               ERESOURCE_Anonymous1_e__Union
	SharedWaiters            unsafe.Pointer
	ExclusiveWaiters         unsafe.Pointer
	OwnerEntry               OWNER_ENTRY
	ActiveEntries            uint32
	ContentionCount          uint32
	NumberOfSharedWaiters    uint32
	NumberOfExclusiveWaiters uint32
	Anonymous2               ERESOURCE_Anonymous2_e__Union
	SpinLock                 uintptr
}

type FAST_IO_DISPATCH struct {
	SizeOfFastIoDispatch          uint32
	FastIoCheckIfPossible         FAST_IO_CHECK_IF_POSSIBLE
	FastIoRead                    FAST_IO_READ
	FastIoWrite                   FAST_IO_WRITE
	FastIoQueryBasicInfo          FAST_IO_QUERY_BASIC_INFO
	FastIoQueryStandardInfo       FAST_IO_QUERY_STANDARD_INFO
	FastIoLock                    FAST_IO_LOCK
	FastIoUnlockSingle            FAST_IO_UNLOCK_SINGLE
	FastIoUnlockAll               FAST_IO_UNLOCK_ALL
	FastIoUnlockAllByKey          FAST_IO_UNLOCK_ALL_BY_KEY
	FastIoDeviceControl           FAST_IO_DEVICE_CONTROL
	AcquireFileForNtCreateSection FAST_IO_ACQUIRE_FILE
	ReleaseFileForNtCreateSection FAST_IO_RELEASE_FILE
	FastIoDetachDevice            FAST_IO_DETACH_DEVICE
	FastIoQueryNetworkOpenInfo    FAST_IO_QUERY_NETWORK_OPEN_INFO
	AcquireForModWrite            FAST_IO_ACQUIRE_FOR_MOD_WRITE
	MdlRead                       FAST_IO_MDL_READ
	MdlReadComplete               FAST_IO_MDL_READ_COMPLETE
	PrepareMdlWrite               FAST_IO_PREPARE_MDL_WRITE
	MdlWriteComplete              FAST_IO_MDL_WRITE_COMPLETE
	FastIoReadCompressed          FAST_IO_READ_COMPRESSED
	FastIoWriteCompressed         FAST_IO_WRITE_COMPRESSED
	MdlReadCompleteCompressed     FAST_IO_MDL_READ_COMPLETE_COMPRESSED
	MdlWriteCompleteCompressed    FAST_IO_MDL_WRITE_COMPLETE_COMPRESSED
	FastIoQueryOpen               FAST_IO_QUERY_OPEN
	ReleaseForModWrite            FAST_IO_RELEASE_FOR_MOD_WRITE
	AcquireForCcFlush             FAST_IO_ACQUIRE_FOR_CCFLUSH
	ReleaseForCcFlush             FAST_IO_RELEASE_FOR_CCFLUSH
}

type FAST_MUTEX struct {
	Count      int32
	Owner      unsafe.Pointer
	Contention uint32
	Event      KEVENT
	OldIrql    uint32
}

type FILE_OBJECT struct {
	Type                 int16
	Size                 int16
	DeviceObject         *DEVICE_OBJECT
	Vpb                  *VPB
	FsContext            unsafe.Pointer
	FsContext2           unsafe.Pointer
	SectionObjectPointer *SECTION_OBJECT_POINTERS
	PrivateCacheMap      unsafe.Pointer
	FinalStatus          win32foundation.NTSTATUS
	RelatedFileObject    *FILE_OBJECT
	LockOperation        win32foundation.BOOLEAN
	DeletePending        win32foundation.BOOLEAN
	ReadAccess           win32foundation.BOOLEAN
	WriteAccess          win32foundation.BOOLEAN
	DeleteAccess         win32foundation.BOOLEAN
	SharedRead           win32foundation.BOOLEAN
	SharedWrite          win32foundation.BOOLEAN
	SharedDelete         win32foundation.BOOLEAN
	Flags                uint32
	FileName             win32foundation.UNICODE_STRING
	CurrentByteOffset    int64
	Waiters              uint32
	Busy                 uint32
	LastLock             unsafe.Pointer
	Lock                 KEVENT
	Event                KEVENT
	CompletionContext    *IO_COMPLETION_CONTEXT
	IrpListLock          uintptr
	IrpList              win32systemkernel.LIST_ENTRY
	FileObjectExtension  unsafe.Pointer
}

type IO_COMPLETION_CONTEXT struct {
	Port       unsafe.Pointer
	Key        unsafe.Pointer
	UsageCount uintptr
}

type IO_SECURITY_CONTEXT struct {
	SecurityQos       *win32security.SECURITY_QUALITY_OF_SERVICE
	AccessState       *ACCESS_STATE
	DesiredAccess     uint32
	FullCreateOptions uint32
}

// IO_STACK_LOCATION_Parameters_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IO_STACK_LOCATION_Parameters_e__Union struct {
	Data [4]uint64
}

type IO_STACK_LOCATION struct {
	MajorFunction     byte
	MinorFunction     byte
	Flags             byte
	Control           byte
	Parameters        IO_STACK_LOCATION_Parameters_e__Union
	DeviceObject      *DEVICE_OBJECT
	FileObject        *FILE_OBJECT
	CompletionRoutine PIO_COMPLETION_ROUTINE
	Context           unsafe.Pointer
}

// IRP_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IRP_Anonymous_e__Union struct {
	Data [1]uint64
}

// IRP_AssociatedIrp_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IRP_AssociatedIrp_e__Union struct {
	Data [1]uint64
}

// IRP_Overlay_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IRP_Overlay_e__Union struct {
	Data [2]uint64
}

// IRP_Tail_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type IRP_Tail_e__Union struct {
	Data [11]uint64
}

type IRP struct {
	Type            int16
	Size            uint16
	MdlAddress      *MDL
	Flags           uint32
	AssociatedIrp   IRP_AssociatedIrp_e__Union
	ThreadListEntry win32systemkernel.LIST_ENTRY
	IoStatus        win32systemio.IO_STATUS_BLOCK
	RequestorMode   int8
	PendingReturned win32foundation.BOOLEAN
	StackCount      win32foundation.CHAR
	CurrentLocation win32foundation.CHAR
	Cancel          win32foundation.BOOLEAN
	CancelIrql      byte
	ApcEnvironment  int8
	AllocationFlags byte
	Anonymous       IRP_Anonymous_e__Union
	UserEvent       *KEVENT
	Overlay         IRP_Overlay_e__Union
	CancelRoutine   DRIVER_CANCEL
	UserBuffer      unsafe.Pointer
	Tail            IRP_Tail_e__Union
}

type KDEVICE_QUEUE struct {
	Type           int16
	Size           int16
	DeviceListHead win32systemkernel.LIST_ENTRY
	Lock           uintptr
	Busy           win32foundation.BOOLEAN
}

// KDPC_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type KDPC_Anonymous_e__Union struct {
	Data [1]uint32
}

type KDPC struct {
	Anonymous        KDPC_Anonymous_e__Union
	DpcListEntry     win32systemkernel.SINGLE_LIST_ENTRY
	ProcessorHistory uintptr
	DeferredRoutine  PKDEFERRED_ROUTINE
	DeferredContext  unsafe.Pointer
	SystemArgument1  unsafe.Pointer
	SystemArgument2  unsafe.Pointer
	DpcData          unsafe.Pointer
}

type KEVENT struct {
	Header DISPATCHER_HEADER
}

// KMUTANT_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type KMUTANT_Anonymous_e__Union struct {
	Data [1]byte
}

type KMUTANT struct {
	Header          DISPATCHER_HEADER
	MutantListEntry win32systemkernel.LIST_ENTRY
	OwnerThread     *uintptr
	Anonymous       KMUTANT_Anonymous_e__Union
	ApcDisable      byte
}

type KQUEUE struct {
	Header         DISPATCHER_HEADER
	EntryListHead  win32systemkernel.LIST_ENTRY
	CurrentCount   uint32
	MaximumCount   uint32
	ThreadListHead win32systemkernel.LIST_ENTRY
}

// KWAIT_BLOCK_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type KWAIT_BLOCK_Anonymous_e__Union struct {
	Data [1]uint64
}

type KWAIT_BLOCK struct {
	WaitListEntry win32systemkernel.LIST_ENTRY
	WaitType      byte
	BlockState    byte
	WaitKey       uint16
	Anonymous     KWAIT_BLOCK_Anonymous_e__Union
	Object        unsafe.Pointer
	SparePtr      unsafe.Pointer
}

type MDL struct {
	Next           *MDL
	Size           int16
	MdlFlags       int16
	Process        *uintptr
	MappedSystemVa unsafe.Pointer
	StartVa        unsafe.Pointer
	ByteCount      uint32
	ByteOffset     uint32
}

type OBJECT_ATTRIBUTES struct {
	Length                   uint32
	RootDirectory            win32foundation.HANDLE
	ObjectName               *win32foundation.UNICODE_STRING
	Attributes               win32foundation.OBJECT_ATTRIBUTE_FLAGS
	SecurityDescriptor       *win32security.SECURITY_DESCRIPTOR
	SecurityQualityOfService *win32security.SECURITY_QUALITY_OF_SERVICE
}

type OBJECT_ATTRIBUTES32 struct {
	Length                   uint32
	RootDirectory            uint32
	ObjectName               uint32
	Attributes               win32foundation.OBJECT_ATTRIBUTE_FLAGS
	SecurityDescriptor       *win32security.SECURITY_DESCRIPTOR
	SecurityQualityOfService *win32security.SECURITY_QUALITY_OF_SERVICE
}

type OBJECT_ATTRIBUTES64 struct {
	Length                   uint32
	RootDirectory            uint64
	ObjectName               uint64
	Attributes               win32foundation.OBJECT_ATTRIBUTE_FLAGS
	SecurityDescriptor       *win32security.SECURITY_DESCRIPTOR
	SecurityQualityOfService *win32security.SECURITY_QUALITY_OF_SERVICE
}

type OBJECT_NAME_INFORMATION struct {
	Name win32foundation.UNICODE_STRING
}

// OWNER_ENTRY_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type OWNER_ENTRY_Anonymous_e__Union struct {
	Data [1]uint32
}

type OWNER_ENTRY struct {
	OwnerThread uintptr
	Anonymous   OWNER_ENTRY_Anonymous_e__Union
}

type RTL_SPLAY_LINKS struct {
	Parent     *RTL_SPLAY_LINKS
	LeftChild  *RTL_SPLAY_LINKS
	RightChild *RTL_SPLAY_LINKS
}

type SECTION_OBJECT_POINTERS struct {
	DataSectionObject  unsafe.Pointer
	SharedCacheMap     unsafe.Pointer
	ImageSectionObject unsafe.Pointer
}

type SECURITY_SUBJECT_CONTEXT struct {
	ClientToken        unsafe.Pointer
	ImpersonationLevel win32security.SECURITY_IMPERSONATION_LEVEL
	PrimaryToken       unsafe.Pointer
	ProcessAuditId     unsafe.Pointer
}

type TARGET_DEVICE_CUSTOM_NOTIFICATION struct {
	Version          uint16
	Size             uint16
	Event            win32.GUID
	FileObject       *FILE_OBJECT
	NameBufferOffset int32
	CustomDataBuffer [1]byte
}

type VPB struct {
	Type              int16
	Size              int16
	Flags             uint16
	VolumeLabelLength uint16
	DeviceObject      *DEVICE_OBJECT
	RealDevice        *DEVICE_OBJECT
	SerialNumber      uint32
	ReferenceCount    uint32
	VolumeLabel       [32]uint16
}

type WORK_QUEUE_ITEM struct {
	List          win32systemkernel.LIST_ENTRY
	WorkerRoutine PWORKER_THREAD_ROUTINE
	Parameter     unsafe.Pointer
}
