// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package systeminformation

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

var (
	modntdll = win32.NewDLL("ntdll.dll")
)

var (
	procNtQuerySystemInformation = modntdll.NewProc("NtQuerySystemInformation")
	procNtQuerySystemTime        = modntdll.NewProc("NtQuerySystemTime")
	procNtQueryTimerResolution   = modntdll.NewProc("NtQueryTimerResolution")
	procZwQuerySystemInformation = modntdll.NewProc("ZwQuerySystemInformation")
	procZwQuerySystemTime        = modntdll.NewProc("ZwQuerySystemTime")
	procZwQueryTimerResolution   = modntdll.NewProc("ZwQueryTimerResolution")
)

// NtQuerySystemInformation calls ntdll!NtQuerySystemInformation.
func NtQuerySystemInformation(SystemInformationClass SYSTEM_INFORMATION_CLASS, SystemInformation unsafe.Pointer, SystemInformationLength uint32, ReturnLength *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtQuerySystemInformation.Addr(), uintptr(SystemInformationClass), uintptr(unsafe.Pointer(SystemInformation)), uintptr(SystemInformationLength), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtQuerySystemTime calls ntdll!NtQuerySystemTime.
func NtQuerySystemTime(SystemTime *int64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtQuerySystemTime.Addr(), uintptr(unsafe.Pointer(SystemTime)))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryTimerResolution calls ntdll!NtQueryTimerResolution.
func NtQueryTimerResolution(MaximumTime *uint32, MinimumTime *uint32, CurrentTime *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtQueryTimerResolution.Addr(), uintptr(unsafe.Pointer(MaximumTime)), uintptr(unsafe.Pointer(MinimumTime)), uintptr(unsafe.Pointer(CurrentTime)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQuerySystemInformation calls ntdll!ZwQuerySystemInformation.
func ZwQuerySystemInformation(SystemInformationClass SYSTEM_INFORMATION_CLASS, SystemInformation unsafe.Pointer, SystemInformationLength uint32, ReturnLength *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwQuerySystemInformation.Addr(), uintptr(SystemInformationClass), uintptr(unsafe.Pointer(SystemInformation)), uintptr(SystemInformationLength), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQuerySystemTime calls ntdll!ZwQuerySystemTime.
func ZwQuerySystemTime(SystemTime *int64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwQuerySystemTime.Addr(), uintptr(unsafe.Pointer(SystemTime)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQueryTimerResolution calls ntdll!ZwQueryTimerResolution.
func ZwQueryTimerResolution(MaximumTime *uint32, MinimumTime *uint32, CurrentTime *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwQueryTimerResolution.Addr(), uintptr(unsafe.Pointer(MaximumTime)), uintptr(unsafe.Pointer(MinimumTime)), uintptr(unsafe.Pointer(CurrentTime)))
	return win32foundation.NTSTATUS(r1)
}
