// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package systeminformation

import (
	"fmt"
)

type SYSTEM_INFORMATION_CLASS int32

const (
	SystemBasicInformation                SYSTEM_INFORMATION_CLASS = 0
	SystemPerformanceInformation          SYSTEM_INFORMATION_CLASS = 2
	SystemTimeOfDayInformation            SYSTEM_INFORMATION_CLASS = 3
	SystemProcessInformation              SYSTEM_INFORMATION_CLASS = 5
	SystemProcessorPerformanceInformation SYSTEM_INFORMATION_CLASS = 8
	SystemInterruptInformation            SYSTEM_INFORMATION_CLASS = 23
	SystemExceptionInformation            SYSTEM_INFORMATION_CLASS = 33
	SystemRegistryQuotaInformation        SYSTEM_INFORMATION_CLASS = 37
	SystemLookasideInformation            SYSTEM_INFORMATION_CLASS = 45
	SystemCodeIntegrityInformation        SYSTEM_INFORMATION_CLASS = 103
	SystemPolicyInformation               SYSTEM_INFORMATION_CLASS = 134
)

// String returns the SYSTEM_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e SYSTEM_INFORMATION_CLASS) String() string {
	switch e {
	case SystemBasicInformation:
		return "SystemBasicInformation"
	case SystemPerformanceInformation:
		return "SystemPerformanceInformation"
	case SystemTimeOfDayInformation:
		return "SystemTimeOfDayInformation"
	case SystemProcessInformation:
		return "SystemProcessInformation"
	case SystemProcessorPerformanceInformation:
		return "SystemProcessorPerformanceInformation"
	case SystemInterruptInformation:
		return "SystemInterruptInformation"
	case SystemExceptionInformation:
		return "SystemExceptionInformation"
	case SystemRegistryQuotaInformation:
		return "SystemRegistryQuotaInformation"
	case SystemLookasideInformation:
		return "SystemLookasideInformation"
	case SystemCodeIntegrityInformation:
		return "SystemCodeIntegrityInformation"
	case SystemPolicyInformation:
		return "SystemPolicyInformation"
	default:
		return fmt.Sprintf("SYSTEM_INFORMATION_CLASS(%d)", int32(e))
	}
}
