// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package direct3d

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/foundation"
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

var (
	modapi_ms_win_dx_d3dkmt_l1_1_4 = win32.NewDLL("api-ms-win-dx-d3dkmt-l1-1-4.dll")
	modapi_ms_win_dx_d3dkmt_l1_1_6 = win32.NewDLL("api-ms-win-dx-d3dkmt-l1-1-6.dll")
	modGDI32                       = win32.NewDLL("GDI32.dll")
)

var (
	procD3DKMTOutputDuplPresentToHwQueue               = modapi_ms_win_dx_d3dkmt_l1_1_4.NewProc("D3DKMTOutputDuplPresentToHwQueue")
	procD3DKMTSubmitPresentBltToHwQueue                = modapi_ms_win_dx_d3dkmt_l1_1_4.NewProc("D3DKMTSubmitPresentBltToHwQueue")
	procD3DKMTSubmitPresentToHwQueue                   = modapi_ms_win_dx_d3dkmt_l1_1_4.NewProc("D3DKMTSubmitPresentToHwQueue")
	procD3DKMTEnumAdapters3                            = modapi_ms_win_dx_d3dkmt_l1_1_6.NewProc("D3DKMTEnumAdapters3")
	procD3DKMTAcquireKeyedMutex                        = modGDI32.NewProc("D3DKMTAcquireKeyedMutex")
	procD3DKMTAcquireKeyedMutex2                       = modGDI32.NewProc("D3DKMTAcquireKeyedMutex2")
	procD3DKMTAdjustFullscreenGamma                    = modGDI32.NewProc("D3DKMTAdjustFullscreenGamma")
	procD3DKMTCancelPresents                           = modGDI32.NewProc("D3DKMTCancelPresents")
	procD3DKMTChangeSurfacePointer                     = modGDI32.NewProc("D3DKMTChangeSurfacePointer")
	procD3DKMTChangeVideoMemoryReservation             = modGDI32.NewProc("D3DKMTChangeVideoMemoryReservation")
	procD3DKMTCheckExclusiveOwnership                  = modGDI32.NewProc("D3DKMTCheckExclusiveOwnership")
	procD3DKMTCheckMonitorPowerState                   = modGDI32.NewProc("D3DKMTCheckMonitorPowerState")
	procD3DKMTCheckMultiPlaneOverlaySupport            = modGDI32.NewProc("D3DKMTCheckMultiPlaneOverlaySupport")
	procD3DKMTCheckMultiPlaneOverlaySupport2           = modGDI32.NewProc("D3DKMTCheckMultiPlaneOverlaySupport2")
	procD3DKMTCheckMultiPlaneOverlaySupport3           = modGDI32.NewProc("D3DKMTCheckMultiPlaneOverlaySupport3")
	procD3DKMTCheckOcclusion                           = modGDI32.NewProc("D3DKMTCheckOcclusion")
	procD3DKMTCheckSharedResourceAccess                = modGDI32.NewProc("D3DKMTCheckSharedResourceAccess")
	procD3DKMTCheckVidPnExclusiveOwnership             = modGDI32.NewProc("D3DKMTCheckVidPnExclusiveOwnership")
	procD3DKMTCloseAdapter                             = modGDI32.NewProc("D3DKMTCloseAdapter")
	procD3DKMTConfigureSharedResource                  = modGDI32.NewProc("D3DKMTConfigureSharedResource")
	procD3DKMTCreateAllocation                         = modGDI32.NewProc("D3DKMTCreateAllocation")
	procD3DKMTCreateAllocation2                        = modGDI32.NewProc("D3DKMTCreateAllocation2")
	procD3DKMTCreateContext                            = modGDI32.NewProc("D3DKMTCreateContext")
	procD3DKMTCreateContextVirtual                     = modGDI32.NewProc("D3DKMTCreateContextVirtual")
	procD3DKMTCreateDCFromMemory                       = modGDI32.NewProc("D3DKMTCreateDCFromMemory")
	procD3DKMTCreateDevice                             = modGDI32.NewProc("D3DKMTCreateDevice")
	procD3DKMTCreateHwContext                          = modGDI32.NewProc("D3DKMTCreateHwContext")
	procD3DKMTCreateHwQueue                            = modGDI32.NewProc("D3DKMTCreateHwQueue")
	procD3DKMTCreateKeyedMutex                         = modGDI32.NewProc("D3DKMTCreateKeyedMutex")
	procD3DKMTCreateKeyedMutex2                        = modGDI32.NewProc("D3DKMTCreateKeyedMutex2")
	procD3DKMTCreateOutputDupl                         = modGDI32.NewProc("D3DKMTCreateOutputDupl")
	procD3DKMTCreateOverlay                            = modGDI32.NewProc("D3DKMTCreateOverlay")
	procD3DKMTCreatePagingQueue                        = modGDI32.NewProc("D3DKMTCreatePagingQueue")
	procD3DKMTCreateProtectedSession                   = modGDI32.NewProc("D3DKMTCreateProtectedSession")
	procD3DKMTCreateSynchronizationObject              = modGDI32.NewProc("D3DKMTCreateSynchronizationObject")
	procD3DKMTCreateSynchronizationObject2             = modGDI32.NewProc("D3DKMTCreateSynchronizationObject2")
	procD3DKMTDestroyAllocation                        = modGDI32.NewProc("D3DKMTDestroyAllocation")
	procD3DKMTDestroyAllocation2                       = modGDI32.NewProc("D3DKMTDestroyAllocation2")
	procD3DKMTDestroyContext                           = modGDI32.NewProc("D3DKMTDestroyContext")
	procD3DKMTDestroyDCFromMemory                      = modGDI32.NewProc("D3DKMTDestroyDCFromMemory")
	procD3DKMTDestroyDevice                            = modGDI32.NewProc("D3DKMTDestroyDevice")
	procD3DKMTDestroyHwContext                         = modGDI32.NewProc("D3DKMTDestroyHwContext")
	procD3DKMTDestroyHwQueue                           = modGDI32.NewProc("D3DKMTDestroyHwQueue")
	procD3DKMTDestroyKeyedMutex                        = modGDI32.NewProc("D3DKMTDestroyKeyedMutex")
	procD3DKMTDestroyOutputDupl                        = modGDI32.NewProc("D3DKMTDestroyOutputDupl")
	procD3DKMTDestroyOverlay                           = modGDI32.NewProc("D3DKMTDestroyOverlay")
	procD3DKMTDestroyPagingQueue                       = modGDI32.NewProc("D3DKMTDestroyPagingQueue")
	procD3DKMTDestroyProtectedSession                  = modGDI32.NewProc("D3DKMTDestroyProtectedSession")
	procD3DKMTDestroySynchronizationObject             = modGDI32.NewProc("D3DKMTDestroySynchronizationObject")
	procD3DKMTEnumAdapters                             = modGDI32.NewProc("D3DKMTEnumAdapters")
	procD3DKMTEnumAdapters2                            = modGDI32.NewProc("D3DKMTEnumAdapters2")
	procD3DKMTEscape                                   = modGDI32.NewProc("D3DKMTEscape")
	procD3DKMTEvict                                    = modGDI32.NewProc("D3DKMTEvict")
	procD3DKMTFlipOverlay                              = modGDI32.NewProc("D3DKMTFlipOverlay")
	procD3DKMTFlushHeapTransitions                     = modGDI32.NewProc("D3DKMTFlushHeapTransitions")
	procD3DKMTFreeGpuVirtualAddress                    = modGDI32.NewProc("D3DKMTFreeGpuVirtualAddress")
	procD3DKMTGetAllocationPriority                    = modGDI32.NewProc("D3DKMTGetAllocationPriority")
	procD3DKMTGetContextInProcessSchedulingPriority    = modGDI32.NewProc("D3DKMTGetContextInProcessSchedulingPriority")
	procD3DKMTGetContextSchedulingPriority             = modGDI32.NewProc("D3DKMTGetContextSchedulingPriority")
	procD3DKMTGetDWMVerticalBlankEvent                 = modGDI32.NewProc("D3DKMTGetDWMVerticalBlankEvent")
	procD3DKMTGetDeviceState                           = modGDI32.NewProc("D3DKMTGetDeviceState")
	procD3DKMTGetDisplayModeList                       = modGDI32.NewProc("D3DKMTGetDisplayModeList")
	procD3DKMTGetMultiPlaneOverlayCaps                 = modGDI32.NewProc("D3DKMTGetMultiPlaneOverlayCaps")
	procD3DKMTGetMultisampleMethodList                 = modGDI32.NewProc("D3DKMTGetMultisampleMethodList")
	procD3DKMTGetOverlayState                          = modGDI32.NewProc("D3DKMTGetOverlayState")
	procD3DKMTGetPostCompositionCaps                   = modGDI32.NewProc("D3DKMTGetPostCompositionCaps")
	procD3DKMTGetPresentHistory                        = modGDI32.NewProc("D3DKMTGetPresentHistory")
	procD3DKMTGetPresentQueueEvent                     = modGDI32.NewProc("D3DKMTGetPresentQueueEvent")
	procD3DKMTGetProcessDeviceRemovalSupport           = modGDI32.NewProc("D3DKMTGetProcessDeviceRemovalSupport")
	procD3DKMTGetProcessSchedulingPriorityClass        = modGDI32.NewProc("D3DKMTGetProcessSchedulingPriorityClass")
	procD3DKMTGetResourcePresentPrivateDriverData      = modGDI32.NewProc("D3DKMTGetResourcePresentPrivateDriverData")
	procD3DKMTGetRuntimeData                           = modGDI32.NewProc("D3DKMTGetRuntimeData")
	procD3DKMTGetScanLine                              = modGDI32.NewProc("D3DKMTGetScanLine")
	procD3DKMTGetSharedPrimaryHandle                   = modGDI32.NewProc("D3DKMTGetSharedPrimaryHandle")
	procD3DKMTGetSharedResourceAdapterLuid             = modGDI32.NewProc("D3DKMTGetSharedResourceAdapterLuid")
	procD3DKMTInvalidateActiveVidPn                    = modGDI32.NewProc("D3DKMTInvalidateActiveVidPn")
	procD3DKMTInvalidateCache                          = modGDI32.NewProc("D3DKMTInvalidateCache")
	procD3DKMTLock                                     = modGDI32.NewProc("D3DKMTLock")
	procD3DKMTLock2                                    = modGDI32.NewProc("D3DKMTLock2")
	procD3DKMTMakeResident                             = modGDI32.NewProc("D3DKMTMakeResident")
	procD3DKMTMapGpuVirtualAddress                     = modGDI32.NewProc("D3DKMTMapGpuVirtualAddress")
	procD3DKMTMarkDeviceAsError                        = modGDI32.NewProc("D3DKMTMarkDeviceAsError")
	procD3DKMTOfferAllocations                         = modGDI32.NewProc("D3DKMTOfferAllocations")
	procD3DKMTOpenAdapterFromDeviceName                = modGDI32.NewProc("D3DKMTOpenAdapterFromDeviceName")
	procD3DKMTOpenAdapterFromGdiDisplayName            = modGDI32.NewProc("D3DKMTOpenAdapterFromGdiDisplayName")
	procD3DKMTOpenAdapterFromHdc                       = modGDI32.NewProc("D3DKMTOpenAdapterFromHdc")
	procD3DKMTOpenAdapterFromLuid                      = modGDI32.NewProc("D3DKMTOpenAdapterFromLuid")
	procD3DKMTOpenKeyedMutex                           = modGDI32.NewProc("D3DKMTOpenKeyedMutex")
	procD3DKMTOpenKeyedMutex2                          = modGDI32.NewProc("D3DKMTOpenKeyedMutex2")
	procD3DKMTOpenKeyedMutexFromNtHandle               = modGDI32.NewProc("D3DKMTOpenKeyedMutexFromNtHandle")
	procD3DKMTOpenNtHandleFromName                     = modGDI32.NewProc("D3DKMTOpenNtHandleFromName")
	procD3DKMTOpenProtectedSessionFromNtHandle         = modGDI32.NewProc("D3DKMTOpenProtectedSessionFromNtHandle")
	procD3DKMTOpenResource                             = modGDI32.NewProc("D3DKMTOpenResource")
	procD3DKMTOpenResource2                            = modGDI32.NewProc("D3DKMTOpenResource2")
	procD3DKMTOpenResourceFromNtHandle                 = modGDI32.NewProc("D3DKMTOpenResourceFromNtHandle")
	procD3DKMTOpenSyncObjectFromNtHandle               = modGDI32.NewProc("D3DKMTOpenSyncObjectFromNtHandle")
	procD3DKMTOpenSyncObjectFromNtHandle2              = modGDI32.NewProc("D3DKMTOpenSyncObjectFromNtHandle2")
	procD3DKMTOpenSyncObjectNtHandleFromName           = modGDI32.NewProc("D3DKMTOpenSyncObjectNtHandleFromName")
	procD3DKMTOpenSynchronizationObject                = modGDI32.NewProc("D3DKMTOpenSynchronizationObject")
	procD3DKMTOutputDuplGetFrameInfo                   = modGDI32.NewProc("D3DKMTOutputDuplGetFrameInfo")
	procD3DKMTOutputDuplGetMetaData                    = modGDI32.NewProc("D3DKMTOutputDuplGetMetaData")
	procD3DKMTOutputDuplGetPointerShapeData            = modGDI32.NewProc("D3DKMTOutputDuplGetPointerShapeData")
	procD3DKMTOutputDuplPresent                        = modGDI32.NewProc("D3DKMTOutputDuplPresent")
	procD3DKMTOutputDuplReleaseFrame                   = modGDI32.NewProc("D3DKMTOutputDuplReleaseFrame")
	procD3DKMTPollDisplayChildren                      = modGDI32.NewProc("D3DKMTPollDisplayChildren")
	procD3DKMTPresent                                  = modGDI32.NewProc("D3DKMTPresent")
	procD3DKMTPresentMultiPlaneOverlay                 = modGDI32.NewProc("D3DKMTPresentMultiPlaneOverlay")
	procD3DKMTPresentMultiPlaneOverlay2                = modGDI32.NewProc("D3DKMTPresentMultiPlaneOverlay2")
	procD3DKMTPresentMultiPlaneOverlay3                = modGDI32.NewProc("D3DKMTPresentMultiPlaneOverlay3")
	procD3DKMTPresentRedirected                        = modGDI32.NewProc("D3DKMTPresentRedirected")
	procD3DKMTQueryAdapterInfo                         = modGDI32.NewProc("D3DKMTQueryAdapterInfo")
	procD3DKMTQueryAllocationResidency                 = modGDI32.NewProc("D3DKMTQueryAllocationResidency")
	procD3DKMTQueryClockCalibration                    = modGDI32.NewProc("D3DKMTQueryClockCalibration")
	procD3DKMTQueryFSEBlock                            = modGDI32.NewProc("D3DKMTQueryFSEBlock")
	procD3DKMTQueryProcessOfferInfo                    = modGDI32.NewProc("D3DKMTQueryProcessOfferInfo")
	procD3DKMTQueryProtectedSessionInfoFromNtHandle    = modGDI32.NewProc("D3DKMTQueryProtectedSessionInfoFromNtHandle")
	procD3DKMTQueryProtectedSessionStatus              = modGDI32.NewProc("D3DKMTQueryProtectedSessionStatus")
	procD3DKMTQueryRemoteVidPnSourceFromGdiDisplayName = modGDI32.NewProc("D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName")
	procD3DKMTQueryResourceInfo                        = modGDI32.NewProc("D3DKMTQueryResourceInfo")
	procD3DKMTQueryResourceInfoFromNtHandle            = modGDI32.NewProc("D3DKMTQueryResourceInfoFromNtHandle")
	procD3DKMTQueryStatistics                          = modGDI32.NewProc("D3DKMTQueryStatistics")
	procD3DKMTQueryVidPnExclusiveOwnership             = modGDI32.NewProc("D3DKMTQueryVidPnExclusiveOwnership")
	procD3DKMTQueryVideoMemoryInfo                     = modGDI32.NewProc("D3DKMTQueryVideoMemoryInfo")
	procD3DKMTReclaimAllocations                       = modGDI32.NewProc("D3DKMTReclaimAllocations")
	procD3DKMTReclaimAllocations2                      = modGDI32.NewProc("D3DKMTReclaimAllocations2")
	procD3DKMTRegisterTrimNotification                 = modGDI32.NewProc("D3DKMTRegisterTrimNotification")
	procD3DKMTRegisterVailProcess                      = modGDI32.NewProc("D3DKMTRegisterVailProcess")
	procD3DKMTReleaseKeyedMutex                        = modGDI32.NewProc("D3DKMTReleaseKeyedMutex")
	procD3DKMTReleaseKeyedMutex2                       = modGDI32.NewProc("D3DKMTReleaseKeyedMutex2")
	procD3DKMTReleaseProcessVidPnSourceOwners          = modGDI32.NewProc("D3DKMTReleaseProcessVidPnSourceOwners")
	procD3DKMTRender                                   = modGDI32.NewProc("D3DKMTRender")
	procD3DKMTReserveGpuVirtualAddress                 = modGDI32.NewProc("D3DKMTReserveGpuVirtualAddress")
	procD3DKMTSetAllocationPriority                    = modGDI32.NewProc("D3DKMTSetAllocationPriority")
	procD3DKMTSetContextInProcessSchedulingPriority    = modGDI32.NewProc("D3DKMTSetContextInProcessSchedulingPriority")
	procD3DKMTSetContextSchedulingPriority             = modGDI32.NewProc("D3DKMTSetContextSchedulingPriority")
	procD3DKMTSetDisplayMode                           = modGDI32.NewProc("D3DKMTSetDisplayMode")
	procD3DKMTSetDisplayPrivateDriverFormat            = modGDI32.NewProc("D3DKMTSetDisplayPrivateDriverFormat")
	procD3DKMTSetFSEBlock                              = modGDI32.NewProc("D3DKMTSetFSEBlock")
	procD3DKMTSetGammaRamp                             = modGDI32.NewProc("D3DKMTSetGammaRamp")
	procD3DKMTSetHwProtectionTeardownRecovery          = modGDI32.NewProc("D3DKMTSetHwProtectionTeardownRecovery")
	procD3DKMTSetMonitorColorSpaceTransform            = modGDI32.NewProc("D3DKMTSetMonitorColorSpaceTransform")
	procD3DKMTSetProcessSchedulingPriorityClass        = modGDI32.NewProc("D3DKMTSetProcessSchedulingPriorityClass")
	procD3DKMTSetQueuedLimit                           = modGDI32.NewProc("D3DKMTSetQueuedLimit")
	procD3DKMTSetStablePowerState                      = modGDI32.NewProc("D3DKMTSetStablePowerState")
	procD3DKMTSetSyncRefreshCountWaitTarget            = modGDI32.NewProc("D3DKMTSetSyncRefreshCountWaitTarget")
	procD3DKMTSetVidPnSourceHwProtection               = modGDI32.NewProc("D3DKMTSetVidPnSourceHwProtection")
	procD3DKMTSetVidPnSourceOwner                      = modGDI32.NewProc("D3DKMTSetVidPnSourceOwner")
	procD3DKMTSetVidPnSourceOwner1                     = modGDI32.NewProc("D3DKMTSetVidPnSourceOwner1")
	procD3DKMTSetVidPnSourceOwner2                     = modGDI32.NewProc("D3DKMTSetVidPnSourceOwner2")
	procD3DKMTShareObjects                             = modGDI32.NewProc("D3DKMTShareObjects")
	procD3DKMTSharedPrimaryLockNotification            = modGDI32.NewProc("D3DKMTSharedPrimaryLockNotification")
	procD3DKMTSharedPrimaryUnLockNotification          = modGDI32.NewProc("D3DKMTSharedPrimaryUnLockNotification")
	procD3DKMTSignalSynchronizationObject              = modGDI32.NewProc("D3DKMTSignalSynchronizationObject")
	procD3DKMTSignalSynchronizationObject2             = modGDI32.NewProc("D3DKMTSignalSynchronizationObject2")
	procD3DKMTSignalSynchronizationObjectFromCpu       = modGDI32.NewProc("D3DKMTSignalSynchronizationObjectFromCpu")
	procD3DKMTSignalSynchronizationObjectFromGpu       = modGDI32.NewProc("D3DKMTSignalSynchronizationObjectFromGpu")
	procD3DKMTSignalSynchronizationObjectFromGpu2      = modGDI32.NewProc("D3DKMTSignalSynchronizationObjectFromGpu2")
	procD3DKMTSubmitCommand                            = modGDI32.NewProc("D3DKMTSubmitCommand")
	procD3DKMTSubmitCommandToHwQueue                   = modGDI32.NewProc("D3DKMTSubmitCommandToHwQueue")
	procD3DKMTSubmitSignalSyncObjectsToHwQueue         = modGDI32.NewProc("D3DKMTSubmitSignalSyncObjectsToHwQueue")
	procD3DKMTSubmitWaitForSyncObjectsToHwQueue        = modGDI32.NewProc("D3DKMTSubmitWaitForSyncObjectsToHwQueue")
	procD3DKMTTrimProcessCommitment                    = modGDI32.NewProc("D3DKMTTrimProcessCommitment")
	procD3DKMTUnlock                                   = modGDI32.NewProc("D3DKMTUnlock")
	procD3DKMTUnlock2                                  = modGDI32.NewProc("D3DKMTUnlock2")
	procD3DKMTUnregisterTrimNotification               = modGDI32.NewProc("D3DKMTUnregisterTrimNotification")
	procD3DKMTUpdateAllocationProperty                 = modGDI32.NewProc("D3DKMTUpdateAllocationProperty")
	procD3DKMTUpdateGpuVirtualAddress                  = modGDI32.NewProc("D3DKMTUpdateGpuVirtualAddress")
	procD3DKMTUpdateOverlay                            = modGDI32.NewProc("D3DKMTUpdateOverlay")
	procD3DKMTWaitForIdle                              = modGDI32.NewProc("D3DKMTWaitForIdle")
	procD3DKMTWaitForSynchronizationObject             = modGDI32.NewProc("D3DKMTWaitForSynchronizationObject")
	procD3DKMTWaitForSynchronizationObject2            = modGDI32.NewProc("D3DKMTWaitForSynchronizationObject2")
	procD3DKMTWaitForSynchronizationObjectFromCpu      = modGDI32.NewProc("D3DKMTWaitForSynchronizationObjectFromCpu")
	procD3DKMTWaitForSynchronizationObjectFromGpu      = modGDI32.NewProc("D3DKMTWaitForSynchronizationObjectFromGpu")
	procD3DKMTWaitForVerticalBlankEvent                = modGDI32.NewProc("D3DKMTWaitForVerticalBlankEvent")
	procD3DKMTWaitForVerticalBlankEvent2               = modGDI32.NewProc("D3DKMTWaitForVerticalBlankEvent2")
)

// D3DKMTAcquireKeyedMutex calls GDI32!D3DKMTAcquireKeyedMutex.
func D3DKMTAcquireKeyedMutex(param0 *D3DKMT_ACQUIREKEYEDMUTEX) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTAcquireKeyedMutex.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTAcquireKeyedMutex2 calls GDI32!D3DKMTAcquireKeyedMutex2.
func D3DKMTAcquireKeyedMutex2(param0 *D3DKMT_ACQUIREKEYEDMUTEX2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTAcquireKeyedMutex2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTAdjustFullscreenGamma calls GDI32!D3DKMTAdjustFullscreenGamma.
func D3DKMTAdjustFullscreenGamma(param0 *D3DKMT_ADJUSTFULLSCREENGAMMA) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTAdjustFullscreenGamma.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCancelPresents calls GDI32!D3DKMTCancelPresents.
func D3DKMTCancelPresents(param0 *D3DKMT_CANCEL_PRESENTS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCancelPresents.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTChangeSurfacePointer calls GDI32!D3DKMTChangeSurfacePointer.
func D3DKMTChangeSurfacePointer(param0 *D3DKMT_CHANGESURFACEPOINTER) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTChangeSurfacePointer.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTChangeVideoMemoryReservation calls GDI32!D3DKMTChangeVideoMemoryReservation.
func D3DKMTChangeVideoMemoryReservation(param0 *D3DKMT_CHANGEVIDEOMEMORYRESERVATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTChangeVideoMemoryReservation.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckExclusiveOwnership calls GDI32!D3DKMTCheckExclusiveOwnership.
func D3DKMTCheckExclusiveOwnership() win32foundation.BOOLEAN {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckExclusiveOwnership.Addr())
	return win32foundation.BOOLEAN(r1)
}

// D3DKMTCheckMonitorPowerState calls GDI32!D3DKMTCheckMonitorPowerState.
func D3DKMTCheckMonitorPowerState(param0 *D3DKMT_CHECKMONITORPOWERSTATE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckMonitorPowerState.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckMultiPlaneOverlaySupport calls GDI32!D3DKMTCheckMultiPlaneOverlaySupport.
func D3DKMTCheckMultiPlaneOverlaySupport(param0 *D3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckMultiPlaneOverlaySupport.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckMultiPlaneOverlaySupport2 calls GDI32!D3DKMTCheckMultiPlaneOverlaySupport2.
func D3DKMTCheckMultiPlaneOverlaySupport2(param0 *D3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckMultiPlaneOverlaySupport2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckMultiPlaneOverlaySupport3 calls GDI32!D3DKMTCheckMultiPlaneOverlaySupport3.
func D3DKMTCheckMultiPlaneOverlaySupport3(param0 *D3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT3) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckMultiPlaneOverlaySupport3.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckOcclusion calls GDI32!D3DKMTCheckOcclusion.
func D3DKMTCheckOcclusion(param0 *D3DKMT_CHECKOCCLUSION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckOcclusion.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckSharedResourceAccess calls GDI32!D3DKMTCheckSharedResourceAccess.
func D3DKMTCheckSharedResourceAccess(param0 *D3DKMT_CHECKSHAREDRESOURCEACCESS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckSharedResourceAccess.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCheckVidPnExclusiveOwnership calls GDI32!D3DKMTCheckVidPnExclusiveOwnership.
func D3DKMTCheckVidPnExclusiveOwnership(param0 *D3DKMT_CHECKVIDPNEXCLUSIVEOWNERSHIP) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCheckVidPnExclusiveOwnership.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCloseAdapter calls GDI32!D3DKMTCloseAdapter.
func D3DKMTCloseAdapter(param0 *D3DKMT_CLOSEADAPTER) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCloseAdapter.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTConfigureSharedResource calls GDI32!D3DKMTConfigureSharedResource.
func D3DKMTConfigureSharedResource(param0 *D3DKMT_CONFIGURESHAREDRESOURCE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTConfigureSharedResource.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateAllocation calls GDI32!D3DKMTCreateAllocation.
func D3DKMTCreateAllocation(param0 *D3DKMT_CREATEALLOCATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateAllocation.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateAllocation2 calls GDI32!D3DKMTCreateAllocation2.
func D3DKMTCreateAllocation2(param0 *D3DKMT_CREATEALLOCATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateAllocation2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateContext calls GDI32!D3DKMTCreateContext.
func D3DKMTCreateContext(param0 *D3DKMT_CREATECONTEXT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateContext.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateContextVirtual calls GDI32!D3DKMTCreateContextVirtual.
func D3DKMTCreateContextVirtual(param0 *D3DKMT_CREATECONTEXTVIRTUAL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateContextVirtual.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateDCFromMemory calls GDI32!D3DKMTCreateDCFromMemory.
func D3DKMTCreateDCFromMemory(param0 *D3DKMT_CREATEDCFROMMEMORY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateDCFromMemory.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateDevice calls GDI32!D3DKMTCreateDevice.
func D3DKMTCreateDevice(param0 *D3DKMT_CREATEDEVICE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateDevice.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateHwContext calls GDI32!D3DKMTCreateHwContext.
func D3DKMTCreateHwContext(param0 *D3DKMT_CREATEHWCONTEXT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateHwContext.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateHwQueue calls GDI32!D3DKMTCreateHwQueue.
func D3DKMTCreateHwQueue(param0 *D3DKMT_CREATEHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateKeyedMutex calls GDI32!D3DKMTCreateKeyedMutex.
func D3DKMTCreateKeyedMutex(param0 *D3DKMT_CREATEKEYEDMUTEX) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateKeyedMutex.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateKeyedMutex2 calls GDI32!D3DKMTCreateKeyedMutex2.
func D3DKMTCreateKeyedMutex2(param0 *D3DKMT_CREATEKEYEDMUTEX2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateKeyedMutex2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateOutputDupl calls GDI32!D3DKMTCreateOutputDupl.
func D3DKMTCreateOutputDupl(param0 *D3DKMT_CREATE_OUTPUTDUPL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateOutputDupl.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateOverlay calls GDI32!D3DKMTCreateOverlay.
func D3DKMTCreateOverlay(param0 *D3DKMT_CREATEOVERLAY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateOverlay.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreatePagingQueue calls GDI32!D3DKMTCreatePagingQueue.
func D3DKMTCreatePagingQueue(param0 *D3DKMT_CREATEPAGINGQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreatePagingQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateProtectedSession calls GDI32!D3DKMTCreateProtectedSession.
func D3DKMTCreateProtectedSession(param0 *D3DKMT_CREATEPROTECTEDSESSION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateProtectedSession.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateSynchronizationObject calls GDI32!D3DKMTCreateSynchronizationObject.
func D3DKMTCreateSynchronizationObject(param0 *D3DKMT_CREATESYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateSynchronizationObject.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTCreateSynchronizationObject2 calls GDI32!D3DKMTCreateSynchronizationObject2.
func D3DKMTCreateSynchronizationObject2(param0 *D3DKMT_CREATESYNCHRONIZATIONOBJECT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTCreateSynchronizationObject2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyAllocation calls GDI32!D3DKMTDestroyAllocation.
func D3DKMTDestroyAllocation(param0 *D3DKMT_DESTROYALLOCATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyAllocation.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyAllocation2 calls GDI32!D3DKMTDestroyAllocation2.
func D3DKMTDestroyAllocation2(param0 *D3DKMT_DESTROYALLOCATION2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyAllocation2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyContext calls GDI32!D3DKMTDestroyContext.
func D3DKMTDestroyContext(param0 *D3DKMT_DESTROYCONTEXT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyContext.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyDCFromMemory calls GDI32!D3DKMTDestroyDCFromMemory.
func D3DKMTDestroyDCFromMemory(param0 *D3DKMT_DESTROYDCFROMMEMORY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyDCFromMemory.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyDevice calls GDI32!D3DKMTDestroyDevice.
func D3DKMTDestroyDevice(param0 *D3DKMT_DESTROYDEVICE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyDevice.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyHwContext calls GDI32!D3DKMTDestroyHwContext.
func D3DKMTDestroyHwContext(param0 *D3DKMT_DESTROYHWCONTEXT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyHwContext.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyHwQueue calls GDI32!D3DKMTDestroyHwQueue.
func D3DKMTDestroyHwQueue(param0 *D3DKMT_DESTROYHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyKeyedMutex calls GDI32!D3DKMTDestroyKeyedMutex.
func D3DKMTDestroyKeyedMutex(param0 *D3DKMT_DESTROYKEYEDMUTEX) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyKeyedMutex.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyOutputDupl calls GDI32!D3DKMTDestroyOutputDupl.
func D3DKMTDestroyOutputDupl(param0 *D3DKMT_DESTROY_OUTPUTDUPL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyOutputDupl.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyOverlay calls GDI32!D3DKMTDestroyOverlay.
func D3DKMTDestroyOverlay(param0 *D3DKMT_DESTROYOVERLAY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyOverlay.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyPagingQueue calls GDI32!D3DKMTDestroyPagingQueue.
func D3DKMTDestroyPagingQueue(param0 *D3DDDI_DESTROYPAGINGQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyPagingQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroyProtectedSession calls GDI32!D3DKMTDestroyProtectedSession.
func D3DKMTDestroyProtectedSession(param0 *D3DKMT_DESTROYPROTECTEDSESSION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroyProtectedSession.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTDestroySynchronizationObject calls GDI32!D3DKMTDestroySynchronizationObject.
func D3DKMTDestroySynchronizationObject(param0 *D3DKMT_DESTROYSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTDestroySynchronizationObject.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTEnumAdapters calls GDI32!D3DKMTEnumAdapters.
func D3DKMTEnumAdapters(param0 *D3DKMT_ENUMADAPTERS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTEnumAdapters.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTEnumAdapters2 calls GDI32!D3DKMTEnumAdapters2.
func D3DKMTEnumAdapters2(param0 *D3DKMT_ENUMADAPTERS2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTEnumAdapters2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTEnumAdapters3 calls api-ms-win-dx-d3dkmt-l1-1-6!D3DKMTEnumAdapters3.
func D3DKMTEnumAdapters3(param0 *D3DKMT_ENUMADAPTERS3) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTEnumAdapters3.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTEscape calls GDI32!D3DKMTEscape.
func D3DKMTEscape(param0 *D3DKMT_ESCAPE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTEscape.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTEvict calls GDI32!D3DKMTEvict.
func D3DKMTEvict(param0 *D3DKMT_EVICT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTEvict.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTFlipOverlay calls GDI32!D3DKMTFlipOverlay.
func D3DKMTFlipOverlay(param0 *D3DKMT_FLIPOVERLAY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTFlipOverlay.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTFlushHeapTransitions calls GDI32!D3DKMTFlushHeapTransitions.
func D3DKMTFlushHeapTransitions(param0 *D3DKMT_FLUSHHEAPTRANSITIONS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTFlushHeapTransitions.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTFreeGpuVirtualAddress calls GDI32!D3DKMTFreeGpuVirtualAddress.
func D3DKMTFreeGpuVirtualAddress(param0 *D3DKMT_FREEGPUVIRTUALADDRESS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTFreeGpuVirtualAddress.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetAllocationPriority calls GDI32!D3DKMTGetAllocationPriority.
func D3DKMTGetAllocationPriority(param0 *D3DKMT_GETALLOCATIONPRIORITY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetAllocationPriority.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetContextInProcessSchedulingPriority calls GDI32!D3DKMTGetContextInProcessSchedulingPriority.
func D3DKMTGetContextInProcessSchedulingPriority(param0 *D3DKMT_GETCONTEXTINPROCESSSCHEDULINGPRIORITY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetContextInProcessSchedulingPriority.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetContextSchedulingPriority calls GDI32!D3DKMTGetContextSchedulingPriority.
func D3DKMTGetContextSchedulingPriority(param0 *D3DKMT_GETCONTEXTSCHEDULINGPRIORITY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetContextSchedulingPriority.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetDWMVerticalBlankEvent calls GDI32!D3DKMTGetDWMVerticalBlankEvent.
func D3DKMTGetDWMVerticalBlankEvent(param0 *D3DKMT_GETVERTICALBLANKEVENT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetDWMVerticalBlankEvent.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetDeviceState calls GDI32!D3DKMTGetDeviceState.
func D3DKMTGetDeviceState(param0 *D3DKMT_GETDEVICESTATE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetDeviceState.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetDisplayModeList calls GDI32!D3DKMTGetDisplayModeList.
func D3DKMTGetDisplayModeList(param0 *D3DKMT_GETDISPLAYMODELIST) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetDisplayModeList.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetMultiPlaneOverlayCaps calls GDI32!D3DKMTGetMultiPlaneOverlayCaps.
func D3DKMTGetMultiPlaneOverlayCaps(param0 *D3DKMT_GET_MULTIPLANE_OVERLAY_CAPS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetMultiPlaneOverlayCaps.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetMultisampleMethodList calls GDI32!D3DKMTGetMultisampleMethodList.
func D3DKMTGetMultisampleMethodList(param0 *D3DKMT_GETMULTISAMPLEMETHODLIST) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetMultisampleMethodList.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetOverlayState calls GDI32!D3DKMTGetOverlayState.
func D3DKMTGetOverlayState(param0 *D3DKMT_GETOVERLAYSTATE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetOverlayState.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetPostCompositionCaps calls GDI32!D3DKMTGetPostCompositionCaps.
func D3DKMTGetPostCompositionCaps(param0 *D3DKMT_GET_POST_COMPOSITION_CAPS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetPostCompositionCaps.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetPresentHistory calls GDI32!D3DKMTGetPresentHistory.
func D3DKMTGetPresentHistory(param0 *D3DKMT_GETPRESENTHISTORY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetPresentHistory.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetPresentQueueEvent calls GDI32!D3DKMTGetPresentQueueEvent.
func D3DKMTGetPresentQueueEvent(hAdapter uint32, param1 *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetPresentQueueEvent.Addr(), uintptr(hAdapter), uintptr(unsafe.Pointer(param1)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetProcessDeviceRemovalSupport calls GDI32!D3DKMTGetProcessDeviceRemovalSupport.
func D3DKMTGetProcessDeviceRemovalSupport(param0 *D3DKMT_GETPROCESSDEVICEREMOVALSUPPORT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetProcessDeviceRemovalSupport.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetProcessSchedulingPriorityClass calls GDI32!D3DKMTGetProcessSchedulingPriorityClass.
func D3DKMTGetProcessSchedulingPriorityClass(param0 win32foundation.HANDLE, param1 *D3DKMT_SCHEDULINGPRIORITYCLASS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetProcessSchedulingPriorityClass.Addr(), uintptr(param0), uintptr(unsafe.Pointer(param1)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetResourcePresentPrivateDriverData calls GDI32!D3DKMTGetResourcePresentPrivateDriverData.
func D3DKMTGetResourcePresentPrivateDriverData(param0 *D3DDDI_GETRESOURCEPRESENTPRIVATEDRIVERDATA) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetResourcePresentPrivateDriverData.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetRuntimeData calls GDI32!D3DKMTGetRuntimeData.
func D3DKMTGetRuntimeData(param0 *D3DKMT_GETRUNTIMEDATA) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetRuntimeData.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetScanLine calls GDI32!D3DKMTGetScanLine.
func D3DKMTGetScanLine(param0 *D3DKMT_GETSCANLINE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetScanLine.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetSharedPrimaryHandle calls GDI32!D3DKMTGetSharedPrimaryHandle.
func D3DKMTGetSharedPrimaryHandle(param0 *D3DKMT_GETSHAREDPRIMARYHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetSharedPrimaryHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTGetSharedResourceAdapterLuid calls GDI32!D3DKMTGetSharedResourceAdapterLuid.
func D3DKMTGetSharedResourceAdapterLuid(param0 *D3DKMT_GETSHAREDRESOURCEADAPTERLUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTGetSharedResourceAdapterLuid.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTInvalidateActiveVidPn calls GDI32!D3DKMTInvalidateActiveVidPn.
func D3DKMTInvalidateActiveVidPn(param0 *D3DKMT_INVALIDATEACTIVEVIDPN) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTInvalidateActiveVidPn.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTInvalidateCache calls GDI32!D3DKMTInvalidateCache.
func D3DKMTInvalidateCache(param0 *D3DKMT_INVALIDATECACHE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTInvalidateCache.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTLock calls GDI32!D3DKMTLock.
func D3DKMTLock(param0 *D3DKMT_LOCK) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTLock.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTLock2 calls GDI32!D3DKMTLock2.
func D3DKMTLock2(param0 *D3DKMT_LOCK2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTLock2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTMakeResident calls GDI32!D3DKMTMakeResident.
func D3DKMTMakeResident(param0 *D3DDDI_MAKERESIDENT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTMakeResident.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTMapGpuVirtualAddress calls GDI32!D3DKMTMapGpuVirtualAddress.
func D3DKMTMapGpuVirtualAddress(param0 *D3DDDI_MAPGPUVIRTUALADDRESS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTMapGpuVirtualAddress.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTMarkDeviceAsError calls GDI32!D3DKMTMarkDeviceAsError.
func D3DKMTMarkDeviceAsError(param0 *D3DKMT_MARKDEVICEASERROR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTMarkDeviceAsError.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOfferAllocations calls GDI32!D3DKMTOfferAllocations.
func D3DKMTOfferAllocations(param0 *D3DKMT_OFFERALLOCATIONS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOfferAllocations.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenAdapterFromDeviceName calls GDI32!D3DKMTOpenAdapterFromDeviceName.
func D3DKMTOpenAdapterFromDeviceName(param0 *D3DKMT_OPENADAPTERFROMDEVICENAME) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenAdapterFromDeviceName.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenAdapterFromGdiDisplayName calls GDI32!D3DKMTOpenAdapterFromGdiDisplayName.
func D3DKMTOpenAdapterFromGdiDisplayName(param0 *D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenAdapterFromGdiDisplayName.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenAdapterFromHdc calls GDI32!D3DKMTOpenAdapterFromHdc.
func D3DKMTOpenAdapterFromHdc(param0 *D3DKMT_OPENADAPTERFROMHDC) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenAdapterFromHdc.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenAdapterFromLuid calls GDI32!D3DKMTOpenAdapterFromLuid.
func D3DKMTOpenAdapterFromLuid(param0 *D3DKMT_OPENADAPTERFROMLUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenAdapterFromLuid.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenKeyedMutex calls GDI32!D3DKMTOpenKeyedMutex.
func D3DKMTOpenKeyedMutex(param0 *D3DKMT_OPENKEYEDMUTEX) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenKeyedMutex.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenKeyedMutex2 calls GDI32!D3DKMTOpenKeyedMutex2.
func D3DKMTOpenKeyedMutex2(param0 *D3DKMT_OPENKEYEDMUTEX2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenKeyedMutex2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenKeyedMutexFromNtHandle calls GDI32!D3DKMTOpenKeyedMutexFromNtHandle.
func D3DKMTOpenKeyedMutexFromNtHandle(param0 *D3DKMT_OPENKEYEDMUTEXFROMNTHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenKeyedMutexFromNtHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenNtHandleFromName calls GDI32!D3DKMTOpenNtHandleFromName.
func D3DKMTOpenNtHandleFromName(param0 *D3DKMT_OPENNTHANDLEFROMNAME) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenNtHandleFromName.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenProtectedSessionFromNtHandle calls GDI32!D3DKMTOpenProtectedSessionFromNtHandle.
func D3DKMTOpenProtectedSessionFromNtHandle(param0 *D3DKMT_OPENPROTECTEDSESSIONFROMNTHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenProtectedSessionFromNtHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenResource calls GDI32!D3DKMTOpenResource.
func D3DKMTOpenResource(param0 *D3DKMT_OPENRESOURCE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenResource.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenResource2 calls GDI32!D3DKMTOpenResource2.
func D3DKMTOpenResource2(param0 *D3DKMT_OPENRESOURCE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenResource2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenResourceFromNtHandle calls GDI32!D3DKMTOpenResourceFromNtHandle.
func D3DKMTOpenResourceFromNtHandle(param0 *D3DKMT_OPENRESOURCEFROMNTHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenResourceFromNtHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenSyncObjectFromNtHandle calls GDI32!D3DKMTOpenSyncObjectFromNtHandle.
func D3DKMTOpenSyncObjectFromNtHandle(param0 *D3DKMT_OPENSYNCOBJECTFROMNTHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenSyncObjectFromNtHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenSyncObjectFromNtHandle2 calls GDI32!D3DKMTOpenSyncObjectFromNtHandle2.
func D3DKMTOpenSyncObjectFromNtHandle2(param0 *D3DKMT_OPENSYNCOBJECTFROMNTHANDLE2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenSyncObjectFromNtHandle2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenSyncObjectNtHandleFromName calls GDI32!D3DKMTOpenSyncObjectNtHandleFromName.
func D3DKMTOpenSyncObjectNtHandleFromName(param0 *D3DKMT_OPENSYNCOBJECTNTHANDLEFROMNAME) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenSyncObjectNtHandleFromName.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOpenSynchronizationObject calls GDI32!D3DKMTOpenSynchronizationObject.
func D3DKMTOpenSynchronizationObject(param0 *D3DKMT_OPENSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOpenSynchronizationObject.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOutputDuplGetFrameInfo calls GDI32!D3DKMTOutputDuplGetFrameInfo.
func D3DKMTOutputDuplGetFrameInfo(param0 *D3DKMT_OUTPUTDUPL_GET_FRAMEINFO) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOutputDuplGetFrameInfo.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOutputDuplGetMetaData calls GDI32!D3DKMTOutputDuplGetMetaData.
func D3DKMTOutputDuplGetMetaData(param0 *D3DKMT_OUTPUTDUPL_METADATA) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOutputDuplGetMetaData.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOutputDuplGetPointerShapeData calls GDI32!D3DKMTOutputDuplGetPointerShapeData.
func D3DKMTOutputDuplGetPointerShapeData(param0 *D3DKMT_OUTPUTDUPL_GET_POINTER_SHAPE_DATA) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOutputDuplGetPointerShapeData.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOutputDuplPresent calls GDI32!D3DKMTOutputDuplPresent.
func D3DKMTOutputDuplPresent(param0 *D3DKMT_OUTPUTDUPLPRESENT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOutputDuplPresent.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOutputDuplPresentToHwQueue calls api-ms-win-dx-d3dkmt-l1-1-4!D3DKMTOutputDuplPresentToHwQueue.
func D3DKMTOutputDuplPresentToHwQueue(param0 *D3DKMT_OUTPUTDUPLPRESENTTOHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOutputDuplPresentToHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTOutputDuplReleaseFrame calls GDI32!D3DKMTOutputDuplReleaseFrame.
func D3DKMTOutputDuplReleaseFrame(param0 *D3DKMT_OUTPUTDUPL_RELEASE_FRAME) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTOutputDuplReleaseFrame.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTPollDisplayChildren calls GDI32!D3DKMTPollDisplayChildren.
func D3DKMTPollDisplayChildren(param0 *D3DKMT_POLLDISPLAYCHILDREN) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTPollDisplayChildren.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTPresent calls GDI32!D3DKMTPresent.
func D3DKMTPresent(param0 *D3DKMT_PRESENT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTPresent.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTPresentMultiPlaneOverlay calls GDI32!D3DKMTPresentMultiPlaneOverlay.
func D3DKMTPresentMultiPlaneOverlay(param0 *D3DKMT_PRESENT_MULTIPLANE_OVERLAY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTPresentMultiPlaneOverlay.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTPresentMultiPlaneOverlay2 calls GDI32!D3DKMTPresentMultiPlaneOverlay2.
func D3DKMTPresentMultiPlaneOverlay2(param0 *D3DKMT_PRESENT_MULTIPLANE_OVERLAY2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTPresentMultiPlaneOverlay2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTPresentMultiPlaneOverlay3 calls GDI32!D3DKMTPresentMultiPlaneOverlay3.
func D3DKMTPresentMultiPlaneOverlay3(param0 *D3DKMT_PRESENT_MULTIPLANE_OVERLAY3) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTPresentMultiPlaneOverlay3.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTPresentRedirected calls GDI32!D3DKMTPresentRedirected.
func D3DKMTPresentRedirected(param0 *D3DKMT_PRESENT_REDIRECTED) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTPresentRedirected.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryAdapterInfo calls GDI32!D3DKMTQueryAdapterInfo.
func D3DKMTQueryAdapterInfo(param0 *D3DKMT_QUERYADAPTERINFO) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryAdapterInfo.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryAllocationResidency calls GDI32!D3DKMTQueryAllocationResidency.
func D3DKMTQueryAllocationResidency(param0 *D3DKMT_QUERYALLOCATIONRESIDENCY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryAllocationResidency.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryClockCalibration calls GDI32!D3DKMTQueryClockCalibration.
func D3DKMTQueryClockCalibration(param0 *D3DKMT_QUERYCLOCKCALIBRATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryClockCalibration.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryFSEBlock calls GDI32!D3DKMTQueryFSEBlock.
func D3DKMTQueryFSEBlock(param0 *D3DKMT_QUERYFSEBLOCK) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryFSEBlock.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryProcessOfferInfo calls GDI32!D3DKMTQueryProcessOfferInfo.
func D3DKMTQueryProcessOfferInfo(param0 *D3DKMT_QUERYPROCESSOFFERINFO) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryProcessOfferInfo.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryProtectedSessionInfoFromNtHandle calls GDI32!D3DKMTQueryProtectedSessionInfoFromNtHandle.
func D3DKMTQueryProtectedSessionInfoFromNtHandle(param0 *D3DKMT_QUERYPROTECTEDSESSIONINFOFROMNTHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryProtectedSessionInfoFromNtHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryProtectedSessionStatus calls GDI32!D3DKMTQueryProtectedSessionStatus.
func D3DKMTQueryProtectedSessionStatus(param0 *D3DKMT_QUERYPROTECTEDSESSIONSTATUS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryProtectedSessionStatus.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName calls GDI32!D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName.
func D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName(param0 *D3DKMT_QUERYREMOTEVIDPNSOURCEFROMGDIDISPLAYNAME) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryRemoteVidPnSourceFromGdiDisplayName.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryResourceInfo calls GDI32!D3DKMTQueryResourceInfo.
func D3DKMTQueryResourceInfo(param0 *D3DKMT_QUERYRESOURCEINFO) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryResourceInfo.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryResourceInfoFromNtHandle calls GDI32!D3DKMTQueryResourceInfoFromNtHandle.
func D3DKMTQueryResourceInfoFromNtHandle(param0 *D3DKMT_QUERYRESOURCEINFOFROMNTHANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryResourceInfoFromNtHandle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryStatistics calls GDI32!D3DKMTQueryStatistics.
func D3DKMTQueryStatistics(param0 *D3DKMT_QUERYSTATISTICS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryStatistics.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryVidPnExclusiveOwnership calls GDI32!D3DKMTQueryVidPnExclusiveOwnership.
func D3DKMTQueryVidPnExclusiveOwnership(param0 *D3DKMT_QUERYVIDPNEXCLUSIVEOWNERSHIP) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryVidPnExclusiveOwnership.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTQueryVideoMemoryInfo calls GDI32!D3DKMTQueryVideoMemoryInfo.
func D3DKMTQueryVideoMemoryInfo(param0 *D3DKMT_QUERYVIDEOMEMORYINFO) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTQueryVideoMemoryInfo.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTReclaimAllocations calls GDI32!D3DKMTReclaimAllocations.
func D3DKMTReclaimAllocations(param0 *D3DKMT_RECLAIMALLOCATIONS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTReclaimAllocations.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTReclaimAllocations2 calls GDI32!D3DKMTReclaimAllocations2.
func D3DKMTReclaimAllocations2(param0 *D3DKMT_RECLAIMALLOCATIONS2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTReclaimAllocations2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTRegisterTrimNotification calls GDI32!D3DKMTRegisterTrimNotification.
func D3DKMTRegisterTrimNotification(param0 *D3DKMT_REGISTERTRIMNOTIFICATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTRegisterTrimNotification.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTRegisterVailProcess calls GDI32!D3DKMTRegisterVailProcess.
func D3DKMTRegisterVailProcess(param0 *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTRegisterVailProcess.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTReleaseKeyedMutex calls GDI32!D3DKMTReleaseKeyedMutex.
func D3DKMTReleaseKeyedMutex(param0 *D3DKMT_RELEASEKEYEDMUTEX) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTReleaseKeyedMutex.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTReleaseKeyedMutex2 calls GDI32!D3DKMTReleaseKeyedMutex2.
func D3DKMTReleaseKeyedMutex2(param0 *D3DKMT_RELEASEKEYEDMUTEX2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTReleaseKeyedMutex2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTReleaseProcessVidPnSourceOwners calls GDI32!D3DKMTReleaseProcessVidPnSourceOwners.
func D3DKMTReleaseProcessVidPnSourceOwners(param0 win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTReleaseProcessVidPnSourceOwners.Addr(), uintptr(param0))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTRender calls GDI32!D3DKMTRender.
func D3DKMTRender(param0 *D3DKMT_RENDER) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTRender.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTReserveGpuVirtualAddress calls GDI32!D3DKMTReserveGpuVirtualAddress.
func D3DKMTReserveGpuVirtualAddress(param0 *D3DDDI_RESERVEGPUVIRTUALADDRESS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTReserveGpuVirtualAddress.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetAllocationPriority calls GDI32!D3DKMTSetAllocationPriority.
func D3DKMTSetAllocationPriority(param0 *D3DKMT_SETALLOCATIONPRIORITY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetAllocationPriority.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetContextInProcessSchedulingPriority calls GDI32!D3DKMTSetContextInProcessSchedulingPriority.
func D3DKMTSetContextInProcessSchedulingPriority(param0 *D3DKMT_SETCONTEXTINPROCESSSCHEDULINGPRIORITY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetContextInProcessSchedulingPriority.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetContextSchedulingPriority calls GDI32!D3DKMTSetContextSchedulingPriority.
func D3DKMTSetContextSchedulingPriority(param0 *D3DKMT_SETCONTEXTSCHEDULINGPRIORITY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetContextSchedulingPriority.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetDisplayMode calls GDI32!D3DKMTSetDisplayMode.
func D3DKMTSetDisplayMode(param0 *D3DKMT_SETDISPLAYMODE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetDisplayMode.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetDisplayPrivateDriverFormat calls GDI32!D3DKMTSetDisplayPrivateDriverFormat.
func D3DKMTSetDisplayPrivateDriverFormat(param0 *D3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetDisplayPrivateDriverFormat.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetFSEBlock calls GDI32!D3DKMTSetFSEBlock.
func D3DKMTSetFSEBlock(param0 *D3DKMT_SETFSEBLOCK) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetFSEBlock.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetGammaRamp calls GDI32!D3DKMTSetGammaRamp.
func D3DKMTSetGammaRamp(param0 *D3DKMT_SETGAMMARAMP) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetGammaRamp.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetHwProtectionTeardownRecovery calls GDI32!D3DKMTSetHwProtectionTeardownRecovery.
func D3DKMTSetHwProtectionTeardownRecovery(param0 *D3DKMT_SETHWPROTECTIONTEARDOWNRECOVERY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetHwProtectionTeardownRecovery.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetMonitorColorSpaceTransform calls GDI32!D3DKMTSetMonitorColorSpaceTransform.
func D3DKMTSetMonitorColorSpaceTransform(param0 *D3DKMT_SET_COLORSPACE_TRANSFORM) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetMonitorColorSpaceTransform.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetProcessSchedulingPriorityClass calls GDI32!D3DKMTSetProcessSchedulingPriorityClass.
func D3DKMTSetProcessSchedulingPriorityClass(param0 win32foundation.HANDLE, param1 D3DKMT_SCHEDULINGPRIORITYCLASS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetProcessSchedulingPriorityClass.Addr(), uintptr(param0), uintptr(param1))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetQueuedLimit calls GDI32!D3DKMTSetQueuedLimit.
func D3DKMTSetQueuedLimit(param0 *D3DKMT_SETQUEUEDLIMIT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetQueuedLimit.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetStablePowerState calls GDI32!D3DKMTSetStablePowerState.
func D3DKMTSetStablePowerState(param0 *D3DKMT_SETSTABLEPOWERSTATE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetStablePowerState.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetSyncRefreshCountWaitTarget calls GDI32!D3DKMTSetSyncRefreshCountWaitTarget.
func D3DKMTSetSyncRefreshCountWaitTarget(param0 *D3DKMT_SETSYNCREFRESHCOUNTWAITTARGET) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetSyncRefreshCountWaitTarget.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetVidPnSourceHwProtection calls GDI32!D3DKMTSetVidPnSourceHwProtection.
func D3DKMTSetVidPnSourceHwProtection(param0 *D3DKMT_SETVIDPNSOURCEHWPROTECTION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetVidPnSourceHwProtection.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetVidPnSourceOwner calls GDI32!D3DKMTSetVidPnSourceOwner.
func D3DKMTSetVidPnSourceOwner(param0 *D3DKMT_SETVIDPNSOURCEOWNER) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetVidPnSourceOwner.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetVidPnSourceOwner1 calls GDI32!D3DKMTSetVidPnSourceOwner1.
func D3DKMTSetVidPnSourceOwner1(param0 *D3DKMT_SETVIDPNSOURCEOWNER1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetVidPnSourceOwner1.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSetVidPnSourceOwner2 calls GDI32!D3DKMTSetVidPnSourceOwner2.
func D3DKMTSetVidPnSourceOwner2(param0 *D3DKMT_SETVIDPNSOURCEOWNER2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSetVidPnSourceOwner2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTShareObjects calls GDI32!D3DKMTShareObjects.
func D3DKMTShareObjects(hObjects []uint32, pObjectAttributes *foundation.OBJECT_ATTRIBUTES, dwDesiredAccess uint32, phSharedNtHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	var _hObjects *uint32
	if len(hObjects) > 0 {
		_hObjects = &hObjects[0]
	}
	r1, _, _ := syscall.SyscallN(procD3DKMTShareObjects.Addr(), uintptr(len(hObjects)), uintptr(unsafe.Pointer(_hObjects)), uintptr(unsafe.Pointer(pObjectAttributes)), uintptr(dwDesiredAccess), uintptr(unsafe.Pointer(phSharedNtHandle)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSharedPrimaryLockNotification calls GDI32!D3DKMTSharedPrimaryLockNotification.
func D3DKMTSharedPrimaryLockNotification(param0 *D3DKMT_SHAREDPRIMARYLOCKNOTIFICATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSharedPrimaryLockNotification.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSharedPrimaryUnLockNotification calls GDI32!D3DKMTSharedPrimaryUnLockNotification.
func D3DKMTSharedPrimaryUnLockNotification(param0 *D3DKMT_SHAREDPRIMARYUNLOCKNOTIFICATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSharedPrimaryUnLockNotification.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSignalSynchronizationObject calls GDI32!D3DKMTSignalSynchronizationObject.
func D3DKMTSignalSynchronizationObject(param0 *D3DKMT_SIGNALSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSignalSynchronizationObject.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSignalSynchronizationObject2 calls GDI32!D3DKMTSignalSynchronizationObject2.
func D3DKMTSignalSynchronizationObject2(param0 *D3DKMT_SIGNALSYNCHRONIZATIONOBJECT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSignalSynchronizationObject2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSignalSynchronizationObjectFromCpu calls GDI32!D3DKMTSignalSynchronizationObjectFromCpu.
func D3DKMTSignalSynchronizationObjectFromCpu(param0 *D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSignalSynchronizationObjectFromCpu.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSignalSynchronizationObjectFromGpu calls GDI32!D3DKMTSignalSynchronizationObjectFromGpu.
func D3DKMTSignalSynchronizationObjectFromGpu(param0 *D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSignalSynchronizationObjectFromGpu.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSignalSynchronizationObjectFromGpu2 calls GDI32!D3DKMTSignalSynchronizationObjectFromGpu2.
func D3DKMTSignalSynchronizationObjectFromGpu2(param0 *D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSignalSynchronizationObjectFromGpu2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSubmitCommand calls GDI32!D3DKMTSubmitCommand.
func D3DKMTSubmitCommand(param0 *D3DKMT_SUBMITCOMMAND) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSubmitCommand.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSubmitCommandToHwQueue calls GDI32!D3DKMTSubmitCommandToHwQueue.
func D3DKMTSubmitCommandToHwQueue(param0 *D3DKMT_SUBMITCOMMANDTOHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSubmitCommandToHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSubmitPresentBltToHwQueue calls api-ms-win-dx-d3dkmt-l1-1-4!D3DKMTSubmitPresentBltToHwQueue.
func D3DKMTSubmitPresentBltToHwQueue(param0 *D3DKMT_SUBMITPRESENTBLTTOHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSubmitPresentBltToHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSubmitPresentToHwQueue calls api-ms-win-dx-d3dkmt-l1-1-4!D3DKMTSubmitPresentToHwQueue.
func D3DKMTSubmitPresentToHwQueue(param0 *D3DKMT_SUBMITPRESENTTOHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSubmitPresentToHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSubmitSignalSyncObjectsToHwQueue calls GDI32!D3DKMTSubmitSignalSyncObjectsToHwQueue.
func D3DKMTSubmitSignalSyncObjectsToHwQueue(param0 *D3DKMT_SUBMITSIGNALSYNCOBJECTSTOHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSubmitSignalSyncObjectsToHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTSubmitWaitForSyncObjectsToHwQueue calls GDI32!D3DKMTSubmitWaitForSyncObjectsToHwQueue.
func D3DKMTSubmitWaitForSyncObjectsToHwQueue(param0 *D3DKMT_SUBMITWAITFORSYNCOBJECTSTOHWQUEUE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTSubmitWaitForSyncObjectsToHwQueue.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTTrimProcessCommitment calls GDI32!D3DKMTTrimProcessCommitment.
func D3DKMTTrimProcessCommitment(param0 *D3DKMT_TRIMPROCESSCOMMITMENT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTTrimProcessCommitment.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTUnlock calls GDI32!D3DKMTUnlock.
func D3DKMTUnlock(param0 *D3DKMT_UNLOCK) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTUnlock.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTUnlock2 calls GDI32!D3DKMTUnlock2.
func D3DKMTUnlock2(param0 *D3DKMT_UNLOCK2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTUnlock2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTUnregisterTrimNotification calls GDI32!D3DKMTUnregisterTrimNotification.
func D3DKMTUnregisterTrimNotification(param0 *D3DKMT_UNREGISTERTRIMNOTIFICATION) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTUnregisterTrimNotification.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTUpdateAllocationProperty calls GDI32!D3DKMTUpdateAllocationProperty.
func D3DKMTUpdateAllocationProperty(param0 *D3DDDI_UPDATEALLOCPROPERTY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTUpdateAllocationProperty.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTUpdateGpuVirtualAddress calls GDI32!D3DKMTUpdateGpuVirtualAddress.
func D3DKMTUpdateGpuVirtualAddress(param0 *D3DKMT_UPDATEGPUVIRTUALADDRESS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTUpdateGpuVirtualAddress.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTUpdateOverlay calls GDI32!D3DKMTUpdateOverlay.
func D3DKMTUpdateOverlay(param0 *D3DKMT_UPDATEOVERLAY) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTUpdateOverlay.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForIdle calls GDI32!D3DKMTWaitForIdle.
func D3DKMTWaitForIdle(param0 *D3DKMT_WAITFORIDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForIdle.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForSynchronizationObject calls GDI32!D3DKMTWaitForSynchronizationObject.
func D3DKMTWaitForSynchronizationObject(param0 *D3DKMT_WAITFORSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForSynchronizationObject.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForSynchronizationObject2 calls GDI32!D3DKMTWaitForSynchronizationObject2.
func D3DKMTWaitForSynchronizationObject2(param0 *D3DKMT_WAITFORSYNCHRONIZATIONOBJECT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForSynchronizationObject2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForSynchronizationObjectFromCpu calls GDI32!D3DKMTWaitForSynchronizationObjectFromCpu.
func D3DKMTWaitForSynchronizationObjectFromCpu(param0 *D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForSynchronizationObjectFromCpu.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForSynchronizationObjectFromGpu calls GDI32!D3DKMTWaitForSynchronizationObjectFromGpu.
func D3DKMTWaitForSynchronizationObjectFromGpu(param0 *D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMGPU) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForSynchronizationObjectFromGpu.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForVerticalBlankEvent calls GDI32!D3DKMTWaitForVerticalBlankEvent.
func D3DKMTWaitForVerticalBlankEvent(param0 *D3DKMT_WAITFORVERTICALBLANKEVENT) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForVerticalBlankEvent.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}

// D3DKMTWaitForVerticalBlankEvent2 calls GDI32!D3DKMTWaitForVerticalBlankEvent2.
func D3DKMTWaitForVerticalBlankEvent2(param0 *D3DKMT_WAITFORVERTICALBLANKEVENT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procD3DKMTWaitForVerticalBlankEvent2.Addr(), uintptr(unsafe.Pointer(param0)))
	return win32foundation.NTSTATUS(r1)
}
