// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package direct3d

// LPD3DHAL_CLEAR2CB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_CLEAR2DATA) uint32.
type LPD3DHAL_CLEAR2CB uintptr

// LPD3DHAL_CLEARCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_CLEARDATA) uint32.
type LPD3DHAL_CLEARCB uintptr

// LPD3DHAL_CONTEXTCREATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_CONTEXTCREATEDATA) uint32.
type LPD3DHAL_CONTEXTCREATECB uintptr

// LPD3DHAL_CONTEXTDESTROYALLCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_CONTEXTDESTROYALLDATA) uint32.
type LPD3DHAL_CONTEXTDESTROYALLCB uintptr

// LPD3DHAL_CONTEXTDESTROYCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_CONTEXTDESTROYDATA) uint32.
type LPD3DHAL_CONTEXTDESTROYCB uintptr

// LPD3DHAL_DRAWONEINDEXEDPRIMITIVECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_DRAWONEINDEXEDPRIMITIVEDATA) uint32.
type LPD3DHAL_DRAWONEINDEXEDPRIMITIVECB uintptr

// LPD3DHAL_DRAWONEPRIMITIVECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_DRAWONEPRIMITIVEDATA) uint32.
type LPD3DHAL_DRAWONEPRIMITIVECB uintptr

// LPD3DHAL_DRAWPRIMITIVES2CB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_DRAWPRIMITIVES2DATA) uint32.
type LPD3DHAL_DRAWPRIMITIVES2CB uintptr

// LPD3DHAL_DRAWPRIMITIVESCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_DRAWPRIMITIVESDATA) uint32.
type LPD3DHAL_DRAWPRIMITIVESCB uintptr

// LPD3DHAL_GETSTATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_GETSTATEDATA) uint32.
type LPD3DHAL_GETSTATECB uintptr

// LPD3DHAL_RENDERPRIMITIVECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_RENDERPRIMITIVEDATA) uint32.
type LPD3DHAL_RENDERPRIMITIVECB uintptr

// LPD3DHAL_RENDERSTATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_RENDERSTATEDATA) uint32.
type LPD3DHAL_RENDERSTATECB uintptr

// LPD3DHAL_SCENECAPTURECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_SCENECAPTUREDATA) uint32.
type LPD3DHAL_SCENECAPTURECB uintptr

// LPD3DHAL_SETRENDERTARGETCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_SETRENDERTARGETDATA) uint32.
type LPD3DHAL_SETRENDERTARGETCB uintptr

// LPD3DHAL_TEXTURECREATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_TEXTURECREATEDATA) uint32.
type LPD3DHAL_TEXTURECREATECB uintptr

// LPD3DHAL_TEXTUREDESTROYCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_TEXTUREDESTROYDATA) uint32.
type LPD3DHAL_TEXTUREDESTROYCB uintptr

// LPD3DHAL_TEXTUREGETSURFCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_TEXTUREGETSURFDATA) uint32.
type LPD3DHAL_TEXTUREGETSURFCB uintptr

// LPD3DHAL_TEXTURESWAPCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_TEXTURESWAPDATA) uint32.
type LPD3DHAL_TEXTURESWAPCB uintptr

// LPD3DHAL_VALIDATETEXTURESTAGESTATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DHAL_VALIDATETEXTURESTAGESTATEDATA) uint32.
type LPD3DHAL_VALIDATETEXTURESTAGESTATECB uintptr

// LPD3DNTHAL_CLEAR2CB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_CLEAR2DATA) uint32.
type LPD3DNTHAL_CLEAR2CB uintptr

// LPD3DNTHAL_CONTEXTCREATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_CONTEXTCREATEDATA) uint32.
type LPD3DNTHAL_CONTEXTCREATECB uintptr

// LPD3DNTHAL_CONTEXTDESTROYALLCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_CONTEXTDESTROYALLDATA) uint32.
type LPD3DNTHAL_CONTEXTDESTROYALLCB uintptr

// LPD3DNTHAL_CONTEXTDESTROYCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_CONTEXTDESTROYDATA) uint32.
type LPD3DNTHAL_CONTEXTDESTROYCB uintptr

// LPD3DNTHAL_DRAWPRIMITIVES2CB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_DRAWPRIMITIVES2DATA) uint32.
type LPD3DNTHAL_DRAWPRIMITIVES2CB uintptr

// LPD3DNTHAL_SCENECAPTURECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_SCENECAPTUREDATA) uint32.
type LPD3DNTHAL_SCENECAPTURECB uintptr

// LPD3DNTHAL_SETRENDERTARGETCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_SETRENDERTARGETDATA) uint32.
type LPD3DNTHAL_SETRENDERTARGETCB uintptr

// LPD3DNTHAL_TEXTURECREATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_TEXTURECREATEDATA) uint32.
type LPD3DNTHAL_TEXTURECREATECB uintptr

// LPD3DNTHAL_TEXTUREDESTROYCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_TEXTUREDESTROYDATA) uint32.
type LPD3DNTHAL_TEXTUREDESTROYCB uintptr

// LPD3DNTHAL_TEXTUREGETSURFCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_TEXTUREGETSURFDATA) uint32.
type LPD3DNTHAL_TEXTUREGETSURFCB uintptr

// LPD3DNTHAL_TEXTURESWAPCB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_TEXTURESWAPDATA) uint32.
type LPD3DNTHAL_TEXTURESWAPCB uintptr

// LPD3DNTHAL_VALIDATETEXTURESTAGESTATECB is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DNTHAL_VALIDATETEXTURESTAGESTATEDATA) uint32.
type LPD3DNTHAL_VALIDATETEXTURESTAGESTATECB uintptr

// PDXGK_FSTATE_NOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, uint32, uint32, win32foundation.BOOLEAN, unsafe.Pointer).
type PDXGK_FSTATE_NOTIFICATION uintptr

// PDXGK_GRAPHICSPOWER_UNREGISTER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer) win32foundation.NTSTATUS.
type PDXGK_GRAPHICSPOWER_UNREGISTER uintptr

// PDXGK_INITIAL_COMPONENT_STATE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, uint32, win32foundation.BOOLEAN, uint32, win32.GUID, uint32).
type PDXGK_INITIAL_COMPONENT_STATE uintptr

// PDXGK_POWER_NOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, win32systempower.DEVICE_POWER_STATE, win32foundation.BOOLEAN, unsafe.Pointer).
type PDXGK_POWER_NOTIFICATION uintptr

// PDXGK_REMOVAL_NOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer).
type PDXGK_REMOVAL_NOTIFICATION uintptr

// PDXGK_SET_SHARED_POWER_COMPONENT_STATE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, uint32, win32foundation.BOOLEAN) win32foundation.NTSTATUS.
type PDXGK_SET_SHARED_POWER_COMPONENT_STATE uintptr

// PFND3DKMT_ACQUIREKEYEDMUTEX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ACQUIREKEYEDMUTEX) win32foundation.NTSTATUS.
type PFND3DKMT_ACQUIREKEYEDMUTEX uintptr

// PFND3DKMT_ACQUIREKEYEDMUTEX2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ACQUIREKEYEDMUTEX2) win32foundation.NTSTATUS.
type PFND3DKMT_ACQUIREKEYEDMUTEX2 uintptr

// PFND3DKMT_ADJUSTFULLSCREENGAMMA is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ADJUSTFULLSCREENGAMMA) win32foundation.NTSTATUS.
type PFND3DKMT_ADJUSTFULLSCREENGAMMA uintptr

// PFND3DKMT_BUDGETCHANGENOTIFICATIONCALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_BUDGETCHANGENOTIFICATION).
type PFND3DKMT_BUDGETCHANGENOTIFICATIONCALLBACK uintptr

// PFND3DKMT_CANCELPRESENTS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CANCEL_PRESENTS) win32foundation.NTSTATUS.
type PFND3DKMT_CANCELPRESENTS uintptr

// PFND3DKMT_CHANGESURFACEPOINTER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHANGESURFACEPOINTER) win32foundation.NTSTATUS.
type PFND3DKMT_CHANGESURFACEPOINTER uintptr

// PFND3DKMT_CHANGEVIDEOMEMORYRESERVATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHANGEVIDEOMEMORYRESERVATION) win32foundation.NTSTATUS.
type PFND3DKMT_CHANGEVIDEOMEMORYRESERVATION uintptr

// PFND3DKMT_CHECKEXCLUSIVEOWNERSHIP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.BOOLEAN.
type PFND3DKMT_CHECKEXCLUSIVEOWNERSHIP uintptr

// PFND3DKMT_CHECKMONITORPOWERSTATE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKMONITORPOWERSTATE) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKMONITORPOWERSTATE uintptr

// PFND3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT uintptr

// PFND3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT2) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT2 uintptr

// PFND3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT3 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT3) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKMULTIPLANEOVERLAYSUPPORT3 uintptr

// PFND3DKMT_CHECKOCCLUSION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKOCCLUSION) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKOCCLUSION uintptr

// PFND3DKMT_CHECKSHAREDRESOURCEACCESS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKSHAREDRESOURCEACCESS) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKSHAREDRESOURCEACCESS uintptr

// PFND3DKMT_CHECKVIDPNEXCLUSIVEOWNERSHIP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CHECKVIDPNEXCLUSIVEOWNERSHIP) win32foundation.NTSTATUS.
type PFND3DKMT_CHECKVIDPNEXCLUSIVEOWNERSHIP uintptr

// PFND3DKMT_CLOSEADAPTER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CLOSEADAPTER) win32foundation.NTSTATUS.
type PFND3DKMT_CLOSEADAPTER uintptr

// PFND3DKMT_CONFIGURESHAREDRESOURCE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CONFIGURESHAREDRESOURCE) win32foundation.NTSTATUS.
type PFND3DKMT_CONFIGURESHAREDRESOURCE uintptr

// PFND3DKMT_CONNECTDOORBELL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CONNECT_DOORBELL) win32foundation.NTSTATUS.
type PFND3DKMT_CONNECTDOORBELL uintptr

// PFND3DKMT_CREATEALLOCATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEALLOCATION) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEALLOCATION uintptr

// PFND3DKMT_CREATEALLOCATION2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEALLOCATION) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEALLOCATION2 uintptr

// PFND3DKMT_CREATECONTEXT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATECONTEXT) win32foundation.NTSTATUS.
type PFND3DKMT_CREATECONTEXT uintptr

// PFND3DKMT_CREATECONTEXTVIRTUAL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATECONTEXTVIRTUAL) win32foundation.NTSTATUS.
type PFND3DKMT_CREATECONTEXTVIRTUAL uintptr

// PFND3DKMT_CREATEDCFROMMEMORY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEDCFROMMEMORY) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEDCFROMMEMORY uintptr

// PFND3DKMT_CREATEDEVICE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEDEVICE) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEDEVICE uintptr

// PFND3DKMT_CREATEDOORBELL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATE_DOORBELL) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEDOORBELL uintptr

// PFND3DKMT_CREATEHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEHWQUEUE uintptr

// PFND3DKMT_CREATEKEYEDMUTEX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEKEYEDMUTEX) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEKEYEDMUTEX uintptr

// PFND3DKMT_CREATEKEYEDMUTEX2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEKEYEDMUTEX2) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEKEYEDMUTEX2 uintptr

// PFND3DKMT_CREATENATIVEFENCE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATENATIVEFENCE) win32foundation.NTSTATUS.
type PFND3DKMT_CREATENATIVEFENCE uintptr

// PFND3DKMT_CREATEOUTPUTDUPL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATE_OUTPUTDUPL) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEOUTPUTDUPL uintptr

// PFND3DKMT_CREATEOVERLAY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEOVERLAY) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEOVERLAY uintptr

// PFND3DKMT_CREATEPAGINGQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEPAGINGQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEPAGINGQUEUE uintptr

// PFND3DKMT_CREATEPROTECTEDSESSION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATEPROTECTEDSESSION) win32foundation.NTSTATUS.
type PFND3DKMT_CREATEPROTECTEDSESSION uintptr

// PFND3DKMT_CREATESYNCHRONIZATIONOBJECT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATESYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS.
type PFND3DKMT_CREATESYNCHRONIZATIONOBJECT uintptr

// PFND3DKMT_CREATESYNCHRONIZATIONOBJECT2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_CREATESYNCHRONIZATIONOBJECT2) win32foundation.NTSTATUS.
type PFND3DKMT_CREATESYNCHRONIZATIONOBJECT2 uintptr

// PFND3DKMT_DESTROYALLOCATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYALLOCATION) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYALLOCATION uintptr

// PFND3DKMT_DESTROYALLOCATION2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYALLOCATION2) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYALLOCATION2 uintptr

// PFND3DKMT_DESTROYCONTEXT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYCONTEXT) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYCONTEXT uintptr

// PFND3DKMT_DESTROYDCFROMMEMORY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYDCFROMMEMORY) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYDCFROMMEMORY uintptr

// PFND3DKMT_DESTROYDEVICE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYDEVICE) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYDEVICE uintptr

// PFND3DKMT_DESTROYDOORBELL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROY_DOORBELL) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYDOORBELL uintptr

// PFND3DKMT_DESTROYHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYHWQUEUE uintptr

// PFND3DKMT_DESTROYKEYEDMUTEX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYKEYEDMUTEX) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYKEYEDMUTEX uintptr

// PFND3DKMT_DESTROYOUTPUTDUPL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROY_OUTPUTDUPL) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYOUTPUTDUPL uintptr

// PFND3DKMT_DESTROYOVERLAY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYOVERLAY) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYOVERLAY uintptr

// PFND3DKMT_DESTROYPAGINGQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DDDI_DESTROYPAGINGQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYPAGINGQUEUE uintptr

// PFND3DKMT_DESTROYPROTECTEDSESSION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYPROTECTEDSESSION) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYPROTECTEDSESSION uintptr

// PFND3DKMT_DESTROYSYNCHRONIZATIONOBJECT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_DESTROYSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS.
type PFND3DKMT_DESTROYSYNCHRONIZATIONOBJECT uintptr

// PFND3DKMT_ENUMADAPTERS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ENUMADAPTERS) win32foundation.NTSTATUS.
type PFND3DKMT_ENUMADAPTERS uintptr

// PFND3DKMT_ENUMADAPTERS2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ENUMADAPTERS2) win32foundation.NTSTATUS.
type PFND3DKMT_ENUMADAPTERS2 uintptr

// PFND3DKMT_ENUMADAPTERS3 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ENUMADAPTERS3) win32foundation.NTSTATUS.
type PFND3DKMT_ENUMADAPTERS3 uintptr

// PFND3DKMT_ESCAPE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_ESCAPE) win32foundation.NTSTATUS.
type PFND3DKMT_ESCAPE uintptr

// PFND3DKMT_EVICT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_EVICT) win32foundation.NTSTATUS.
type PFND3DKMT_EVICT uintptr

// PFND3DKMT_FLIPOVERLAY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_FLIPOVERLAY) win32foundation.NTSTATUS.
type PFND3DKMT_FLIPOVERLAY uintptr

// PFND3DKMT_FLUSHHEAPTRANSITIONS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_FLUSHHEAPTRANSITIONS) win32foundation.NTSTATUS.
type PFND3DKMT_FLUSHHEAPTRANSITIONS uintptr

// PFND3DKMT_FREEGPUVIRTUALADDRESS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_FREEGPUVIRTUALADDRESS) win32foundation.NTSTATUS.
type PFND3DKMT_FREEGPUVIRTUALADDRESS uintptr

// PFND3DKMT_GETALLOCATIONPRIORITY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETALLOCATIONPRIORITY) win32foundation.NTSTATUS.
type PFND3DKMT_GETALLOCATIONPRIORITY uintptr

// PFND3DKMT_GETCONTEXTINPROCESSSCHEDULINGPRIORITY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETCONTEXTINPROCESSSCHEDULINGPRIORITY) win32foundation.NTSTATUS.
type PFND3DKMT_GETCONTEXTINPROCESSSCHEDULINGPRIORITY uintptr

// PFND3DKMT_GETCONTEXTSCHEDULINGPRIORITY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETCONTEXTSCHEDULINGPRIORITY) win32foundation.NTSTATUS.
type PFND3DKMT_GETCONTEXTSCHEDULINGPRIORITY uintptr

// PFND3DKMT_GETDEVICESTATE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETDEVICESTATE) win32foundation.NTSTATUS.
type PFND3DKMT_GETDEVICESTATE uintptr

// PFND3DKMT_GETDISPLAYMODELIST is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETDISPLAYMODELIST) win32foundation.NTSTATUS.
type PFND3DKMT_GETDISPLAYMODELIST uintptr

// PFND3DKMT_GETDWMVERTICALBLANKEVENT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETVERTICALBLANKEVENT) win32foundation.NTSTATUS.
type PFND3DKMT_GETDWMVERTICALBLANKEVENT uintptr

// PFND3DKMT_GETMULTIPLANEOVERLAYCAPS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GET_MULTIPLANE_OVERLAY_CAPS) win32foundation.NTSTATUS.
type PFND3DKMT_GETMULTIPLANEOVERLAYCAPS uintptr

// PFND3DKMT_GETMULTISAMPLEMETHODLIST is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETMULTISAMPLEMETHODLIST) win32foundation.NTSTATUS.
type PFND3DKMT_GETMULTISAMPLEMETHODLIST uintptr

// PFND3DKMT_GETOVERLAYSTATE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETOVERLAYSTATE) win32foundation.NTSTATUS.
type PFND3DKMT_GETOVERLAYSTATE uintptr

// PFND3DKMT_GETPOSTCOMPOSITIONCAPS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GET_POST_COMPOSITION_CAPS) win32foundation.NTSTATUS.
type PFND3DKMT_GETPOSTCOMPOSITIONCAPS uintptr

// PFND3DKMT_GETPRESENTHISTORY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETPRESENTHISTORY) win32foundation.NTSTATUS.
type PFND3DKMT_GETPRESENTHISTORY uintptr

// PFND3DKMT_GETPROCESSDEVICEREMOVALSUPPORT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETPROCESSDEVICEREMOVALSUPPORT) win32foundation.NTSTATUS.
type PFND3DKMT_GETPROCESSDEVICEREMOVALSUPPORT uintptr

// PFND3DKMT_GETPROCESSSCHEDULINGPRIORITYCLASS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.HANDLE, *D3DKMT_SCHEDULINGPRIORITYCLASS) win32foundation.NTSTATUS.
type PFND3DKMT_GETPROCESSSCHEDULINGPRIORITYCLASS uintptr

// PFND3DKMT_GETRESOURCEPRESENTPRIVATEDRIVERDATA is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DDDI_GETRESOURCEPRESENTPRIVATEDRIVERDATA) win32foundation.NTSTATUS.
type PFND3DKMT_GETRESOURCEPRESENTPRIVATEDRIVERDATA uintptr

// PFND3DKMT_GETRUNTIMEDATA is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETRUNTIMEDATA) win32foundation.NTSTATUS.
type PFND3DKMT_GETRUNTIMEDATA uintptr

// PFND3DKMT_GETSCANLINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETSCANLINE) win32foundation.NTSTATUS.
type PFND3DKMT_GETSCANLINE uintptr

// PFND3DKMT_GETSHAREDPRIMARYHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETSHAREDPRIMARYHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_GETSHAREDPRIMARYHANDLE uintptr

// PFND3DKMT_GETSHAREDRESOURCEADAPTERLUID is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_GETSHAREDRESOURCEADAPTERLUID) win32foundation.NTSTATUS.
type PFND3DKMT_GETSHAREDRESOURCEADAPTERLUID uintptr

// PFND3DKMT_INVALIDATEACTIVEVIDPN is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_INVALIDATEACTIVEVIDPN) win32foundation.NTSTATUS.
type PFND3DKMT_INVALIDATEACTIVEVIDPN uintptr

// PFND3DKMT_INVALIDATECACHE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_INVALIDATECACHE) win32foundation.NTSTATUS.
type PFND3DKMT_INVALIDATECACHE uintptr

// PFND3DKMT_LOCK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_LOCK) win32foundation.NTSTATUS.
type PFND3DKMT_LOCK uintptr

// PFND3DKMT_LOCK2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_LOCK2) win32foundation.NTSTATUS.
type PFND3DKMT_LOCK2 uintptr

// PFND3DKMT_MAKERESIDENT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DDDI_MAKERESIDENT) win32foundation.NTSTATUS.
type PFND3DKMT_MAKERESIDENT uintptr

// PFND3DKMT_MAPGPUVIRTUALADDRESS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DDDI_MAPGPUVIRTUALADDRESS) win32foundation.NTSTATUS.
type PFND3DKMT_MAPGPUVIRTUALADDRESS uintptr

// PFND3DKMT_MARKDEVICEASERROR is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_MARKDEVICEASERROR) win32foundation.NTSTATUS.
type PFND3DKMT_MARKDEVICEASERROR uintptr

// PFND3DKMT_NOTIFYWORKSUBMISSION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_NOTIFY_WORK_SUBMISSION) win32foundation.NTSTATUS.
type PFND3DKMT_NOTIFYWORKSUBMISSION uintptr

// PFND3DKMT_OFFERALLOCATIONS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OFFERALLOCATIONS) win32foundation.NTSTATUS.
type PFND3DKMT_OFFERALLOCATIONS uintptr

// PFND3DKMT_OPENADAPTERFROMDEVICENAME is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENADAPTERFROMDEVICENAME) win32foundation.NTSTATUS.
type PFND3DKMT_OPENADAPTERFROMDEVICENAME uintptr

// PFND3DKMT_OPENADAPTERFROMGDIDISPLAYNAME is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME) win32foundation.NTSTATUS.
type PFND3DKMT_OPENADAPTERFROMGDIDISPLAYNAME uintptr

// PFND3DKMT_OPENADAPTERFROMHDC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENADAPTERFROMHDC) win32foundation.NTSTATUS.
type PFND3DKMT_OPENADAPTERFROMHDC uintptr

// PFND3DKMT_OPENADAPTERFROMLUID is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENADAPTERFROMLUID) win32foundation.NTSTATUS.
type PFND3DKMT_OPENADAPTERFROMLUID uintptr

// PFND3DKMT_OPENKEYEDMUTEX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENKEYEDMUTEX) win32foundation.NTSTATUS.
type PFND3DKMT_OPENKEYEDMUTEX uintptr

// PFND3DKMT_OPENKEYEDMUTEX2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENKEYEDMUTEX2) win32foundation.NTSTATUS.
type PFND3DKMT_OPENKEYEDMUTEX2 uintptr

// PFND3DKMT_OPENKEYEDMUTEXFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENKEYEDMUTEXFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENKEYEDMUTEXFROMNTHANDLE uintptr

// PFND3DKMT_OPENNATIVEFENCEFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENNATIVEFENCEFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENNATIVEFENCEFROMNTHANDLE uintptr

// PFND3DKMT_OPENNTHANDLEFROMNAME is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENNTHANDLEFROMNAME) win32foundation.NTSTATUS.
type PFND3DKMT_OPENNTHANDLEFROMNAME uintptr

// PFND3DKMT_OPENPROTECTEDSESSIONFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENPROTECTEDSESSIONFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENPROTECTEDSESSIONFROMNTHANDLE uintptr

// PFND3DKMT_OPENRESOURCE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENRESOURCE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENRESOURCE uintptr

// PFND3DKMT_OPENRESOURCE2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENRESOURCE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENRESOURCE2 uintptr

// PFND3DKMT_OPENRESOURCEFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENRESOURCEFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENRESOURCEFROMNTHANDLE uintptr

// PFND3DKMT_OPENSYNCHRONIZATIONOBJECT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS.
type PFND3DKMT_OPENSYNCHRONIZATIONOBJECT uintptr

// PFND3DKMT_OPENSYNCOBJECTFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENSYNCOBJECTFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_OPENSYNCOBJECTFROMNTHANDLE uintptr

// PFND3DKMT_OPENSYNCOBJECTFROMNTHANDLE2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENSYNCOBJECTFROMNTHANDLE2) win32foundation.NTSTATUS.
type PFND3DKMT_OPENSYNCOBJECTFROMNTHANDLE2 uintptr

// PFND3DKMT_OPENSYNCOBJECTNTHANDLEFROMNAME is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OPENSYNCOBJECTNTHANDLEFROMNAME) win32foundation.NTSTATUS.
type PFND3DKMT_OPENSYNCOBJECTNTHANDLEFROMNAME uintptr

// PFND3DKMT_OUTPUTDUPLGETFRAMEINFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OUTPUTDUPL_GET_FRAMEINFO) win32foundation.NTSTATUS.
type PFND3DKMT_OUTPUTDUPLGETFRAMEINFO uintptr

// PFND3DKMT_OUTPUTDUPLGETMETADATA is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OUTPUTDUPL_METADATA) win32foundation.NTSTATUS.
type PFND3DKMT_OUTPUTDUPLGETMETADATA uintptr

// PFND3DKMT_OUTPUTDUPLGETPOINTERSHAPEDATA is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OUTPUTDUPL_GET_POINTER_SHAPE_DATA) win32foundation.NTSTATUS.
type PFND3DKMT_OUTPUTDUPLGETPOINTERSHAPEDATA uintptr

// PFND3DKMT_OUTPUTDUPLPRESENT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OUTPUTDUPLPRESENT) win32foundation.NTSTATUS.
type PFND3DKMT_OUTPUTDUPLPRESENT uintptr

// PFND3DKMT_OUTPUTDUPLPRESENTTOHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OUTPUTDUPLPRESENTTOHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_OUTPUTDUPLPRESENTTOHWQUEUE uintptr

// PFND3DKMT_OUTPUTDUPLRELEASEFRAME is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_OUTPUTDUPL_RELEASE_FRAME) win32foundation.NTSTATUS.
type PFND3DKMT_OUTPUTDUPLRELEASEFRAME uintptr

// PFND3DKMT_PINDIRECTFLIPRESOURCES is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_PINDIRECTFLIPRESOURCES) win32foundation.NTSTATUS.
type PFND3DKMT_PINDIRECTFLIPRESOURCES uintptr

// PFND3DKMT_POLLDISPLAYCHILDREN is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_POLLDISPLAYCHILDREN) win32foundation.NTSTATUS.
type PFND3DKMT_POLLDISPLAYCHILDREN uintptr

// PFND3DKMT_PRESENT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_PRESENT) win32foundation.NTSTATUS.
type PFND3DKMT_PRESENT uintptr

// PFND3DKMT_PRESENTMULTIPLANEOVERLAY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_PRESENT_MULTIPLANE_OVERLAY) win32foundation.NTSTATUS.
type PFND3DKMT_PRESENTMULTIPLANEOVERLAY uintptr

// PFND3DKMT_PRESENTMULTIPLANEOVERLAY2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_PRESENT_MULTIPLANE_OVERLAY2) win32foundation.NTSTATUS.
type PFND3DKMT_PRESENTMULTIPLANEOVERLAY2 uintptr

// PFND3DKMT_PRESENTMULTIPLANEOVERLAY3 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_PRESENT_MULTIPLANE_OVERLAY3) win32foundation.NTSTATUS.
type PFND3DKMT_PRESENTMULTIPLANEOVERLAY3 uintptr

// PFND3DKMT_QUERYADAPTERINFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYADAPTERINFO) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYADAPTERINFO uintptr

// PFND3DKMT_QUERYALLOCATIONRESIDENCY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYALLOCATIONRESIDENCY) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYALLOCATIONRESIDENCY uintptr

// PFND3DKMT_QUERYCLOCKCALIBRATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYCLOCKCALIBRATION) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYCLOCKCALIBRATION uintptr

// PFND3DKMT_QUERYFSEBLOCK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYFSEBLOCK) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYFSEBLOCK uintptr

// PFND3DKMT_QUERYHYBRIDLISTVALUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_HYBRID_LIST) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYHYBRIDLISTVALUE uintptr

// PFND3DKMT_QUERYPROCESSOFFERINFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYPROCESSOFFERINFO) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYPROCESSOFFERINFO uintptr

// PFND3DKMT_QUERYPROTECTEDSESSIONINFOFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYPROTECTEDSESSIONINFOFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYPROTECTEDSESSIONINFOFROMNTHANDLE uintptr

// PFND3DKMT_QUERYPROTECTEDSESSIONSTATUS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYPROTECTEDSESSIONSTATUS) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYPROTECTEDSESSIONSTATUS uintptr

// PFND3DKMT_QUERYREMOTEVIDPNSOURCEFROMGDIDISPLAYNAME is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYREMOTEVIDPNSOURCEFROMGDIDISPLAYNAME) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYREMOTEVIDPNSOURCEFROMGDIDISPLAYNAME uintptr

// PFND3DKMT_QUERYRESOURCEINFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYRESOURCEINFO) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYRESOURCEINFO uintptr

// PFND3DKMT_QUERYRESOURCEINFOFROMNTHANDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYRESOURCEINFOFROMNTHANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYRESOURCEINFOFROMNTHANDLE uintptr

// PFND3DKMT_QUERYSTATISTICS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYSTATISTICS) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYSTATISTICS uintptr

// PFND3DKMT_QUERYVIDEOMEMORYINFO is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYVIDEOMEMORYINFO) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYVIDEOMEMORYINFO uintptr

// PFND3DKMT_QUERYVIDPNEXCLUSIVEOWNERSHIP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_QUERYVIDPNEXCLUSIVEOWNERSHIP) win32foundation.NTSTATUS.
type PFND3DKMT_QUERYVIDPNEXCLUSIVEOWNERSHIP uintptr

// PFND3DKMT_RECLAIMALLOCATIONS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_RECLAIMALLOCATIONS) win32foundation.NTSTATUS.
type PFND3DKMT_RECLAIMALLOCATIONS uintptr

// PFND3DKMT_RECLAIMALLOCATIONS2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_RECLAIMALLOCATIONS2) win32foundation.NTSTATUS.
type PFND3DKMT_RECLAIMALLOCATIONS2 uintptr

// PFND3DKMT_REGISTERBUDGETCHANGENOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_REGISTERBUDGETCHANGENOTIFICATION) win32foundation.NTSTATUS.
type PFND3DKMT_REGISTERBUDGETCHANGENOTIFICATION uintptr

// PFND3DKMT_REGISTERTRIMNOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_REGISTERTRIMNOTIFICATION) win32foundation.NTSTATUS.
type PFND3DKMT_REGISTERTRIMNOTIFICATION uintptr

// PFND3DKMT_RELEASEKEYEDMUTEX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_RELEASEKEYEDMUTEX) win32foundation.NTSTATUS.
type PFND3DKMT_RELEASEKEYEDMUTEX uintptr

// PFND3DKMT_RELEASEKEYEDMUTEX2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_RELEASEKEYEDMUTEX2) win32foundation.NTSTATUS.
type PFND3DKMT_RELEASEKEYEDMUTEX2 uintptr

// PFND3DKMT_RELEASEPROCESSVIDPNSOURCEOWNERS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.HANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_RELEASEPROCESSVIDPNSOURCEOWNERS uintptr

// PFND3DKMT_RENDER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_RENDER) win32foundation.NTSTATUS.
type PFND3DKMT_RENDER uintptr

// PFND3DKMT_RESERVEGPUVIRTUALADDRESS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DDDI_RESERVEGPUVIRTUALADDRESS) win32foundation.NTSTATUS.
type PFND3DKMT_RESERVEGPUVIRTUALADDRESS uintptr

// PFND3DKMT_SETALLOCATIONPRIORITY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETALLOCATIONPRIORITY) win32foundation.NTSTATUS.
type PFND3DKMT_SETALLOCATIONPRIORITY uintptr

// PFND3DKMT_SETCONTEXTINPROCESSSCHEDULINGPRIORITY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETCONTEXTINPROCESSSCHEDULINGPRIORITY) win32foundation.NTSTATUS.
type PFND3DKMT_SETCONTEXTINPROCESSSCHEDULINGPRIORITY uintptr

// PFND3DKMT_SETCONTEXTSCHEDULINGPRIORITY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETCONTEXTSCHEDULINGPRIORITY) win32foundation.NTSTATUS.
type PFND3DKMT_SETCONTEXTSCHEDULINGPRIORITY uintptr

// PFND3DKMT_SETDISPLAYMODE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETDISPLAYMODE) win32foundation.NTSTATUS.
type PFND3DKMT_SETDISPLAYMODE uintptr

// PFND3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT) win32foundation.NTSTATUS.
type PFND3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT uintptr

// PFND3DKMT_SETFSEBLOCK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETFSEBLOCK) win32foundation.NTSTATUS.
type PFND3DKMT_SETFSEBLOCK uintptr

// PFND3DKMT_SETGAMMARAMP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETGAMMARAMP) win32foundation.NTSTATUS.
type PFND3DKMT_SETGAMMARAMP uintptr

// PFND3DKMT_SETHWPROTECTIONTEARDOWNRECOVERY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETHWPROTECTIONTEARDOWNRECOVERY) win32foundation.NTSTATUS.
type PFND3DKMT_SETHWPROTECTIONTEARDOWNRECOVERY uintptr

// PFND3DKMT_SETHYBRIDLISTVVALUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_HYBRID_LIST) win32foundation.NTSTATUS.
type PFND3DKMT_SETHYBRIDLISTVVALUE uintptr

// PFND3DKMT_SETPROCESSSCHEDULINGPRIORITYCLASS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.HANDLE, D3DKMT_SCHEDULINGPRIORITYCLASS) win32foundation.NTSTATUS.
type PFND3DKMT_SETPROCESSSCHEDULINGPRIORITYCLASS uintptr

// PFND3DKMT_SETQUEUEDLIMIT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETQUEUEDLIMIT) win32foundation.NTSTATUS.
type PFND3DKMT_SETQUEUEDLIMIT uintptr

// PFND3DKMT_SETSTABLEPOWERSTATE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETSTABLEPOWERSTATE) win32foundation.NTSTATUS.
type PFND3DKMT_SETSTABLEPOWERSTATE uintptr

// PFND3DKMT_SETSTEREOENABLED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.BOOL) win32foundation.NTSTATUS.
type PFND3DKMT_SETSTEREOENABLED uintptr

// PFND3DKMT_SETSYNCREFRESHCOUNTWAITTARGET is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETSYNCREFRESHCOUNTWAITTARGET) win32foundation.NTSTATUS.
type PFND3DKMT_SETSYNCREFRESHCOUNTWAITTARGET uintptr

// PFND3DKMT_SETVIDPNSOURCEHWPROTECTION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETVIDPNSOURCEHWPROTECTION) win32foundation.NTSTATUS.
type PFND3DKMT_SETVIDPNSOURCEHWPROTECTION uintptr

// PFND3DKMT_SETVIDPNSOURCEOWNER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETVIDPNSOURCEOWNER) win32foundation.NTSTATUS.
type PFND3DKMT_SETVIDPNSOURCEOWNER uintptr

// PFND3DKMT_SETVIDPNSOURCEOWNER1 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETVIDPNSOURCEOWNER1) win32foundation.NTSTATUS.
type PFND3DKMT_SETVIDPNSOURCEOWNER1 uintptr

// PFND3DKMT_SETVIDPNSOURCEOWNER2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SETVIDPNSOURCEOWNER2) win32foundation.NTSTATUS.
type PFND3DKMT_SETVIDPNSOURCEOWNER2 uintptr

// PFND3DKMT_SHAREDPRIMARYLOCKNOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SHAREDPRIMARYLOCKNOTIFICATION) win32foundation.NTSTATUS.
type PFND3DKMT_SHAREDPRIMARYLOCKNOTIFICATION uintptr

// PFND3DKMT_SHAREDPRIMARYUNLOCKNOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SHAREDPRIMARYUNLOCKNOTIFICATION) win32foundation.NTSTATUS.
type PFND3DKMT_SHAREDPRIMARYUNLOCKNOTIFICATION uintptr

// PFND3DKMT_SHAREOBJECTS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uint32, *uint32, *foundation.OBJECT_ATTRIBUTES, uint32, *win32foundation.HANDLE) win32foundation.NTSTATUS.
type PFND3DKMT_SHAREOBJECTS uintptr

// PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SIGNALSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS.
type PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECT uintptr

// PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECT2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SIGNALSYNCHRONIZATIONOBJECT2) win32foundation.NTSTATUS.
type PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECT2 uintptr

// PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU) win32foundation.NTSTATUS.
type PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMCPU uintptr

// PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU) win32foundation.NTSTATUS.
type PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU uintptr

// PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2) win32foundation.NTSTATUS.
type PFND3DKMT_SIGNALSYNCHRONIZATIONOBJECTFROMGPU2 uintptr

// PFND3DKMT_SUBMITCOMMAND is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SUBMITCOMMAND) win32foundation.NTSTATUS.
type PFND3DKMT_SUBMITCOMMAND uintptr

// PFND3DKMT_SUBMITCOMMANDTOHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SUBMITCOMMANDTOHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_SUBMITCOMMANDTOHWQUEUE uintptr

// PFND3DKMT_SUBMITPRESENTBLTTOHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SUBMITPRESENTBLTTOHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_SUBMITPRESENTBLTTOHWQUEUE uintptr

// PFND3DKMT_SUBMITPRESENTTOHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SUBMITPRESENTTOHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_SUBMITPRESENTTOHWQUEUE uintptr

// PFND3DKMT_SUBMITSIGNALSYNCOBJECTSTOHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SUBMITSIGNALSYNCOBJECTSTOHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_SUBMITSIGNALSYNCOBJECTSTOHWQUEUE uintptr

// PFND3DKMT_SUBMITWAITFORSYNCOBJECTSTOHWQUEUE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_SUBMITWAITFORSYNCOBJECTSTOHWQUEUE) win32foundation.NTSTATUS.
type PFND3DKMT_SUBMITWAITFORSYNCOBJECTSTOHWQUEUE uintptr

// PFND3DKMT_TRIMNOTIFICATIONCALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_TRIMNOTIFICATION).
type PFND3DKMT_TRIMNOTIFICATIONCALLBACK uintptr

// PFND3DKMT_TRIMPROCESSCOMMITMENT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_TRIMPROCESSCOMMITMENT) win32foundation.NTSTATUS.
type PFND3DKMT_TRIMPROCESSCOMMITMENT uintptr

// PFND3DKMT_UNLOCK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UNLOCK) win32foundation.NTSTATUS.
type PFND3DKMT_UNLOCK uintptr

// PFND3DKMT_UNLOCK2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UNLOCK2) win32foundation.NTSTATUS.
type PFND3DKMT_UNLOCK2 uintptr

// PFND3DKMT_UNPINDIRECTFLIPRESOURCES is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UNPINDIRECTFLIPRESOURCES) win32foundation.NTSTATUS.
type PFND3DKMT_UNPINDIRECTFLIPRESOURCES uintptr

// PFND3DKMT_UNREGISTERBUDGETCHANGENOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UNREGISTERBUDGETCHANGENOTIFICATION) win32foundation.NTSTATUS.
type PFND3DKMT_UNREGISTERBUDGETCHANGENOTIFICATION uintptr

// PFND3DKMT_UNREGISTERTRIMNOTIFICATION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UNREGISTERTRIMNOTIFICATION) win32foundation.NTSTATUS.
type PFND3DKMT_UNREGISTERTRIMNOTIFICATION uintptr

// PFND3DKMT_UPDATEALLOCATIONPROPERTY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DDDI_UPDATEALLOCPROPERTY) win32foundation.NTSTATUS.
type PFND3DKMT_UPDATEALLOCATIONPROPERTY uintptr

// PFND3DKMT_UPDATEGPUVIRTUALADDRESS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UPDATEGPUVIRTUALADDRESS) win32foundation.NTSTATUS.
type PFND3DKMT_UPDATEGPUVIRTUALADDRESS uintptr

// PFND3DKMT_UPDATEOVERLAY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_UPDATEOVERLAY) win32foundation.NTSTATUS.
type PFND3DKMT_UPDATEOVERLAY uintptr

// PFND3DKMT_WAITFORIDLE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORIDLE) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORIDLE uintptr

// PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORSYNCHRONIZATIONOBJECT) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECT uintptr

// PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECT2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORSYNCHRONIZATIONOBJECT2) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECT2 uintptr

// PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMCPU uintptr

// PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMGPU is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMGPU) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORSYNCHRONIZATIONOBJECTFROMGPU uintptr

// PFND3DKMT_WAITFORVERTICALBLANKEVENT is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORVERTICALBLANKEVENT) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORVERTICALBLANKEVENT uintptr

// PFND3DKMT_WAITFORVERTICALBLANKEVENT2 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*D3DKMT_WAITFORVERTICALBLANKEVENT2) win32foundation.NTSTATUS.
type PFND3DKMT_WAITFORVERTICALBLANKEVENT2 uintptr

// PFND3DNTPARSEUNKNOWNCOMMAND is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *unsafe.Pointer) win32foundation.HRESULT.
type PFND3DNTPARSEUNKNOWNCOMMAND uintptr

// PFND3DPARSEUNKNOWNCOMMAND is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *unsafe.Pointer) win32foundation.HRESULT.
type PFND3DPARSEUNKNOWNCOMMAND uintptr
