// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package io

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32systemio "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/io"
)

var (
	modntdll = win32.NewDLL("ntdll.dll")
)

var (
	procNtDeviceIoControlFile = modntdll.NewProc("NtDeviceIoControlFile")
)

// NtDeviceIoControlFile calls ntdll!NtDeviceIoControlFile.
func NtDeviceIoControlFile(FileHandle win32foundation.HANDLE, Event win32foundation.HANDLE, ApcRoutine win32systemio.PIO_APC_ROUTINE, ApcContext unsafe.Pointer, IoStatusBlock *win32systemio.IO_STATUS_BLOCK, IoControlCode uint32, InputBuffer []byte, OutputBuffer []byte) win32foundation.NTSTATUS {
	var _InputBuffer *byte
	if len(InputBuffer) > 0 {
		_InputBuffer = &InputBuffer[0]
	}
	var _OutputBuffer *byte
	if len(OutputBuffer) > 0 {
		_OutputBuffer = &OutputBuffer[0]
	}
	r1, _, _ := syscall.SyscallN(procNtDeviceIoControlFile.Addr(), uintptr(FileHandle), uintptr(Event), uintptr(ApcRoutine), uintptr(unsafe.Pointer(ApcContext)), uintptr(unsafe.Pointer(IoStatusBlock)), uintptr(IoControlCode), uintptr(unsafe.Pointer(_InputBuffer)), uintptr(len(InputBuffer)), uintptr(unsafe.Pointer(_OutputBuffer)), uintptr(len(OutputBuffer)))
	return win32foundation.NTSTATUS(r1)
}
