// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package ndis

// CL_ADD_PARTY_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_ADD_PARTY_COMPLETE_HANDLER uintptr

// CL_CALL_CONNECTED_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_CALL_CONNECTED_HANDLER uintptr

// CL_CLOSE_AF_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_CLOSE_AF_COMPLETE_HANDLER uintptr

// CL_CLOSE_CALL_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_CLOSE_CALL_COMPLETE_HANDLER uintptr

// CL_DEREG_SAP_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_DEREG_SAP_COMPLETE_HANDLER uintptr

// CL_DROP_PARTY_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_DROP_PARTY_COMPLETE_HANDLER uintptr

// CL_INCOMING_CALL_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CL_INCOMING_CALL_HANDLER uintptr

// CL_INCOMING_CALL_QOS_CHANGE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_INCOMING_CALL_QOS_CHANGE_HANDLER uintptr

// CL_INCOMING_CLOSE_CALL_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_INCOMING_CLOSE_CALL_HANDLER uintptr

// CL_INCOMING_DROP_PARTY_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_INCOMING_DROP_PARTY_HANDLER uintptr

// CL_MAKE_CALL_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_MAKE_CALL_COMPLETE_HANDLER uintptr

// CL_MODIFY_CALL_QOS_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_MODIFY_CALL_QOS_COMPLETE_HANDLER uintptr

// CL_OPEN_AF_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_OPEN_AF_COMPLETE_HANDLER uintptr

// CL_REG_SAP_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CL_REG_SAP_COMPLETE_HANDLER uintptr

// CM_ACTIVATE_VC_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CM_ACTIVATE_VC_COMPLETE_HANDLER uintptr

// CM_ADD_PARTY_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_ADD_PARTY_HANDLER uintptr

// CM_CLOSE_AF_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_CLOSE_AF_HANDLER uintptr

// CM_CLOSE_CALL_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_CLOSE_CALL_HANDLER uintptr

// CM_DEACTIVATE_VC_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CM_DEACTIVATE_VC_COMPLETE_HANDLER uintptr

// CM_DEREG_SAP_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_DEREG_SAP_HANDLER uintptr

// CM_DROP_PARTY_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_DROP_PARTY_HANDLER uintptr

// CM_INCOMING_CALL_COMPLETE_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CM_INCOMING_CALL_COMPLETE_HANDLER uintptr

// CM_MAKE_CALL_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_MAKE_CALL_HANDLER uintptr

// CM_MODIFY_CALL_QOS_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_MODIFY_CALL_QOS_HANDLER uintptr

// CM_OPEN_AF_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_OPEN_AF_HANDLER uintptr

// CM_REG_SAP_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CM_REG_SAP_HANDLER uintptr

// CO_AF_REGISTER_NOTIFY_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type CO_AF_REGISTER_NOTIFY_HANDLER uintptr

// CO_CREATE_VC_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CO_CREATE_VC_HANDLER uintptr

// CO_DELETE_VC_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type CO_DELETE_VC_HANDLER uintptr

// MINIPORT_CO_ACTIVATE_VC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_CALL_PARAMETERS) int32.
type MINIPORT_CO_ACTIVATE_VC uintptr

// MINIPORT_CO_CREATE_VC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, *unsafe.Pointer) int32.
type MINIPORT_CO_CREATE_VC uintptr

// MINIPORT_CO_DEACTIVATE_VC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer) int32.
type MINIPORT_CO_DEACTIVATE_VC uintptr

// MINIPORT_CO_DELETE_VC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer) int32.
type MINIPORT_CO_DELETE_VC uintptr

// NDIS_PROC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type NDIS_PROC uintptr

// NDIS_PROC_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*NDIS_WORK_ITEM, unsafe.Pointer).
type NDIS_PROC_CALLBACK uintptr

// NDIS_TIMER_FUNCTION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer).
type NDIS_TIMER_FUNCTION uintptr

// PNDIS_TIMER_FUNCTION is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PNDIS_TIMER_FUNCTION uintptr

// PROTCOL_CO_AF_REGISTER_NOTIFY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PROTCOL_CO_AF_REGISTER_NOTIFY uintptr

// PROTOCOL_CL_ADD_PARTY_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, unsafe.Pointer, *CO_CALL_PARAMETERS).
type PROTOCOL_CL_ADD_PARTY_COMPLETE uintptr

// PROTOCOL_CL_CALL_CONNECTED is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer).
type PROTOCOL_CL_CALL_CONNECTED uintptr

// PROTOCOL_CL_CLOSE_AF_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer).
type PROTOCOL_CL_CLOSE_AF_COMPLETE uintptr

// PROTOCOL_CL_CLOSE_CALL_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, unsafe.Pointer).
type PROTOCOL_CL_CLOSE_CALL_COMPLETE uintptr

// PROTOCOL_CL_DEREGISTER_SAP_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer).
type PROTOCOL_CL_DEREGISTER_SAP_COMPLETE uintptr

// PROTOCOL_CL_DROP_PARTY_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer).
type PROTOCOL_CL_DROP_PARTY_COMPLETE uintptr

// PROTOCOL_CL_INCOMING_CALL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, *CO_CALL_PARAMETERS) int32.
type PROTOCOL_CL_INCOMING_CALL uintptr

// PROTOCOL_CL_INCOMING_CALL_QOS_CHANGE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_CALL_PARAMETERS).
type PROTOCOL_CL_INCOMING_CALL_QOS_CHANGE uintptr

// PROTOCOL_CL_INCOMING_CLOSE_CALL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, unsafe.Pointer, uint32).
type PROTOCOL_CL_INCOMING_CLOSE_CALL uintptr

// PROTOCOL_CL_INCOMING_DROP_PARTY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, unsafe.Pointer, uint32).
type PROTOCOL_CL_INCOMING_DROP_PARTY uintptr

// PROTOCOL_CL_MAKE_CALL_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, unsafe.Pointer, *CO_CALL_PARAMETERS).
type PROTOCOL_CL_MAKE_CALL_COMPLETE uintptr

// PROTOCOL_CL_MODIFY_CALL_QOS_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, *CO_CALL_PARAMETERS).
type PROTOCOL_CL_MODIFY_CALL_QOS_COMPLETE uintptr

// PROTOCOL_CL_OPEN_AF_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, unsafe.Pointer).
type PROTOCOL_CL_OPEN_AF_COMPLETE uintptr

// PROTOCOL_CL_REGISTER_SAP_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, *CO_SAP, unsafe.Pointer).
type PROTOCOL_CL_REGISTER_SAP_COMPLETE uintptr

// PROTOCOL_CM_ACTIVATE_VC_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, *CO_CALL_PARAMETERS).
type PROTOCOL_CM_ACTIVATE_VC_COMPLETE uintptr

// PROTOCOL_CM_ADD_PARTY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_CALL_PARAMETERS, unsafe.Pointer, *unsafe.Pointer) int32.
type PROTOCOL_CM_ADD_PARTY uintptr

// PROTOCOL_CM_CLOSE_AF is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer) int32.
type PROTOCOL_CM_CLOSE_AF uintptr

// PROTOCOL_CM_CLOSE_CALL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, uint32) int32.
type PROTOCOL_CM_CLOSE_CALL uintptr

// PROTOCOL_CM_DEACTIVATE_VC_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer).
type PROTOCOL_CM_DEACTIVATE_VC_COMPLETE uintptr

// PROTOCOL_CM_DEREGISTER_SAP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer) int32.
type PROTOCOL_CM_DEREGISTER_SAP uintptr

// PROTOCOL_CM_DROP_PARTY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, uint32) int32.
type PROTOCOL_CM_DROP_PARTY uintptr

// PROTOCOL_CM_INCOMING_CALL_COMPLETE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(int32, unsafe.Pointer, *CO_CALL_PARAMETERS).
type PROTOCOL_CM_INCOMING_CALL_COMPLETE uintptr

// PROTOCOL_CM_MAKE_CALL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_CALL_PARAMETERS, unsafe.Pointer, *unsafe.Pointer) int32.
type PROTOCOL_CM_MAKE_CALL uintptr

// PROTOCOL_CM_MODIFY_QOS_CALL is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_CALL_PARAMETERS) int32.
type PROTOCOL_CM_MODIFY_QOS_CALL uintptr

// PROTOCOL_CM_OPEN_AF is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_ADDRESS_FAMILY, unsafe.Pointer, *unsafe.Pointer) int32.
type PROTOCOL_CM_OPEN_AF uintptr

// PROTOCOL_CM_REG_SAP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_SAP, unsafe.Pointer, *unsafe.Pointer) int32.
type PROTOCOL_CM_REG_SAP uintptr

// PROTOCOL_CO_AF_REGISTER_NOTIFY is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *CO_ADDRESS_FAMILY).
type PROTOCOL_CO_AF_REGISTER_NOTIFY uintptr

// PROTOCOL_CO_CREATE_VC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, *unsafe.Pointer) int32.
type PROTOCOL_CO_CREATE_VC uintptr

// PROTOCOL_CO_DELETE_VC is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer) int32.
type PROTOCOL_CO_DELETE_VC uintptr

// TDI_PNP_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*win32foundation.UNICODE_STRING, *win32foundation.UNICODE_STRING, *win32foundation.UNICODE_STRING, unsafe.Pointer, uint32, uint32) win32foundation.NTSTATUS.
type TDI_PNP_HANDLER uintptr

// TDI_REGISTER_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*win32foundation.UNICODE_STRING, *win32foundation.HANDLE) win32foundation.NTSTATUS.
type TDI_REGISTER_CALLBACK uintptr

// W_CO_ACTIVATE_VC_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type W_CO_ACTIVATE_VC_HANDLER uintptr

// W_CO_CREATE_VC_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type W_CO_CREATE_VC_HANDLER uintptr

// W_CO_DEACTIVATE_VC_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type W_CO_DEACTIVATE_VC_HANDLER uintptr

// W_CO_DELETE_VC_HANDLER is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() int32.
type W_CO_DELETE_VC_HANDLER uintptr
