// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package ndis

type CO_CALL_PARAMETERS uintptr

type CO_MEDIA_PARAMETERS uintptr

type ETH_FILTER uintptr

type NDIS_AF_LIST uintptr

type NDIS_CALL_MANAGER_CHARACTERISTICS uintptr

type NDIS_MINIPORT_BLOCK uintptr

type NDIS_M_DRIVER_BLOCK uintptr

type NDIS_OPEN_BLOCK uintptr

type NDIS_PD_COUNTER_HANDLE uintptr

type NDIS_PD_FILTER_HANDLE uintptr

type NDIS_PD_PROVIDER_HANDLE uintptr

type NDIS_POLL_HANDLE uintptr

type NDIS_PROTOCOL_BLOCK uintptr

type NDIS_WRAPPER_HANDLE uintptr

type NULL_FILTER uintptr

type TR_FILTER uintptr
