// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package ndis

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/foundation"
	systemsystemservices "github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/system/systemservices"
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32networkingwinsock "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networking/winsock"
	win32networkmanagementndis "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networkmanagement/ndis"
)

type BINARY_DATA struct {
	Length uint16
	Buffer unsafe.Pointer
}

type BSSID_INFO struct {
	BSSID [6]byte
	PMKID [16]byte
}

type CO_ADDRESS struct {
	AddressSize uint32
	Address     [1]byte
}

type CO_ADDRESS_FAMILY struct {
	AddressFamily uint32
	MajorVersion  uint32
	MinorVersion  uint32
}

type CO_ADDRESS_LIST struct {
	NumberOfAddressesAvailable uint32
	NumberOfAddresses          uint32
	AddressList                CO_ADDRESS
}

type CO_CALL_MANAGER_PARAMETERS struct {
	Transmit        win32networkingwinsock.FLOWSPEC
	Receive         win32networkingwinsock.FLOWSPEC
	CallMgrSpecific CO_SPECIFIC_PARAMETERS
}

type CO_PVC struct {
	NdisAfHandle  unsafe.Pointer
	PvcParameters CO_SPECIFIC_PARAMETERS
}

type CO_SAP struct {
	SapType   uint32
	SapLength uint32
	Sap       [1]byte
}

type CO_SPECIFIC_PARAMETERS struct {
	ParamType  uint32
	Length     uint32
	Parameters [1]byte
}

// FILTERDBS_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type FILTERDBS_Anonymous_e__Union struct {
	Data [1]uint64
}

type FILTERDBS struct {
	Anonymous FILTERDBS_Anonymous_e__Union
	TrDB      *uintptr
	YYYDB     unsafe.Pointer
	XXXDB     unsafe.Pointer
}

type GEN_GET_NETCARD_TIME struct {
	ReadTime uint64
}

type GEN_GET_TIME_CAPS struct {
	Flags          uint32
	ClockPrecision uint32
}

type LOCK_STATE struct {
	LockState uint16
	OldIrql   byte
}

type MEDIA_SPECIFIC_INFORMATION struct {
	NextEntryOffset  uint32
	ClassId          NDIS_CLASS_ID
	Size             uint32
	ClassInformation [1]byte
}

type NDIS_802_11_AI_REQFI struct {
	Capabilities     uint16
	ListenInterval   uint16
	CurrentAPAddress [6]byte
}

type NDIS_802_11_AI_RESFI struct {
	Capabilities  uint16
	StatusCode    uint16
	AssociationId uint16
}

type NDIS_802_11_ASSOCIATION_INFORMATION struct {
	Length                    uint32
	AvailableRequestFixedIEs  uint16
	RequestFixedIEs           NDIS_802_11_AI_REQFI
	RequestIELength           uint32
	OffsetRequestIEs          uint32
	AvailableResponseFixedIEs uint16
	ResponseFixedIEs          NDIS_802_11_AI_RESFI
	ResponseIELength          uint32
	OffsetResponseIEs         uint32
}

type NDIS_802_11_AUTHENTICATION_ENCRYPTION struct {
	AuthModeSupported      NDIS_802_11_AUTHENTICATION_MODE
	EncryptStatusSupported NDIS_802_11_WEP_STATUS
}

type NDIS_802_11_AUTHENTICATION_EVENT struct {
	Status  NDIS_802_11_STATUS_INDICATION
	Request [1]NDIS_802_11_AUTHENTICATION_REQUEST
}

type NDIS_802_11_AUTHENTICATION_REQUEST struct {
	Length uint32
	Bssid  [6]byte
	Flags  uint32
}

type NDIS_802_11_BSSID_LIST struct {
	NumberOfItems uint32
	Bssid         [1]NDIS_WLAN_BSSID
}

type NDIS_802_11_BSSID_LIST_EX struct {
	NumberOfItems uint32
	Bssid         [1]NDIS_WLAN_BSSID_EX
}

type NDIS_802_11_CAPABILITY struct {
	Length                            uint32
	Version                           uint32
	NoOfPMKIDs                        uint32
	NoOfAuthEncryptPairsSupported     uint32
	AuthenticationEncryptionSupported [1]NDIS_802_11_AUTHENTICATION_ENCRYPTION
}

type NDIS_802_11_CONFIGURATION struct {
	Length       uint32
	BeaconPeriod uint32
	ATIMWindow   uint32
	DSConfig     uint32
	FHConfig     NDIS_802_11_CONFIGURATION_FH
}

type NDIS_802_11_CONFIGURATION_FH struct {
	Length     uint32
	HopPattern uint32
	HopSet     uint32
	DwellTime  uint32
}

type NDIS_802_11_FIXED_IEs struct {
	Timestamp      [8]byte
	BeaconInterval uint16
	Capabilities   uint16
}

type NDIS_802_11_KEY struct {
	Length      uint32
	KeyIndex    uint32
	KeyLength   uint32
	BSSID       [6]byte
	KeyRSC      uint64
	KeyMaterial [1]byte
}

type NDIS_802_11_NETWORK_TYPE_LIST struct {
	NumberOfItems uint32
	NetworkType   [1]NDIS_802_11_NETWORK_TYPE
}

type NDIS_802_11_NON_BCAST_SSID_LIST struct {
	NumberOfItems  uint32
	Non_Bcast_Ssid [1]NDIS_802_11_SSID
}

type NDIS_802_11_PMKID struct {
	Length         uint32
	BSSIDInfoCount uint32
	BSSIDInfo      [1]BSSID_INFO
}

type NDIS_802_11_PMKID_CANDIDATE_LIST struct {
	Version       uint32
	NumCandidates uint32
	CandidateList [1]PMKID_CANDIDATE
}

type NDIS_802_11_REMOVE_KEY struct {
	Length   uint32
	KeyIndex uint32
	BSSID    [6]byte
}

type NDIS_802_11_SSID struct {
	SsidLength uint32
	Ssid       [32]byte
}

type NDIS_802_11_STATISTICS struct {
	Length                         uint32
	TransmittedFragmentCount       int64
	MulticastTransmittedFrameCount int64
	FailedCount                    int64
	RetryCount                     int64
	MultipleRetryCount             int64
	RTSSuccessCount                int64
	RTSFailureCount                int64
	ACKFailureCount                int64
	FrameDuplicateCount            int64
	ReceivedFragmentCount          int64
	MulticastReceivedFrameCount    int64
	FCSErrorCount                  int64
	TKIPLocalMICFailures           int64
	TKIPICVErrorCount              int64
	TKIPCounterMeasuresInvoked     int64
	TKIPReplays                    int64
	CCMPFormatErrors               int64
	CCMPReplays                    int64
	CCMPDecryptErrors              int64
	FourWayHandshakeFailures       int64
	WEPUndecryptableCount          int64
	WEPICVErrorCount               int64
	DecryptSuccessCount            int64
	DecryptFailureCount            int64
}

type NDIS_802_11_STATUS_INDICATION struct {
	StatusType NDIS_802_11_STATUS_TYPE
}

// NDIS_802_11_TEST_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_802_11_TEST_Anonymous_e__Union struct {
	Data [5]uint32
}

type NDIS_802_11_TEST struct {
	Length    uint32
	Type      uint32
	Anonymous NDIS_802_11_TEST_Anonymous_e__Union
}

type NDIS_802_11_VARIABLE_IEs struct {
	ElementID byte
	Length    byte
	Data      [1]byte
}

type NDIS_802_11_WEP struct {
	Length      uint32
	KeyIndex    uint32
	KeyLength   uint32
	KeyMaterial [1]byte
}

// NDIS_CONFIGURATION_PARAMETER_ParameterData_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_CONFIGURATION_PARAMETER_ParameterData_e__Union struct {
	Data [2]uint64
}

type NDIS_CONFIGURATION_PARAMETER struct {
	ParameterType NDIS_PARAMETER_TYPE
	ParameterData NDIS_CONFIGURATION_PARAMETER_ParameterData_e__Union
}

type NDIS_CO_DEVICE_PROFILE struct {
	DeviceDescription           NDIS_VAR_DATA_DESC
	DevSpecificInfo             NDIS_VAR_DATA_DESC
	UlTAPISupplementaryPassThru uint32
	UlAddressModes              uint32
	UlNumAddresses              uint32
	UlBearerModes               uint32
	UlMaxTxRate                 uint32
	UlMinTxRate                 uint32
	UlMaxRxRate                 uint32
	UlMinRxRate                 uint32
	UlMediaModes                uint32
	UlGenerateToneModes         uint32
	UlGenerateToneMaxNumFreq    uint32
	UlGenerateDigitModes        uint32
	UlMonitorToneMaxNumFreq     uint32
	UlMonitorToneMaxNumEntries  uint32
	UlMonitorDigitModes         uint32
	UlGatherDigitsMinTimeout    uint32
	UlGatherDigitsMaxTimeout    uint32
	UlDevCapFlags               uint32
	UlMaxNumActiveCalls         uint32
	UlAnswerMode                uint32
	UlUUIAcceptSize             uint32
	UlUUIAnswerSize             uint32
	UlUUIMakeCallSize           uint32
	UlUUIDropSize               uint32
	UlUUISendUserUserInfoSize   uint32
	UlUUICallInfoSize           uint32
}

type NDIS_CO_LINK_SPEED struct {
	Outbound uint32
	Inbound  uint32
}

type NDIS_DMA_BLOCK struct {
	MapRegisterBase     unsafe.Pointer
	AllocationEvent     foundation.KEVENT
	SystemAdapterObject unsafe.Pointer
	Miniport            unsafe.Pointer
	InProgress          win32foundation.BOOLEAN
}

type NDIS_DMA_DESCRIPTION struct {
	DemandMode          win32foundation.BOOLEAN
	AutoInitialize      win32foundation.BOOLEAN
	DmaChannelSpecified win32foundation.BOOLEAN
	DmaWidth            systemsystemservices.DMA_WIDTH
	DmaSpeed            systemsystemservices.DMA_SPEED
	DmaPort             uint32
	DmaChannel          uint32
}

type NDIS_EVENT struct {
	Event foundation.KEVENT
}

// NDIS_GUID_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_GUID_Anonymous_e__Union struct {
	Data [1]uint32
}

type NDIS_GUID struct {
	Guid      win32.GUID
	Anonymous NDIS_GUID_Anonymous_e__Union
	Size      uint32
	Flags     uint32
}

type NDIS_HARDWARE_CROSSTIMESTAMP struct {
	Header                 NDIS_OBJECT_HEADER
	Flags                  uint32
	SystemTimestamp1       uint64
	HardwareClockTimestamp uint64
	SystemTimestamp2       uint64
}

type NDIS_INTERRUPT_MODERATION_PARAMETERS struct {
	Header              NDIS_OBJECT_HEADER
	Flags               uint32
	InterruptModeration NDIS_INTERRUPT_MODERATION
}

type NDIS_IPSEC_OFFLOAD_V1_IPv4AH_e__Struct struct {
	Bitfield uint32
}

type NDIS_IPSEC_OFFLOAD_V1_IPv4ESP_e__Struct struct {
	Bitfield uint32
}

type NDIS_IPSEC_OFFLOAD_V1_Supported_e__Struct struct {
	Encapsulation           uint32
	AhEspCombined           uint32
	TransportTunnelCombined uint32
	IPv4Options             uint32
	Flags                   uint32
}

type NDIS_IPSEC_OFFLOAD_V1 struct {
	Supported NDIS_IPSEC_OFFLOAD_V1_Supported_e__Struct
	IPv4AH    NDIS_IPSEC_OFFLOAD_V1_IPv4AH_e__Struct
	IPv4ESP   NDIS_IPSEC_OFFLOAD_V1_IPv4ESP_e__Struct
}

type NDIS_IP_OPER_STATE struct {
	Header              NDIS_OBJECT_HEADER
	Flags               uint32
	IpOperationalStatus NDIS_IP_OPER_STATUS
}

type NDIS_IP_OPER_STATUS struct {
	AddressFamily          uint32
	OperationalStatus      win32networkmanagementndis.NET_IF_OPER_STATUS
	OperationalStatusFlags uint32
}

type NDIS_IP_OPER_STATUS_INFO struct {
	Header                          NDIS_OBJECT_HEADER
	Flags                           uint32
	NumberofAddressFamiliesReturned uint32
	IpOperationalStatus             [32]NDIS_IP_OPER_STATUS
}

type NDIS_IRDA_PACKET_INFO struct {
	ExtraBOFs         uint32
	MinTurnAroundTime uint32
}

type NDIS_LINK_PARAMETERS struct {
	Header               NDIS_OBJECT_HEADER
	MediaDuplexState     win32networkmanagementndis.NET_IF_MEDIA_DUPLEX_STATE
	XmitLinkSpeed        uint64
	RcvLinkSpeed         uint64
	PauseFunctions       NDIS_SUPPORTED_PAUSE_FUNCTIONS
	AutoNegotiationFlags uint32
}

type NDIS_LINK_SPEED struct {
	XmitLinkSpeed uint64
	RcvLinkSpeed  uint64
}

type NDIS_LINK_STATE struct {
	Header               NDIS_OBJECT_HEADER
	MediaConnectState    win32networkmanagementndis.NET_IF_MEDIA_CONNECT_STATE
	MediaDuplexState     win32networkmanagementndis.NET_IF_MEDIA_DUPLEX_STATE
	XmitLinkSpeed        uint64
	RcvLinkSpeed         uint64
	PauseFunctions       NDIS_SUPPORTED_PAUSE_FUNCTIONS
	AutoNegotiationFlags uint32
}

type NDIS_MINIPORT_TIMER struct {
	Timer                 systemsystemservices.KTIMER
	Dpc                   foundation.KDPC
	MiniportTimerFunction PNDIS_TIMER_FUNCTION
	MiniportTimerContext  unsafe.Pointer
	Miniport              *NDIS_MINIPORT_BLOCK
	NextTimer             *NDIS_MINIPORT_TIMER
}

type NDIS_OBJECT_HEADER struct {
	Type     byte
	Revision byte
	Size     uint16
}

type NDIS_OFFLOAD struct {
	Header   NDIS_OBJECT_HEADER
	Checksum NDIS_TCP_IP_CHECKSUM_OFFLOAD
	LsoV1    NDIS_TCP_LARGE_SEND_OFFLOAD_V1
	IPsecV1  NDIS_IPSEC_OFFLOAD_V1
	LsoV2    NDIS_TCP_LARGE_SEND_OFFLOAD_V2
	Flags    uint32
}

type NDIS_OFFLOAD_PARAMETERS struct {
	Header            NDIS_OBJECT_HEADER
	IPv4Checksum      byte
	TCPIPv4Checksum   byte
	UDPIPv4Checksum   byte
	TCPIPv6Checksum   byte
	UDPIPv6Checksum   byte
	LsoV1             byte
	IPsecV1           byte
	LsoV2IPv4         byte
	LsoV2IPv6         byte
	TcpConnectionIPv4 byte
	TcpConnectionIPv6 byte
	Flags             uint32
}

type NDIS_OPER_STATE struct {
	Header                 NDIS_OBJECT_HEADER
	OperationalStatus      win32networkmanagementndis.NET_IF_OPER_STATUS
	OperationalStatusFlags uint32
}

// NDIS_PACKET_8021Q_INFO_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_PACKET_8021Q_INFO_Anonymous_e__Union struct {
	Data [1]uint64
}

type NDIS_PACKET_8021Q_INFO struct {
	Anonymous NDIS_PACKET_8021Q_INFO_Anonymous_e__Union
}

type NDIS_PCI_DEVICE_CUSTOM_PROPERTIES struct {
	Header               NDIS_OBJECT_HEADER
	DeviceType           uint32
	CurrentSpeedAndMode  uint32
	CurrentPayloadSize   uint32
	MaxPayloadSize       uint32
	MaxReadRequestSize   uint32
	CurrentLinkSpeed     uint32
	CurrentLinkWidth     uint32
	MaxLinkSpeed         uint32
	MaxLinkWidth         uint32
	PciExpressVersion    uint32
	InterruptType        uint32
	MaxInterruptMessages uint32
}

type NDIS_PHYSICAL_ADDRESS_UNIT struct {
	PhysicalAddress int64
	Length          uint32
}

type NDIS_PM_PACKET_PATTERN struct {
	Priority      uint32
	Reserved      uint32
	MaskSize      uint32
	PatternOffset uint32
	PatternSize   uint32
	PatternFlags  uint32
}

type NDIS_PM_WAKE_UP_CAPABILITIES struct {
	MinMagicPacketWakeUp NDIS_DEVICE_POWER_STATE
	MinPatternWakeUp     NDIS_DEVICE_POWER_STATE
	MinLinkChangeWakeUp  NDIS_DEVICE_POWER_STATE
}

type NDIS_PNP_CAPABILITIES struct {
	Flags              uint32
	WakeUpCapabilities NDIS_PM_WAKE_UP_CAPABILITIES
}

type NDIS_PORT struct {
	Next                *NDIS_PORT
	NdisReserved        unsafe.Pointer
	MiniportReserved    unsafe.Pointer
	ProtocolReserved    unsafe.Pointer
	PortCharacteristics NDIS_PORT_CHARACTERISTICS
}

type NDIS_PORT_ARRAY struct {
	Header          NDIS_OBJECT_HEADER
	NumberOfPorts   uint32
	OffsetFirstPort uint32
	ElementSize     uint32
	Ports           [1]NDIS_PORT_CHARACTERISTICS
}

type NDIS_PORT_AUTHENTICATION_PARAMETERS struct {
	Header                 NDIS_OBJECT_HEADER
	SendControlState       NDIS_PORT_CONTROL_STATE
	RcvControlState        NDIS_PORT_CONTROL_STATE
	SendAuthorizationState NDIS_PORT_AUTHORIZATION_STATE
	RcvAuthorizationState  NDIS_PORT_AUTHORIZATION_STATE
}

type NDIS_PORT_CHARACTERISTICS struct {
	Header                 NDIS_OBJECT_HEADER
	PortNumber             uint32
	Flags                  uint32
	Type                   NDIS_PORT_TYPE
	MediaConnectState      win32networkmanagementndis.NET_IF_MEDIA_CONNECT_STATE
	XmitLinkSpeed          uint64
	RcvLinkSpeed           uint64
	Direction              win32networkmanagementndis.NET_IF_DIRECTION_TYPE
	SendControlState       NDIS_PORT_CONTROL_STATE
	RcvControlState        NDIS_PORT_CONTROL_STATE
	SendAuthorizationState NDIS_PORT_AUTHORIZATION_STATE
	RcvAuthorizationState  NDIS_PORT_AUTHORIZATION_STATE
}

type NDIS_PORT_STATE struct {
	Header                 NDIS_OBJECT_HEADER
	MediaConnectState      win32networkmanagementndis.NET_IF_MEDIA_CONNECT_STATE
	XmitLinkSpeed          uint64
	RcvLinkSpeed           uint64
	Direction              win32networkmanagementndis.NET_IF_DIRECTION_TYPE
	SendControlState       NDIS_PORT_CONTROL_STATE
	RcvControlState        NDIS_PORT_CONTROL_STATE
	SendAuthorizationState NDIS_PORT_AUTHORIZATION_STATE
	RcvAuthorizationState  NDIS_PORT_AUTHORIZATION_STATE
	Flags                  uint32
}

type NDIS_RECEIVE_HASH_PARAMETERS struct {
	Header              NDIS_OBJECT_HEADER
	Flags               uint32
	HashInformation     uint32
	HashSecretKeySize   uint16
	HashSecretKeyOffset uint32
}

type NDIS_RECEIVE_SCALE_CAPABILITIES struct {
	Header                    NDIS_OBJECT_HEADER
	CapabilitiesFlags         uint32
	NumberOfInterruptMessages uint32
	NumberOfReceiveQueues     uint32
}

type NDIS_RECEIVE_SCALE_PARAMETERS struct {
	Header                 NDIS_OBJECT_HEADER
	Flags                  uint16
	BaseCpuNumber          uint16
	HashInformation        uint32
	IndirectionTableSize   uint16
	IndirectionTableOffset uint32
	HashSecretKeySize      uint16
	HashSecretKeyOffset    uint32
}

// NDIS_RW_LOCK_Anonymous1_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_RW_LOCK_Anonymous1_e__Union struct {
	Data [2]uint64
}

// NDIS_RW_LOCK_Anonymous2_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_RW_LOCK_Anonymous2_e__Union struct {
	Data [64]uint64
}

type NDIS_RW_LOCK struct {
	Anonymous1 NDIS_RW_LOCK_Anonymous1_e__Union
	Anonymous2 NDIS_RW_LOCK_Anonymous2_e__Union
}

// NDIS_RW_LOCK_REFCOUNT is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_RW_LOCK_REFCOUNT struct {
	Data [4]uint32
}

type NDIS_SPIN_LOCK struct {
	SpinLock uintptr
	OldIrql  byte
}

type NDIS_STATISTICS_INFO struct {
	Header                 NDIS_OBJECT_HEADER
	SupportedStatistics    uint32
	IfInDiscards           uint64
	IfInErrors             uint64
	IfHCInOctets           uint64
	IfHCInUcastPkts        uint64
	IfHCInMulticastPkts    uint64
	IfHCInBroadcastPkts    uint64
	IfHCOutOctets          uint64
	IfHCOutUcastPkts       uint64
	IfHCOutMulticastPkts   uint64
	IfHCOutBroadcastPkts   uint64
	IfOutErrors            uint64
	IfOutDiscards          uint64
	IfHCInUcastOctets      uint64
	IfHCInMulticastOctets  uint64
	IfHCInBroadcastOctets  uint64
	IfHCOutUcastOctets     uint64
	IfHCOutMulticastOctets uint64
	IfHCOutBroadcastOctets uint64
}

type NDIS_STATISTICS_VALUE struct {
	Oid        uint32
	DataLength uint32
	Data       [1]byte
}

type NDIS_STATISTICS_VALUE_EX struct {
	Oid        uint32
	DataLength uint32
	Length     uint32
	Data       [1]byte
}

type NDIS_TCP_CONNECTION_OFFLOAD struct {
	Header                       NDIS_OBJECT_HEADER
	Encapsulation                uint32
	Bitfield                     uint32
	TcpConnectionOffloadCapacity uint32
	Flags                        uint32
}

type NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv4Receive_e__Struct struct {
	Encapsulation uint32
	Bitfield      uint32
}

type NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv4Transmit_e__Struct struct {
	Encapsulation uint32
	Bitfield      uint32
}

type NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv6Receive_e__Struct struct {
	Encapsulation uint32
	Bitfield      uint32
}

type NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv6Transmit_e__Struct struct {
	Encapsulation uint32
	Bitfield      uint32
}

type NDIS_TCP_IP_CHECKSUM_OFFLOAD struct {
	IPv4Transmit NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv4Transmit_e__Struct
	IPv4Receive  NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv4Receive_e__Struct
	IPv6Transmit NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv6Transmit_e__Struct
	IPv6Receive  NDIS_TCP_IP_CHECKSUM_OFFLOAD_IPv6Receive_e__Struct
}

// NDIS_TCP_IP_CHECKSUM_PACKET_INFO_Anonymous_e__Union is a C union, exposed as correctly sized and aligned backing
// storage; read or write a specific member through an unsafe.Pointer cast.
type NDIS_TCP_IP_CHECKSUM_PACKET_INFO_Anonymous_e__Union struct {
	Data [1]uint32
}

type NDIS_TCP_IP_CHECKSUM_PACKET_INFO struct {
	Anonymous NDIS_TCP_IP_CHECKSUM_PACKET_INFO_Anonymous_e__Union
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V1_IPv4_e__Struct struct {
	Encapsulation   uint32
	MaxOffLoadSize  uint32
	MinSegmentCount uint32
	Bitfield        uint32
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V1 struct {
	IPv4 NDIS_TCP_LARGE_SEND_OFFLOAD_V1_IPv4_e__Struct
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V2_IPv4_e__Struct struct {
	Encapsulation   uint32
	MaxOffLoadSize  uint32
	MinSegmentCount uint32
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V2_IPv6_e__Struct struct {
	Encapsulation   uint32
	MaxOffLoadSize  uint32
	MinSegmentCount uint32
	Bitfield        uint32
}

type NDIS_TCP_LARGE_SEND_OFFLOAD_V2 struct {
	IPv4 NDIS_TCP_LARGE_SEND_OFFLOAD_V2_IPv4_e__Struct
	IPv6 NDIS_TCP_LARGE_SEND_OFFLOAD_V2_IPv6_e__Struct
}

type NDIS_TIMEOUT_DPC_REQUEST_CAPABILITIES struct {
	Header             NDIS_OBJECT_HEADER
	Flags              uint32
	TimeoutArrayLength uint32
	TimeoutArray       [1]uint32
}

type NDIS_TIMER struct {
	Timer systemsystemservices.KTIMER
	Dpc   foundation.KDPC
}

type NDIS_TIMESTAMP_CAPABILITIES struct {
	Header                   NDIS_OBJECT_HEADER
	HardwareClockFrequencyHz uint64
	CrossTimestamp           win32foundation.BOOLEAN
	Reserved1                uint64
	Reserved2                uint64
	TimestampFlags           NDIS_TIMESTAMP_CAPABILITY_FLAGS
}

type NDIS_TIMESTAMP_CAPABILITY_FLAGS struct {
	PtpV2OverUdpIPv4EventMsgReceiveHw  win32foundation.BOOLEAN
	PtpV2OverUdpIPv4AllMsgReceiveHw    win32foundation.BOOLEAN
	PtpV2OverUdpIPv4EventMsgTransmitHw win32foundation.BOOLEAN
	PtpV2OverUdpIPv4AllMsgTransmitHw   win32foundation.BOOLEAN
	PtpV2OverUdpIPv6EventMsgReceiveHw  win32foundation.BOOLEAN
	PtpV2OverUdpIPv6AllMsgReceiveHw    win32foundation.BOOLEAN
	PtpV2OverUdpIPv6EventMsgTransmitHw win32foundation.BOOLEAN
	PtpV2OverUdpIPv6AllMsgTransmitHw   win32foundation.BOOLEAN
	AllReceiveHw                       win32foundation.BOOLEAN
	AllTransmitHw                      win32foundation.BOOLEAN
	TaggedTransmitHw                   win32foundation.BOOLEAN
	AllReceiveSw                       win32foundation.BOOLEAN
	AllTransmitSw                      win32foundation.BOOLEAN
	TaggedTransmitSw                   win32foundation.BOOLEAN
}

type NDIS_VAR_DATA_DESC struct {
	Length        uint16
	MaximumLength uint16
	Offset        uintptr
}

type NDIS_WAN_FRAGMENT struct {
	RemoteAddress [6]byte
	LocalAddress  [6]byte
}

type NDIS_WAN_GET_STATS struct {
	LocalAddress                 [6]byte
	BytesSent                    uint32
	BytesRcvd                    uint32
	FramesSent                   uint32
	FramesRcvd                   uint32
	CRCErrors                    uint32
	TimeoutErrors                uint32
	AlignmentErrors              uint32
	SerialOverrunErrors          uint32
	FramingErrors                uint32
	BufferOverrunErrors          uint32
	BytesTransmittedUncompressed uint32
	BytesReceivedUncompressed    uint32
	BytesTransmittedCompressed   uint32
	BytesReceivedCompressed      uint32
}

type NDIS_WAN_LINE_DOWN struct {
	RemoteAddress [6]byte
	LocalAddress  [6]byte
}

type NDIS_WAN_LINE_UP struct {
	LinkSpeed            uint32
	MaximumTotalSize     uint32
	Quality              NDIS_WAN_QUALITY
	SendWindow           uint16
	RemoteAddress        [6]byte
	LocalAddress         [6]byte
	ProtocolBufferLength uint32
	ProtocolBuffer       *byte
	ProtocolType         uint16
	DeviceName           win32foundation.UNICODE_STRING
}

type NDIS_WAN_PROTOCOL_CAPS struct {
	Flags    uint32
	Reserved uint32
}

type NDIS_WLAN_BSSID struct {
	Length             uint32
	MacAddress         [6]byte
	Reserved           [2]byte
	Ssid               NDIS_802_11_SSID
	Privacy            uint32
	Rssi               int32
	NetworkTypeInUse   NDIS_802_11_NETWORK_TYPE
	Configuration      NDIS_802_11_CONFIGURATION
	InfrastructureMode NDIS_802_11_NETWORK_INFRASTRUCTURE
	SupportedRates     [8]byte
}

type NDIS_WLAN_BSSID_EX struct {
	Length             uint32
	MacAddress         [6]byte
	Reserved           [2]byte
	Ssid               NDIS_802_11_SSID
	Privacy            uint32
	Rssi               int32
	NetworkTypeInUse   NDIS_802_11_NETWORK_TYPE
	Configuration      NDIS_802_11_CONFIGURATION
	InfrastructureMode NDIS_802_11_NETWORK_INFRASTRUCTURE
	SupportedRates     [16]byte
	IELength           uint32
	IEs                [1]byte
}

type NDIS_WMI_ENUM_ADAPTER struct {
	Header           NDIS_OBJECT_HEADER
	IfIndex          uint32
	NetLuid          win32networkmanagementndis.NET_LUID_LH
	DeviceNameLength uint16
	DeviceName       [1]win32foundation.CHAR
}

type NDIS_WMI_EVENT_HEADER struct {
	Header           NDIS_OBJECT_HEADER
	IfIndex          uint32
	NetLuid          win32networkmanagementndis.NET_LUID_LH
	RequestId        uint64
	PortNumber       uint32
	DeviceNameLength uint32
	DeviceNameOffset uint32
	Padding          [4]byte
}

type NDIS_WMI_IPSEC_OFFLOAD_V1_IPv4AH_e__Struct struct {
	Md5       uint32
	Sha_1     uint32
	Transport uint32
	Tunnel    uint32
	Send      uint32
	Receive   uint32
}

type NDIS_WMI_IPSEC_OFFLOAD_V1_IPv4ESP_e__Struct struct {
	Des       uint32
	Reserved  uint32
	TripleDes uint32
	NullEsp   uint32
	Transport uint32
	Tunnel    uint32
	Send      uint32
	Receive   uint32
}

type NDIS_WMI_IPSEC_OFFLOAD_V1_Supported_e__Struct struct {
	Encapsulation           uint32
	AhEspCombined           uint32
	TransportTunnelCombined uint32
	IPv4Options             uint32
	Flags                   uint32
}

type NDIS_WMI_IPSEC_OFFLOAD_V1 struct {
	Supported NDIS_WMI_IPSEC_OFFLOAD_V1_Supported_e__Struct
	IPv4AH    NDIS_WMI_IPSEC_OFFLOAD_V1_IPv4AH_e__Struct
	IPv4ESP   NDIS_WMI_IPSEC_OFFLOAD_V1_IPv4ESP_e__Struct
}

type NDIS_WMI_METHOD_HEADER struct {
	Header     NDIS_OBJECT_HEADER
	PortNumber uint32
	NetLuid    win32networkmanagementndis.NET_LUID_LH
	RequestId  uint64
	Timeout    uint32
	Padding    [4]byte
}

type NDIS_WMI_OFFLOAD struct {
	Header   NDIS_OBJECT_HEADER
	Checksum NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD
	LsoV1    NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V1
	IPsecV1  NDIS_WMI_IPSEC_OFFLOAD_V1
	LsoV2    NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2
	Flags    uint32
}

type NDIS_WMI_OUTPUT_INFO struct {
	Header            NDIS_OBJECT_HEADER
	Flags             uint32
	SupportedRevision byte
	DataOffset        uint32
}

type NDIS_WMI_SET_HEADER struct {
	Header     NDIS_OBJECT_HEADER
	PortNumber uint32
	NetLuid    win32networkmanagementndis.NET_LUID_LH
	RequestId  uint64
	Timeout    uint32
	Padding    [4]byte
}

type NDIS_WMI_TCP_CONNECTION_OFFLOAD struct {
	Header                       NDIS_OBJECT_HEADER
	Encapsulation                uint32
	SupportIPv4                  uint32
	SupportIPv6                  uint32
	SupportIPv6ExtensionHeaders  uint32
	SupportSack                  uint32
	TcpConnectionOffloadCapacity uint32
	Flags                        uint32
}

type NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv4Receive_e__Struct struct {
	Encapsulation       uint32
	IpOptionsSupported  uint32
	TcpOptionsSupported uint32
	TcpChecksum         uint32
	UdpChecksum         uint32
	IpChecksum          uint32
}

type NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv4Transmit_e__Struct struct {
	Encapsulation       uint32
	IpOptionsSupported  uint32
	TcpOptionsSupported uint32
	TcpChecksum         uint32
	UdpChecksum         uint32
	IpChecksum          uint32
}

type NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv6Receive_e__Struct struct {
	Encapsulation               uint32
	IpExtensionHeadersSupported uint32
	TcpOptionsSupported         uint32
	TcpChecksum                 uint32
	UdpChecksum                 uint32
}

type NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv6Transmit_e__Struct struct {
	Encapsulation               uint32
	IpExtensionHeadersSupported uint32
	TcpOptionsSupported         uint32
	TcpChecksum                 uint32
	UdpChecksum                 uint32
}

type NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD struct {
	IPv4Transmit NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv4Transmit_e__Struct
	IPv4Receive  NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv4Receive_e__Struct
	IPv6Transmit NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv6Transmit_e__Struct
	IPv6Receive  NDIS_WMI_TCP_IP_CHECKSUM_OFFLOAD_IPv6Receive_e__Struct
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V1_IPv4_e__Struct struct {
	Encapsulation   uint32
	MaxOffLoadSize  uint32
	MinSegmentCount uint32
	TcpOptions      uint32
	IpOptions       uint32
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V1 struct {
	IPv4 NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V1_IPv4_e__Struct
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2_IPv4_e__Struct struct {
	Encapsulation   uint32
	MaxOffLoadSize  uint32
	MinSegmentCount uint32
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2_IPv6_e__Struct struct {
	Encapsulation               uint32
	MaxOffLoadSize              uint32
	MinSegmentCount             uint32
	IpExtensionHeadersSupported uint32
	TcpOptionsSupported         uint32
}

type NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2 struct {
	IPv4 NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2_IPv4_e__Struct
	IPv6 NDIS_WMI_TCP_LARGE_SEND_OFFLOAD_V2_IPv6_e__Struct
}

type NDIS_WORK_ITEM struct {
	Context         unsafe.Pointer
	Routine         NDIS_PROC
	WrapperReserved [32]byte
}

type NETWORK_ADDRESS struct {
	AddressLength uint16
	AddressType   uint16
	Address       [1]byte
}

type NETWORK_ADDRESS_IP struct {
	Sin_port uint16
	IN_ADDR  uint32
	Sin_zero [8]byte
}

type NETWORK_ADDRESS_IP6 struct {
	Sin6_port     uint16
	Sin6_flowinfo uint32
	Sin6_addr     [8]uint16
	Sin6_scope_id uint32
}

type NETWORK_ADDRESS_IPX struct {
	NetworkAddress uint32
	NodeAddress    [6]byte
	Socket         uint16
}

type NETWORK_ADDRESS_LIST struct {
	AddressCount int32
	AddressType  uint16
	Address      [1]NETWORK_ADDRESS
}

type OFFLOAD_ALGO_INFO struct {
	AlgoIdentifier uint32
	AlgoKeylen     uint32
	AlgoRounds     uint32
}

type OFFLOAD_IPSEC_ADD_SA struct {
	SrcAddr        uint32
	SrcMask        uint32
	DestAddr       uint32
	DestMask       uint32
	Protocol       uint32
	SrcPort        uint16
	DestPort       uint16
	SrcTunnelAddr  uint32
	DestTunnelAddr uint32
	Flags          uint16
	NumSAs         int16
	SecAssoc       [3]OFFLOAD_SECURITY_ASSOCIATION
	OffloadHandle  win32foundation.HANDLE
	KeyLen         uint32
	KeyMat         [1]byte
}

type OFFLOAD_IPSEC_ADD_UDPESP_SA struct {
	SrcAddr                   uint32
	SrcMask                   uint32
	DstAddr                   uint32
	DstMask                   uint32
	Protocol                  uint32
	SrcPort                   uint16
	DstPort                   uint16
	SrcTunnelAddr             uint32
	DstTunnelAddr             uint32
	Flags                     uint16
	NumSAs                    int16
	SecAssoc                  [3]OFFLOAD_SECURITY_ASSOCIATION
	OffloadHandle             win32foundation.HANDLE
	EncapTypeEntry            OFFLOAD_IPSEC_UDPESP_ENCAPTYPE_ENTRY
	EncapTypeEntryOffldHandle win32foundation.HANDLE
	KeyLen                    uint32
	KeyMat                    [1]byte
}

type OFFLOAD_IPSEC_DELETE_SA struct {
	OffloadHandle win32foundation.HANDLE
}

type OFFLOAD_IPSEC_DELETE_UDPESP_SA struct {
	OffloadHandle             win32foundation.HANDLE
	EncapTypeEntryOffldHandle win32foundation.HANDLE
}

type OFFLOAD_IPSEC_UDPESP_ENCAPTYPE_ENTRY struct {
	UdpEncapType UDP_ENCAP_TYPE
	DstEncapPort uint16
}

type OFFLOAD_SECURITY_ASSOCIATION struct {
	Operation     OFFLOAD_OPERATION_E
	SPI           uint32
	IntegrityAlgo OFFLOAD_ALGO_INFO
	ConfAlgo      OFFLOAD_ALGO_INFO
	Reserved      OFFLOAD_ALGO_INFO
}

type PMKID_CANDIDATE struct {
	BSSID [6]byte
	Flags uint32
}

type REFERENCE struct {
	SpinLock       uintptr
	ReferenceCount uint16
	Closing        win32foundation.BOOLEAN
}

type TRANSPORT_HEADER_OFFSET struct {
	ProtocolType uint16
	HeaderOffset uint16
}

type VAR_STRING struct {
	UlTotalSize    uint32
	UlNeededSize   uint32
	UlUsedSize     uint32
	UlStringFormat uint32
	UlStringSize   uint32
	UlStringOffset uint32
}
