// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package minifilters

type PFLT_CONTEXT uintptr

type PFLT_DEFERRED_IO_WORKITEM uintptr

type PFLT_FILTER uintptr

type PFLT_GENERIC_WORKITEM uintptr

type PFLT_INSTANCE uintptr

type PFLT_PORT uintptr

type PFLT_VOLUME uintptr
