// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package threading

import (
	"fmt"
)

type PROCESSINFOCLASS int32

const (
	ProcessBasicInformation                     PROCESSINFOCLASS = 0
	ProcessQuotaLimits                          PROCESSINFOCLASS = 1
	ProcessIoCounters                           PROCESSINFOCLASS = 2
	ProcessVmCounters                           PROCESSINFOCLASS = 3
	ProcessTimes                                PROCESSINFOCLASS = 4
	ProcessBasePriority                         PROCESSINFOCLASS = 5
	ProcessRaisePriority                        PROCESSINFOCLASS = 6
	ProcessDebugPort                            PROCESSINFOCLASS = 7
	ProcessExceptionPort                        PROCESSINFOCLASS = 8
	ProcessAccessToken                          PROCESSINFOCLASS = 9
	ProcessLdtInformation                       PROCESSINFOCLASS = 10
	ProcessLdtSize                              PROCESSINFOCLASS = 11
	ProcessDefaultHardErrorMode                 PROCESSINFOCLASS = 12
	ProcessIoPortHandlers                       PROCESSINFOCLASS = 13
	ProcessPooledUsageAndLimits                 PROCESSINFOCLASS = 14
	ProcessWorkingSetWatch                      PROCESSINFOCLASS = 15
	ProcessUserModeIOPL                         PROCESSINFOCLASS = 16
	ProcessEnableAlignmentFaultFixup            PROCESSINFOCLASS = 17
	ProcessPriorityClass                        PROCESSINFOCLASS = 18
	ProcessWx86Information                      PROCESSINFOCLASS = 19
	ProcessHandleCount                          PROCESSINFOCLASS = 20
	ProcessAffinityMask                         PROCESSINFOCLASS = 21
	ProcessPriorityBoost                        PROCESSINFOCLASS = 22
	ProcessDeviceMap                            PROCESSINFOCLASS = 23
	ProcessSessionInformation                   PROCESSINFOCLASS = 24
	ProcessForegroundInformation                PROCESSINFOCLASS = 25
	ProcessWow64Information                     PROCESSINFOCLASS = 26
	ProcessImageFileName                        PROCESSINFOCLASS = 27
	ProcessLUIDDeviceMapsEnabled                PROCESSINFOCLASS = 28
	ProcessBreakOnTermination                   PROCESSINFOCLASS = 29
	ProcessDebugObjectHandle                    PROCESSINFOCLASS = 30
	ProcessDebugFlags                           PROCESSINFOCLASS = 31
	ProcessHandleTracing                        PROCESSINFOCLASS = 32
	ProcessIoPriority                           PROCESSINFOCLASS = 33
	ProcessExecuteFlags                         PROCESSINFOCLASS = 34
	ProcessTlsInformation                       PROCESSINFOCLASS = 35
	ProcessCookie                               PROCESSINFOCLASS = 36
	ProcessImageInformation                     PROCESSINFOCLASS = 37
	ProcessCycleTime                            PROCESSINFOCLASS = 38
	ProcessPagePriority                         PROCESSINFOCLASS = 39
	ProcessInstrumentationCallback              PROCESSINFOCLASS = 40
	ProcessThreadStackAllocation                PROCESSINFOCLASS = 41
	ProcessWorkingSetWatchEx                    PROCESSINFOCLASS = 42
	ProcessImageFileNameWin32                   PROCESSINFOCLASS = 43
	ProcessImageFileMapping                     PROCESSINFOCLASS = 44
	ProcessAffinityUpdateMode                   PROCESSINFOCLASS = 45
	ProcessMemoryAllocationMode                 PROCESSINFOCLASS = 46
	ProcessGroupInformation                     PROCESSINFOCLASS = 47
	ProcessTokenVirtualizationEnabled           PROCESSINFOCLASS = 48
	ProcessOwnerInformation                     PROCESSINFOCLASS = 49
	ProcessWindowInformation                    PROCESSINFOCLASS = 50
	ProcessHandleInformation                    PROCESSINFOCLASS = 51
	ProcessMitigationPolicy                     PROCESSINFOCLASS = 52
	ProcessDynamicFunctionTableInformation      PROCESSINFOCLASS = 53
	ProcessHandleCheckingMode                   PROCESSINFOCLASS = 54
	ProcessKeepAliveCount                       PROCESSINFOCLASS = 55
	ProcessRevokeFileHandles                    PROCESSINFOCLASS = 56
	ProcessWorkingSetControl                    PROCESSINFOCLASS = 57
	ProcessHandleTable                          PROCESSINFOCLASS = 58
	ProcessCheckStackExtentsMode                PROCESSINFOCLASS = 59
	ProcessCommandLineInformation               PROCESSINFOCLASS = 60
	ProcessProtectionInformation                PROCESSINFOCLASS = 61
	ProcessMemoryExhaustion                     PROCESSINFOCLASS = 62
	ProcessFaultInformation                     PROCESSINFOCLASS = 63
	ProcessTelemetryIdInformation               PROCESSINFOCLASS = 64
	ProcessCommitReleaseInformation             PROCESSINFOCLASS = 65
	ProcessReserved1Information                 PROCESSINFOCLASS = 66
	ProcessReserved2Information                 PROCESSINFOCLASS = 67
	ProcessSubsystemProcess                     PROCESSINFOCLASS = 68
	ProcessInPrivate                            PROCESSINFOCLASS = 70
	ProcessRaiseUMExceptionOnInvalidHandleClose PROCESSINFOCLASS = 71
	ProcessSubsystemInformation                 PROCESSINFOCLASS = 75
	ProcessWin32kSyscallFilterInformation       PROCESSINFOCLASS = 79
	ProcessEnergyTrackingState                  PROCESSINFOCLASS = 82
	MaxProcessInfoClass                         PROCESSINFOCLASS = 83
)

// String returns the PROCESSINFOCLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e PROCESSINFOCLASS) String() string {
	switch e {
	case ProcessBasicInformation:
		return "ProcessBasicInformation"
	case ProcessQuotaLimits:
		return "ProcessQuotaLimits"
	case ProcessIoCounters:
		return "ProcessIoCounters"
	case ProcessVmCounters:
		return "ProcessVmCounters"
	case ProcessTimes:
		return "ProcessTimes"
	case ProcessBasePriority:
		return "ProcessBasePriority"
	case ProcessRaisePriority:
		return "ProcessRaisePriority"
	case ProcessDebugPort:
		return "ProcessDebugPort"
	case ProcessExceptionPort:
		return "ProcessExceptionPort"
	case ProcessAccessToken:
		return "ProcessAccessToken"
	case ProcessLdtInformation:
		return "ProcessLdtInformation"
	case ProcessLdtSize:
		return "ProcessLdtSize"
	case ProcessDefaultHardErrorMode:
		return "ProcessDefaultHardErrorMode"
	case ProcessIoPortHandlers:
		return "ProcessIoPortHandlers"
	case ProcessPooledUsageAndLimits:
		return "ProcessPooledUsageAndLimits"
	case ProcessWorkingSetWatch:
		return "ProcessWorkingSetWatch"
	case ProcessUserModeIOPL:
		return "ProcessUserModeIOPL"
	case ProcessEnableAlignmentFaultFixup:
		return "ProcessEnableAlignmentFaultFixup"
	case ProcessPriorityClass:
		return "ProcessPriorityClass"
	case ProcessWx86Information:
		return "ProcessWx86Information"
	case ProcessHandleCount:
		return "ProcessHandleCount"
	case ProcessAffinityMask:
		return "ProcessAffinityMask"
	case ProcessPriorityBoost:
		return "ProcessPriorityBoost"
	case ProcessDeviceMap:
		return "ProcessDeviceMap"
	case ProcessSessionInformation:
		return "ProcessSessionInformation"
	case ProcessForegroundInformation:
		return "ProcessForegroundInformation"
	case ProcessWow64Information:
		return "ProcessWow64Information"
	case ProcessImageFileName:
		return "ProcessImageFileName"
	case ProcessLUIDDeviceMapsEnabled:
		return "ProcessLUIDDeviceMapsEnabled"
	case ProcessBreakOnTermination:
		return "ProcessBreakOnTermination"
	case ProcessDebugObjectHandle:
		return "ProcessDebugObjectHandle"
	case ProcessDebugFlags:
		return "ProcessDebugFlags"
	case ProcessHandleTracing:
		return "ProcessHandleTracing"
	case ProcessIoPriority:
		return "ProcessIoPriority"
	case ProcessExecuteFlags:
		return "ProcessExecuteFlags"
	case ProcessTlsInformation:
		return "ProcessTlsInformation"
	case ProcessCookie:
		return "ProcessCookie"
	case ProcessImageInformation:
		return "ProcessImageInformation"
	case ProcessCycleTime:
		return "ProcessCycleTime"
	case ProcessPagePriority:
		return "ProcessPagePriority"
	case ProcessInstrumentationCallback:
		return "ProcessInstrumentationCallback"
	case ProcessThreadStackAllocation:
		return "ProcessThreadStackAllocation"
	case ProcessWorkingSetWatchEx:
		return "ProcessWorkingSetWatchEx"
	case ProcessImageFileNameWin32:
		return "ProcessImageFileNameWin32"
	case ProcessImageFileMapping:
		return "ProcessImageFileMapping"
	case ProcessAffinityUpdateMode:
		return "ProcessAffinityUpdateMode"
	case ProcessMemoryAllocationMode:
		return "ProcessMemoryAllocationMode"
	case ProcessGroupInformation:
		return "ProcessGroupInformation"
	case ProcessTokenVirtualizationEnabled:
		return "ProcessTokenVirtualizationEnabled"
	case ProcessOwnerInformation:
		return "ProcessOwnerInformation"
	case ProcessWindowInformation:
		return "ProcessWindowInformation"
	case ProcessHandleInformation:
		return "ProcessHandleInformation"
	case ProcessMitigationPolicy:
		return "ProcessMitigationPolicy"
	case ProcessDynamicFunctionTableInformation:
		return "ProcessDynamicFunctionTableInformation"
	case ProcessHandleCheckingMode:
		return "ProcessHandleCheckingMode"
	case ProcessKeepAliveCount:
		return "ProcessKeepAliveCount"
	case ProcessRevokeFileHandles:
		return "ProcessRevokeFileHandles"
	case ProcessWorkingSetControl:
		return "ProcessWorkingSetControl"
	case ProcessHandleTable:
		return "ProcessHandleTable"
	case ProcessCheckStackExtentsMode:
		return "ProcessCheckStackExtentsMode"
	case ProcessCommandLineInformation:
		return "ProcessCommandLineInformation"
	case ProcessProtectionInformation:
		return "ProcessProtectionInformation"
	case ProcessMemoryExhaustion:
		return "ProcessMemoryExhaustion"
	case ProcessFaultInformation:
		return "ProcessFaultInformation"
	case ProcessTelemetryIdInformation:
		return "ProcessTelemetryIdInformation"
	case ProcessCommitReleaseInformation:
		return "ProcessCommitReleaseInformation"
	case ProcessReserved1Information:
		return "ProcessReserved1Information"
	case ProcessReserved2Information:
		return "ProcessReserved2Information"
	case ProcessSubsystemProcess:
		return "ProcessSubsystemProcess"
	case ProcessInPrivate:
		return "ProcessInPrivate"
	case ProcessRaiseUMExceptionOnInvalidHandleClose:
		return "ProcessRaiseUMExceptionOnInvalidHandleClose"
	case ProcessSubsystemInformation:
		return "ProcessSubsystemInformation"
	case ProcessWin32kSyscallFilterInformation:
		return "ProcessWin32kSyscallFilterInformation"
	case ProcessEnergyTrackingState:
		return "ProcessEnergyTrackingState"
	case MaxProcessInfoClass:
		return "MaxProcessInfoClass"
	default:
		return fmt.Sprintf("PROCESSINFOCLASS(%d)", int32(e))
	}
}

type THREADINFOCLASS int32

const (
	ThreadBasicInformation          THREADINFOCLASS = 0
	ThreadTimes                     THREADINFOCLASS = 1
	ThreadPriority                  THREADINFOCLASS = 2
	ThreadBasePriority              THREADINFOCLASS = 3
	ThreadAffinityMask              THREADINFOCLASS = 4
	ThreadImpersonationToken        THREADINFOCLASS = 5
	ThreadDescriptorTableEntry      THREADINFOCLASS = 6
	ThreadEnableAlignmentFaultFixup THREADINFOCLASS = 7
	ThreadEventPair_Reusable        THREADINFOCLASS = 8
	ThreadQuerySetWin32StartAddress THREADINFOCLASS = 9
	ThreadZeroTlsCell               THREADINFOCLASS = 10
	ThreadPerformanceCount          THREADINFOCLASS = 11
	ThreadAmILastThread             THREADINFOCLASS = 12
	ThreadIdealProcessor            THREADINFOCLASS = 13
	ThreadPriorityBoost             THREADINFOCLASS = 14
	ThreadSetTlsArrayAddress        THREADINFOCLASS = 15
	ThreadIsIoPending               THREADINFOCLASS = 16
	ThreadHideFromDebugger          THREADINFOCLASS = 17
	ThreadBreakOnTermination        THREADINFOCLASS = 18
	ThreadSwitchLegacyState         THREADINFOCLASS = 19
	ThreadIsTerminated              THREADINFOCLASS = 20
	ThreadLastSystemCall            THREADINFOCLASS = 21
	ThreadIoPriority                THREADINFOCLASS = 22
	ThreadCycleTime                 THREADINFOCLASS = 23
	ThreadPagePriority              THREADINFOCLASS = 24
	ThreadActualBasePriority        THREADINFOCLASS = 25
	ThreadTebInformation            THREADINFOCLASS = 26
	ThreadCSwitchMon                THREADINFOCLASS = 27
	ThreadCSwitchPmu                THREADINFOCLASS = 28
	ThreadWow64Context              THREADINFOCLASS = 29
	ThreadGroupInformation          THREADINFOCLASS = 30
	ThreadUmsInformation            THREADINFOCLASS = 31
	ThreadCounterProfiling          THREADINFOCLASS = 32
	ThreadIdealProcessorEx          THREADINFOCLASS = 33
	ThreadCpuAccountingInformation  THREADINFOCLASS = 34
	ThreadSuspendCount              THREADINFOCLASS = 35
	ThreadActualGroupAffinity       THREADINFOCLASS = 41
	ThreadDynamicCodePolicyInfo     THREADINFOCLASS = 42
	ThreadSubsystemInformation      THREADINFOCLASS = 45
	MaxThreadInfoClass              THREADINFOCLASS = 56
	ThreadNameInformation           THREADINFOCLASS = 38
)

// String returns the THREADINFOCLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e THREADINFOCLASS) String() string {
	switch e {
	case ThreadBasicInformation:
		return "ThreadBasicInformation"
	case ThreadTimes:
		return "ThreadTimes"
	case ThreadPriority:
		return "ThreadPriority"
	case ThreadBasePriority:
		return "ThreadBasePriority"
	case ThreadAffinityMask:
		return "ThreadAffinityMask"
	case ThreadImpersonationToken:
		return "ThreadImpersonationToken"
	case ThreadDescriptorTableEntry:
		return "ThreadDescriptorTableEntry"
	case ThreadEnableAlignmentFaultFixup:
		return "ThreadEnableAlignmentFaultFixup"
	case ThreadEventPair_Reusable:
		return "ThreadEventPair_Reusable"
	case ThreadQuerySetWin32StartAddress:
		return "ThreadQuerySetWin32StartAddress"
	case ThreadZeroTlsCell:
		return "ThreadZeroTlsCell"
	case ThreadPerformanceCount:
		return "ThreadPerformanceCount"
	case ThreadAmILastThread:
		return "ThreadAmILastThread"
	case ThreadIdealProcessor:
		return "ThreadIdealProcessor"
	case ThreadPriorityBoost:
		return "ThreadPriorityBoost"
	case ThreadSetTlsArrayAddress:
		return "ThreadSetTlsArrayAddress"
	case ThreadIsIoPending:
		return "ThreadIsIoPending"
	case ThreadHideFromDebugger:
		return "ThreadHideFromDebugger"
	case ThreadBreakOnTermination:
		return "ThreadBreakOnTermination"
	case ThreadSwitchLegacyState:
		return "ThreadSwitchLegacyState"
	case ThreadIsTerminated:
		return "ThreadIsTerminated"
	case ThreadLastSystemCall:
		return "ThreadLastSystemCall"
	case ThreadIoPriority:
		return "ThreadIoPriority"
	case ThreadCycleTime:
		return "ThreadCycleTime"
	case ThreadPagePriority:
		return "ThreadPagePriority"
	case ThreadActualBasePriority:
		return "ThreadActualBasePriority"
	case ThreadTebInformation:
		return "ThreadTebInformation"
	case ThreadCSwitchMon:
		return "ThreadCSwitchMon"
	case ThreadCSwitchPmu:
		return "ThreadCSwitchPmu"
	case ThreadWow64Context:
		return "ThreadWow64Context"
	case ThreadGroupInformation:
		return "ThreadGroupInformation"
	case ThreadUmsInformation:
		return "ThreadUmsInformation"
	case ThreadCounterProfiling:
		return "ThreadCounterProfiling"
	case ThreadIdealProcessorEx:
		return "ThreadIdealProcessorEx"
	case ThreadCpuAccountingInformation:
		return "ThreadCpuAccountingInformation"
	case ThreadSuspendCount:
		return "ThreadSuspendCount"
	case ThreadActualGroupAffinity:
		return "ThreadActualGroupAffinity"
	case ThreadDynamicCodePolicyInfo:
		return "ThreadDynamicCodePolicyInfo"
	case ThreadSubsystemInformation:
		return "ThreadSubsystemInformation"
	case MaxThreadInfoClass:
		return "MaxThreadInfoClass"
	case ThreadNameInformation:
		return "ThreadNameInformation"
	default:
		return fmt.Sprintf("THREADINFOCLASS(%d)", int32(e))
	}
}

type TIMER_SET_INFORMATION_CLASS int32

const (
	TimerSetCoalescableTimer TIMER_SET_INFORMATION_CLASS = 0
	MaxTimerInfoClass        TIMER_SET_INFORMATION_CLASS = 1
)

// String returns the TIMER_SET_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e TIMER_SET_INFORMATION_CLASS) String() string {
	switch e {
	case TimerSetCoalescableTimer:
		return "TimerSetCoalescableTimer"
	case MaxTimerInfoClass:
		return "MaxTimerInfoClass"
	default:
		return fmt.Sprintf("TIMER_SET_INFORMATION_CLASS(%d)", int32(e))
	}
}
