// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package threading

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/foundation"
	systemsystemservices "github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/system/systemservices"
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32systemkernel "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/kernel"
	win32systemwindowsprogramming "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/windowsprogramming"
)

var (
	modntdll = win32.NewDLL("ntdll.dll")
)

var (
	procNtCancelTimer             = modntdll.NewProc("NtCancelTimer")
	procNtCreateTimer             = modntdll.NewProc("NtCreateTimer")
	procNtOpenEvent               = modntdll.NewProc("NtOpenEvent")
	procNtOpenProcess             = modntdll.NewProc("NtOpenProcess")
	procNtOpenTimer               = modntdll.NewProc("NtOpenTimer")
	procNtQueryInformationProcess = modntdll.NewProc("NtQueryInformationProcess")
	procNtQueryInformationThread  = modntdll.NewProc("NtQueryInformationThread")
	procNtSetInformationThread    = modntdll.NewProc("NtSetInformationThread")
	procNtSetTimer                = modntdll.NewProc("NtSetTimer")
	procNtSetTimerEx              = modntdll.NewProc("NtSetTimerEx")
	procNtTerminateProcess        = modntdll.NewProc("NtTerminateProcess")
	procNtWaitForSingleObject     = modntdll.NewProc("NtWaitForSingleObject")
	procZwCancelTimer             = modntdll.NewProc("ZwCancelTimer")
	procZwCreateTimer             = modntdll.NewProc("ZwCreateTimer")
	procZwOpenEvent               = modntdll.NewProc("ZwOpenEvent")
	procZwOpenProcess             = modntdll.NewProc("ZwOpenProcess")
	procZwOpenTimer               = modntdll.NewProc("ZwOpenTimer")
	procZwQueryInformationProcess = modntdll.NewProc("ZwQueryInformationProcess")
	procZwQueryInformationThread  = modntdll.NewProc("ZwQueryInformationThread")
	procZwSetInformationThread    = modntdll.NewProc("ZwSetInformationThread")
	procZwSetTimer                = modntdll.NewProc("ZwSetTimer")
	procZwSetTimerEx              = modntdll.NewProc("ZwSetTimerEx")
	procZwTerminateProcess        = modntdll.NewProc("ZwTerminateProcess")
	procZwWaitForSingleObject     = modntdll.NewProc("ZwWaitForSingleObject")
)

// NtCancelTimer calls ntdll!NtCancelTimer.
func NtCancelTimer(TimerHandle win32foundation.HANDLE, CurrentState *win32foundation.BOOLEAN) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtCancelTimer.Addr(), uintptr(TimerHandle), uintptr(unsafe.Pointer(CurrentState)))
	return win32foundation.NTSTATUS(r1)
}

// NtCreateTimer calls ntdll!NtCreateTimer.
func NtCreateTimer(TimerHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, TimerType win32systemkernel.TIMER_TYPE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtCreateTimer.Addr(), uintptr(unsafe.Pointer(TimerHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(TimerType))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenEvent calls ntdll!NtOpenEvent.
func NtOpenEvent(EventHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenEvent.Addr(), uintptr(unsafe.Pointer(EventHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenProcess calls ntdll!NtOpenProcess.
func NtOpenProcess(ProcessHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, ClientId *win32systemwindowsprogramming.CLIENT_ID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenProcess.Addr(), uintptr(unsafe.Pointer(ProcessHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(unsafe.Pointer(ClientId)))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenTimer calls ntdll!NtOpenTimer.
func NtOpenTimer(TimerHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenTimer.Addr(), uintptr(unsafe.Pointer(TimerHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryInformationProcess calls ntdll!NtQueryInformationProcess.
func NtQueryInformationProcess(ProcessHandle win32foundation.HANDLE, ProcessInformationClass PROCESSINFOCLASS, ProcessInformation unsafe.Pointer, ProcessInformationLength uint32, ReturnLength *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtQueryInformationProcess.Addr(), uintptr(ProcessHandle), uintptr(ProcessInformationClass), uintptr(unsafe.Pointer(ProcessInformation)), uintptr(ProcessInformationLength), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryInformationThread calls ntdll!NtQueryInformationThread.
func NtQueryInformationThread(ThreadHandle win32foundation.HANDLE, ThreadInformationClass THREADINFOCLASS, ThreadInformation unsafe.Pointer, ThreadInformationLength uint32, ReturnLength *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtQueryInformationThread.Addr(), uintptr(ThreadHandle), uintptr(ThreadInformationClass), uintptr(unsafe.Pointer(ThreadInformation)), uintptr(ThreadInformationLength), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtSetInformationThread calls ntdll!NtSetInformationThread.
func NtSetInformationThread(ThreadHandle win32foundation.HANDLE, ThreadInformationClass THREADINFOCLASS, ThreadInformation []byte) win32foundation.NTSTATUS {
	var _ThreadInformation *byte
	if len(ThreadInformation) > 0 {
		_ThreadInformation = &ThreadInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtSetInformationThread.Addr(), uintptr(ThreadHandle), uintptr(ThreadInformationClass), uintptr(unsafe.Pointer(_ThreadInformation)), uintptr(len(ThreadInformation)))
	return win32foundation.NTSTATUS(r1)
}

// NtSetTimer calls ntdll!NtSetTimer.
func NtSetTimer(TimerHandle win32foundation.HANDLE, DueTime *int64, TimerApcRoutine systemsystemservices.PTIMER_APC_ROUTINE, TimerContext unsafe.Pointer, ResumeTimer win32foundation.BOOLEAN, Period int32, PreviousState *win32foundation.BOOLEAN) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtSetTimer.Addr(), uintptr(TimerHandle), uintptr(unsafe.Pointer(DueTime)), uintptr(TimerApcRoutine), uintptr(unsafe.Pointer(TimerContext)), uintptr(ResumeTimer), uintptr(Period), uintptr(unsafe.Pointer(PreviousState)))
	return win32foundation.NTSTATUS(r1)
}

// NtSetTimerEx calls ntdll!NtSetTimerEx.
func NtSetTimerEx(TimerHandle win32foundation.HANDLE, TimerSetInformationClass TIMER_SET_INFORMATION_CLASS, TimerSetInformation []byte) win32foundation.NTSTATUS {
	var _TimerSetInformation *byte
	if len(TimerSetInformation) > 0 {
		_TimerSetInformation = &TimerSetInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtSetTimerEx.Addr(), uintptr(TimerHandle), uintptr(TimerSetInformationClass), uintptr(unsafe.Pointer(_TimerSetInformation)), uintptr(len(TimerSetInformation)))
	return win32foundation.NTSTATUS(r1)
}

// NtTerminateProcess calls ntdll!NtTerminateProcess.
func NtTerminateProcess(ProcessHandle win32foundation.HANDLE, ExitStatus win32foundation.NTSTATUS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtTerminateProcess.Addr(), uintptr(ProcessHandle), uintptr(ExitStatus))
	return win32foundation.NTSTATUS(r1)
}

// NtWaitForSingleObject calls ntdll!NtWaitForSingleObject.
func NtWaitForSingleObject(Handle win32foundation.HANDLE, Alertable win32foundation.BOOLEAN, Timeout *int64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtWaitForSingleObject.Addr(), uintptr(Handle), uintptr(Alertable), uintptr(unsafe.Pointer(Timeout)))
	return win32foundation.NTSTATUS(r1)
}

// ZwCancelTimer calls ntdll!ZwCancelTimer.
func ZwCancelTimer(TimerHandle win32foundation.HANDLE, CurrentState *win32foundation.BOOLEAN) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwCancelTimer.Addr(), uintptr(TimerHandle), uintptr(unsafe.Pointer(CurrentState)))
	return win32foundation.NTSTATUS(r1)
}

// ZwCreateTimer calls ntdll!ZwCreateTimer.
func ZwCreateTimer(TimerHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, TimerType win32systemkernel.TIMER_TYPE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwCreateTimer.Addr(), uintptr(unsafe.Pointer(TimerHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(TimerType))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenEvent calls ntdll!ZwOpenEvent.
func ZwOpenEvent(EventHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenEvent.Addr(), uintptr(unsafe.Pointer(EventHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenProcess calls ntdll!ZwOpenProcess.
func ZwOpenProcess(ProcessHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, ClientId *win32systemwindowsprogramming.CLIENT_ID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenProcess.Addr(), uintptr(unsafe.Pointer(ProcessHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(unsafe.Pointer(ClientId)))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenTimer calls ntdll!ZwOpenTimer.
func ZwOpenTimer(TimerHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenTimer.Addr(), uintptr(unsafe.Pointer(TimerHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQueryInformationProcess calls ntdll!ZwQueryInformationProcess.
func ZwQueryInformationProcess(ProcessHandle win32foundation.HANDLE, ProcessInformationClass PROCESSINFOCLASS, ProcessInformation unsafe.Pointer, ProcessInformationLength uint32, ReturnLength *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwQueryInformationProcess.Addr(), uintptr(ProcessHandle), uintptr(ProcessInformationClass), uintptr(unsafe.Pointer(ProcessInformation)), uintptr(ProcessInformationLength), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQueryInformationThread calls ntdll!ZwQueryInformationThread.
func ZwQueryInformationThread(ThreadHandle win32foundation.HANDLE, ThreadInformationClass THREADINFOCLASS, ThreadInformation unsafe.Pointer, ThreadInformationLength uint32, ReturnLength *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwQueryInformationThread.Addr(), uintptr(ThreadHandle), uintptr(ThreadInformationClass), uintptr(unsafe.Pointer(ThreadInformation)), uintptr(ThreadInformationLength), uintptr(unsafe.Pointer(ReturnLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwSetInformationThread calls ntdll!ZwSetInformationThread.
func ZwSetInformationThread(ThreadHandle win32foundation.HANDLE, ThreadInformationClass THREADINFOCLASS, ThreadInformation []byte) win32foundation.NTSTATUS {
	var _ThreadInformation *byte
	if len(ThreadInformation) > 0 {
		_ThreadInformation = &ThreadInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwSetInformationThread.Addr(), uintptr(ThreadHandle), uintptr(ThreadInformationClass), uintptr(unsafe.Pointer(_ThreadInformation)), uintptr(len(ThreadInformation)))
	return win32foundation.NTSTATUS(r1)
}

// ZwSetTimer calls ntdll!ZwSetTimer.
func ZwSetTimer(TimerHandle win32foundation.HANDLE, DueTime *int64, TimerApcRoutine systemsystemservices.PTIMER_APC_ROUTINE, TimerContext unsafe.Pointer, ResumeTimer win32foundation.BOOLEAN, Period int32, PreviousState *win32foundation.BOOLEAN) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwSetTimer.Addr(), uintptr(TimerHandle), uintptr(unsafe.Pointer(DueTime)), uintptr(TimerApcRoutine), uintptr(unsafe.Pointer(TimerContext)), uintptr(ResumeTimer), uintptr(Period), uintptr(unsafe.Pointer(PreviousState)))
	return win32foundation.NTSTATUS(r1)
}

// ZwSetTimerEx calls ntdll!ZwSetTimerEx.
func ZwSetTimerEx(TimerHandle win32foundation.HANDLE, TimerSetInformationClass TIMER_SET_INFORMATION_CLASS, TimerSetInformation []byte) win32foundation.NTSTATUS {
	var _TimerSetInformation *byte
	if len(TimerSetInformation) > 0 {
		_TimerSetInformation = &TimerSetInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwSetTimerEx.Addr(), uintptr(TimerHandle), uintptr(TimerSetInformationClass), uintptr(unsafe.Pointer(_TimerSetInformation)), uintptr(len(TimerSetInformation)))
	return win32foundation.NTSTATUS(r1)
}

// ZwTerminateProcess calls ntdll!ZwTerminateProcess.
func ZwTerminateProcess(ProcessHandle win32foundation.HANDLE, ExitStatus win32foundation.NTSTATUS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwTerminateProcess.Addr(), uintptr(ProcessHandle), uintptr(ExitStatus))
	return win32foundation.NTSTATUS(r1)
}

// ZwWaitForSingleObject calls ntdll!ZwWaitForSingleObject.
func ZwWaitForSingleObject(Handle win32foundation.HANDLE, Alertable win32foundation.BOOLEAN, Timeout *int64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwWaitForSingleObject.Addr(), uintptr(Handle), uintptr(Alertable), uintptr(unsafe.Pointer(Timeout)))
	return win32foundation.NTSTATUS(r1)
}
