// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package humaninterfacedevice binds the Windows.Wdk.Devices.HumanInterfaceDevice API surface.
package humaninterfacedevice
