// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package humaninterfacedevice

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

var (
	modVhfUm = win32.NewDLL("VhfUm.DLL")
)

var (
	procVhfAsyncOperationComplete = modVhfUm.NewProc("VhfAsyncOperationComplete")
	procVhfCreate                 = modVhfUm.NewProc("VhfCreate")
	procVhfDelete                 = modVhfUm.NewProc("VhfDelete")
	procVhfReadReportSubmit       = modVhfUm.NewProc("VhfReadReportSubmit")
	procVhfStart                  = modVhfUm.NewProc("VhfStart")
)

// VhfAsyncOperationComplete calls VhfUm.DLL!VhfAsyncOperationComplete.
func VhfAsyncOperationComplete(VhfOperationHandle unsafe.Pointer, CompletionStatus win32foundation.NTSTATUS) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procVhfAsyncOperationComplete.Addr(), uintptr(unsafe.Pointer(VhfOperationHandle)), uintptr(CompletionStatus))
	return win32foundation.NTSTATUS(r1)
}

// VhfCreate calls VhfUm.DLL!VhfCreate.
func VhfCreate(VhfConfig *VHF_CONFIG, VhfHandle *unsafe.Pointer) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procVhfCreate.Addr(), uintptr(unsafe.Pointer(VhfConfig)), uintptr(unsafe.Pointer(VhfHandle)))
	return win32foundation.NTSTATUS(r1)
}

// VhfDelete calls VhfUm.DLL!VhfDelete.
func VhfDelete(VhfHandle unsafe.Pointer, Wait win32foundation.BOOLEAN) {
	syscall.SyscallN(procVhfDelete.Addr(), uintptr(unsafe.Pointer(VhfHandle)), uintptr(Wait))
}

// VhfReadReportSubmit calls VhfUm.DLL!VhfReadReportSubmit.
func VhfReadReportSubmit(VhfHandle unsafe.Pointer, HidTransferPacket *HID_XFER_PACKET) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procVhfReadReportSubmit.Addr(), uintptr(unsafe.Pointer(VhfHandle)), uintptr(unsafe.Pointer(HidTransferPacket)))
	return win32foundation.NTSTATUS(r1)
}

// VhfStart calls VhfUm.DLL!VhfStart.
func VhfStart(VhfHandle unsafe.Pointer) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procVhfStart.Addr(), uintptr(unsafe.Pointer(VhfHandle)))
	return win32foundation.NTSTATUS(r1)
}
