// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

// Package systemservices binds the Windows.Wdk.System.SystemServices API surface.
package systemservices
