// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package registry

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/foundation"
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32systemio "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/io"
)

var (
	modntdll = win32.NewDLL("ntdll.dll")
)

var (
	procNtCommitRegistryTransaction   = modntdll.NewProc("NtCommitRegistryTransaction")
	procNtCreateKey                   = modntdll.NewProc("NtCreateKey")
	procNtCreateKeyTransacted         = modntdll.NewProc("NtCreateKeyTransacted")
	procNtCreateRegistryTransaction   = modntdll.NewProc("NtCreateRegistryTransaction")
	procNtDeleteKey                   = modntdll.NewProc("NtDeleteKey")
	procNtDeleteValueKey              = modntdll.NewProc("NtDeleteValueKey")
	procNtEnumerateKey                = modntdll.NewProc("NtEnumerateKey")
	procNtEnumerateValueKey           = modntdll.NewProc("NtEnumerateValueKey")
	procNtFlushKey                    = modntdll.NewProc("NtFlushKey")
	procNtNotifyChangeMultipleKeys    = modntdll.NewProc("NtNotifyChangeMultipleKeys")
	procNtOpenKey                     = modntdll.NewProc("NtOpenKey")
	procNtOpenKeyEx                   = modntdll.NewProc("NtOpenKeyEx")
	procNtOpenKeyTransacted           = modntdll.NewProc("NtOpenKeyTransacted")
	procNtOpenKeyTransactedEx         = modntdll.NewProc("NtOpenKeyTransactedEx")
	procNtOpenRegistryTransaction     = modntdll.NewProc("NtOpenRegistryTransaction")
	procNtQueryKey                    = modntdll.NewProc("NtQueryKey")
	procNtQueryMultipleValueKey       = modntdll.NewProc("NtQueryMultipleValueKey")
	procNtQueryValueKey               = modntdll.NewProc("NtQueryValueKey")
	procNtRenameKey                   = modntdll.NewProc("NtRenameKey")
	procNtRestoreKey                  = modntdll.NewProc("NtRestoreKey")
	procNtRollbackRegistryTransaction = modntdll.NewProc("NtRollbackRegistryTransaction")
	procNtSaveKey                     = modntdll.NewProc("NtSaveKey")
	procNtSaveKeyEx                   = modntdll.NewProc("NtSaveKeyEx")
	procNtSetInformationKey           = modntdll.NewProc("NtSetInformationKey")
	procNtSetValueKey                 = modntdll.NewProc("NtSetValueKey")
	procZwCommitRegistryTransaction   = modntdll.NewProc("ZwCommitRegistryTransaction")
	procZwCreateKey                   = modntdll.NewProc("ZwCreateKey")
	procZwCreateKeyTransacted         = modntdll.NewProc("ZwCreateKeyTransacted")
	procZwCreateRegistryTransaction   = modntdll.NewProc("ZwCreateRegistryTransaction")
	procZwDeleteKey                   = modntdll.NewProc("ZwDeleteKey")
	procZwDeleteValueKey              = modntdll.NewProc("ZwDeleteValueKey")
	procZwEnumerateKey                = modntdll.NewProc("ZwEnumerateKey")
	procZwEnumerateValueKey           = modntdll.NewProc("ZwEnumerateValueKey")
	procZwFlushKey                    = modntdll.NewProc("ZwFlushKey")
	procZwNotifyChangeMultipleKeys    = modntdll.NewProc("ZwNotifyChangeMultipleKeys")
	procZwOpenKey                     = modntdll.NewProc("ZwOpenKey")
	procZwOpenKeyEx                   = modntdll.NewProc("ZwOpenKeyEx")
	procZwOpenKeyTransacted           = modntdll.NewProc("ZwOpenKeyTransacted")
	procZwOpenKeyTransactedEx         = modntdll.NewProc("ZwOpenKeyTransactedEx")
	procZwOpenRegistryTransaction     = modntdll.NewProc("ZwOpenRegistryTransaction")
	procZwQueryKey                    = modntdll.NewProc("ZwQueryKey")
	procZwQueryMultipleValueKey       = modntdll.NewProc("ZwQueryMultipleValueKey")
	procZwQueryValueKey               = modntdll.NewProc("ZwQueryValueKey")
	procZwRenameKey                   = modntdll.NewProc("ZwRenameKey")
	procZwRestoreKey                  = modntdll.NewProc("ZwRestoreKey")
	procZwRollbackRegistryTransaction = modntdll.NewProc("ZwRollbackRegistryTransaction")
	procZwSaveKey                     = modntdll.NewProc("ZwSaveKey")
	procZwSaveKeyEx                   = modntdll.NewProc("ZwSaveKeyEx")
	procZwSetInformationKey           = modntdll.NewProc("ZwSetInformationKey")
	procZwSetValueKey                 = modntdll.NewProc("ZwSetValueKey")
)

// NtCommitRegistryTransaction calls ntdll!NtCommitRegistryTransaction.
func NtCommitRegistryTransaction(TransactionHandle win32foundation.HANDLE, Flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtCommitRegistryTransaction.Addr(), uintptr(TransactionHandle), uintptr(Flags))
	return win32foundation.NTSTATUS(r1)
}

// NtCreateKey calls ntdll!NtCreateKey.
func NtCreateKey(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, Class *win32foundation.UNICODE_STRING, CreateOptions uint32, Disposition *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtCreateKey.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), 0, uintptr(unsafe.Pointer(Class)), uintptr(CreateOptions), uintptr(unsafe.Pointer(Disposition)))
	return win32foundation.NTSTATUS(r1)
}

// NtCreateKeyTransacted calls ntdll!NtCreateKeyTransacted.
func NtCreateKeyTransacted(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, Class *win32foundation.UNICODE_STRING, CreateOptions uint32, TransactionHandle win32foundation.HANDLE, Disposition *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtCreateKeyTransacted.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), 0, uintptr(unsafe.Pointer(Class)), uintptr(CreateOptions), uintptr(TransactionHandle), uintptr(unsafe.Pointer(Disposition)))
	return win32foundation.NTSTATUS(r1)
}

// NtCreateRegistryTransaction calls ntdll!NtCreateRegistryTransaction.
func NtCreateRegistryTransaction(TransactionHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, CreateOptions uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtCreateRegistryTransaction.Addr(), uintptr(unsafe.Pointer(TransactionHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(CreateOptions))
	return win32foundation.NTSTATUS(r1)
}

// NtDeleteKey calls ntdll!NtDeleteKey.
func NtDeleteKey(KeyHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtDeleteKey.Addr(), uintptr(KeyHandle))
	return win32foundation.NTSTATUS(r1)
}

// NtDeleteValueKey calls ntdll!NtDeleteValueKey.
func NtDeleteValueKey(KeyHandle win32foundation.HANDLE, ValueName *win32foundation.UNICODE_STRING) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtDeleteValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(ValueName)))
	return win32foundation.NTSTATUS(r1)
}

// NtEnumerateKey calls ntdll!NtEnumerateKey.
func NtEnumerateKey(KeyHandle win32foundation.HANDLE, Index uint32, KeyInformationClass KEY_INFORMATION_CLASS, KeyInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyInformation *byte
	if len(KeyInformation) > 0 {
		_KeyInformation = &KeyInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtEnumerateKey.Addr(), uintptr(KeyHandle), uintptr(Index), uintptr(KeyInformationClass), uintptr(unsafe.Pointer(_KeyInformation)), uintptr(len(KeyInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtEnumerateValueKey calls ntdll!NtEnumerateValueKey.
func NtEnumerateValueKey(KeyHandle win32foundation.HANDLE, Index uint32, KeyValueInformationClass KEY_VALUE_INFORMATION_CLASS, KeyValueInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyValueInformation *byte
	if len(KeyValueInformation) > 0 {
		_KeyValueInformation = &KeyValueInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtEnumerateValueKey.Addr(), uintptr(KeyHandle), uintptr(Index), uintptr(KeyValueInformationClass), uintptr(unsafe.Pointer(_KeyValueInformation)), uintptr(len(KeyValueInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtFlushKey calls ntdll!NtFlushKey.
func NtFlushKey(KeyHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtFlushKey.Addr(), uintptr(KeyHandle))
	return win32foundation.NTSTATUS(r1)
}

// NtNotifyChangeMultipleKeys calls ntdll!NtNotifyChangeMultipleKeys.
func NtNotifyChangeMultipleKeys(MasterKeyHandle win32foundation.HANDLE, SubordinateObjects []foundation.OBJECT_ATTRIBUTES, Event win32foundation.HANDLE, ApcRoutine win32systemio.PIO_APC_ROUTINE, ApcContext unsafe.Pointer, IoStatusBlock *win32systemio.IO_STATUS_BLOCK, CompletionFilter uint32, WatchTree win32foundation.BOOLEAN, Buffer []byte, Asynchronous win32foundation.BOOLEAN) win32foundation.NTSTATUS {
	var _SubordinateObjects *foundation.OBJECT_ATTRIBUTES
	if len(SubordinateObjects) > 0 {
		_SubordinateObjects = &SubordinateObjects[0]
	}
	var _Buffer *byte
	if len(Buffer) > 0 {
		_Buffer = &Buffer[0]
	}
	r1, _, _ := syscall.SyscallN(procNtNotifyChangeMultipleKeys.Addr(), uintptr(MasterKeyHandle), uintptr(len(SubordinateObjects)), uintptr(unsafe.Pointer(_SubordinateObjects)), uintptr(Event), uintptr(ApcRoutine), uintptr(unsafe.Pointer(ApcContext)), uintptr(unsafe.Pointer(IoStatusBlock)), uintptr(CompletionFilter), uintptr(WatchTree), uintptr(unsafe.Pointer(_Buffer)), uintptr(len(Buffer)), uintptr(Asynchronous))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenKey calls ntdll!NtOpenKey.
func NtOpenKey(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenKey.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenKeyEx calls ntdll!NtOpenKeyEx.
func NtOpenKeyEx(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, OpenOptions uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenKeyEx.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(OpenOptions))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenKeyTransacted calls ntdll!NtOpenKeyTransacted.
func NtOpenKeyTransacted(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, TransactionHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenKeyTransacted.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(TransactionHandle))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenKeyTransactedEx calls ntdll!NtOpenKeyTransactedEx.
func NtOpenKeyTransactedEx(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, OpenOptions uint32, TransactionHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenKeyTransactedEx.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(OpenOptions), uintptr(TransactionHandle))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenRegistryTransaction calls ntdll!NtOpenRegistryTransaction.
func NtOpenRegistryTransaction(TransactionHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenRegistryTransaction.Addr(), uintptr(unsafe.Pointer(TransactionHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryKey calls ntdll!NtQueryKey.
func NtQueryKey(KeyHandle win32foundation.HANDLE, KeyInformationClass KEY_INFORMATION_CLASS, KeyInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyInformation *byte
	if len(KeyInformation) > 0 {
		_KeyInformation = &KeyInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtQueryKey.Addr(), uintptr(KeyHandle), uintptr(KeyInformationClass), uintptr(unsafe.Pointer(_KeyInformation)), uintptr(len(KeyInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryMultipleValueKey calls ntdll!NtQueryMultipleValueKey.
func NtQueryMultipleValueKey(KeyHandle win32foundation.HANDLE, ValueEntries []KEY_VALUE_ENTRY, ValueBuffer unsafe.Pointer, BufferLength *uint32, RequiredBufferLength *uint32) win32foundation.NTSTATUS {
	var _ValueEntries *KEY_VALUE_ENTRY
	if len(ValueEntries) > 0 {
		_ValueEntries = &ValueEntries[0]
	}
	r1, _, _ := syscall.SyscallN(procNtQueryMultipleValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(_ValueEntries)), uintptr(len(ValueEntries)), uintptr(unsafe.Pointer(ValueBuffer)), uintptr(unsafe.Pointer(BufferLength)), uintptr(unsafe.Pointer(RequiredBufferLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtQueryValueKey calls ntdll!NtQueryValueKey.
func NtQueryValueKey(KeyHandle win32foundation.HANDLE, ValueName *win32foundation.UNICODE_STRING, KeyValueInformationClass KEY_VALUE_INFORMATION_CLASS, KeyValueInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyValueInformation *byte
	if len(KeyValueInformation) > 0 {
		_KeyValueInformation = &KeyValueInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtQueryValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(ValueName)), uintptr(KeyValueInformationClass), uintptr(unsafe.Pointer(_KeyValueInformation)), uintptr(len(KeyValueInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// NtRenameKey calls ntdll!NtRenameKey.
func NtRenameKey(KeyHandle win32foundation.HANDLE, NewName *win32foundation.UNICODE_STRING) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtRenameKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(NewName)))
	return win32foundation.NTSTATUS(r1)
}

// NtRestoreKey calls ntdll!NtRestoreKey.
func NtRestoreKey(KeyHandle win32foundation.HANDLE, FileHandle win32foundation.HANDLE, Flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtRestoreKey.Addr(), uintptr(KeyHandle), uintptr(FileHandle), uintptr(Flags))
	return win32foundation.NTSTATUS(r1)
}

// NtRollbackRegistryTransaction calls ntdll!NtRollbackRegistryTransaction.
func NtRollbackRegistryTransaction(TransactionHandle win32foundation.HANDLE, Flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtRollbackRegistryTransaction.Addr(), uintptr(TransactionHandle), uintptr(Flags))
	return win32foundation.NTSTATUS(r1)
}

// NtSaveKey calls ntdll!NtSaveKey.
func NtSaveKey(KeyHandle win32foundation.HANDLE, FileHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtSaveKey.Addr(), uintptr(KeyHandle), uintptr(FileHandle))
	return win32foundation.NTSTATUS(r1)
}

// NtSaveKeyEx calls ntdll!NtSaveKeyEx.
func NtSaveKeyEx(KeyHandle win32foundation.HANDLE, FileHandle win32foundation.HANDLE, Format uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtSaveKeyEx.Addr(), uintptr(KeyHandle), uintptr(FileHandle), uintptr(Format))
	return win32foundation.NTSTATUS(r1)
}

// NtSetInformationKey calls ntdll!NtSetInformationKey.
func NtSetInformationKey(KeyHandle win32foundation.HANDLE, KeySetInformationClass KEY_SET_INFORMATION_CLASS, KeySetInformation []byte) win32foundation.NTSTATUS {
	var _KeySetInformation *byte
	if len(KeySetInformation) > 0 {
		_KeySetInformation = &KeySetInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procNtSetInformationKey.Addr(), uintptr(KeyHandle), uintptr(KeySetInformationClass), uintptr(unsafe.Pointer(_KeySetInformation)), uintptr(len(KeySetInformation)))
	return win32foundation.NTSTATUS(r1)
}

// NtSetValueKey calls ntdll!NtSetValueKey.
func NtSetValueKey(KeyHandle win32foundation.HANDLE, ValueName *win32foundation.UNICODE_STRING, TitleIndex uint32, Type uint32, Data []byte) win32foundation.NTSTATUS {
	var _Data *byte
	if len(Data) > 0 {
		_Data = &Data[0]
	}
	r1, _, _ := syscall.SyscallN(procNtSetValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(ValueName)), uintptr(TitleIndex), uintptr(Type), uintptr(unsafe.Pointer(_Data)), uintptr(len(Data)))
	return win32foundation.NTSTATUS(r1)
}

// ZwCommitRegistryTransaction calls ntdll!ZwCommitRegistryTransaction.
func ZwCommitRegistryTransaction(TransactionHandle win32foundation.HANDLE, Flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwCommitRegistryTransaction.Addr(), uintptr(TransactionHandle), uintptr(Flags))
	return win32foundation.NTSTATUS(r1)
}

// ZwCreateKey calls ntdll!ZwCreateKey.
func ZwCreateKey(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, Class *win32foundation.UNICODE_STRING, CreateOptions uint32, Disposition *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwCreateKey.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), 0, uintptr(unsafe.Pointer(Class)), uintptr(CreateOptions), uintptr(unsafe.Pointer(Disposition)))
	return win32foundation.NTSTATUS(r1)
}

// ZwCreateKeyTransacted calls ntdll!ZwCreateKeyTransacted.
func ZwCreateKeyTransacted(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, Class *win32foundation.UNICODE_STRING, CreateOptions uint32, TransactionHandle win32foundation.HANDLE, Disposition *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwCreateKeyTransacted.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), 0, uintptr(unsafe.Pointer(Class)), uintptr(CreateOptions), uintptr(TransactionHandle), uintptr(unsafe.Pointer(Disposition)))
	return win32foundation.NTSTATUS(r1)
}

// ZwCreateRegistryTransaction calls ntdll!ZwCreateRegistryTransaction.
func ZwCreateRegistryTransaction(TransactionHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, CreateOptions uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwCreateRegistryTransaction.Addr(), uintptr(unsafe.Pointer(TransactionHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(CreateOptions))
	return win32foundation.NTSTATUS(r1)
}

// ZwDeleteKey calls ntdll!ZwDeleteKey.
func ZwDeleteKey(KeyHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwDeleteKey.Addr(), uintptr(KeyHandle))
	return win32foundation.NTSTATUS(r1)
}

// ZwDeleteValueKey calls ntdll!ZwDeleteValueKey.
func ZwDeleteValueKey(KeyHandle win32foundation.HANDLE, ValueName *win32foundation.UNICODE_STRING) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwDeleteValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(ValueName)))
	return win32foundation.NTSTATUS(r1)
}

// ZwEnumerateKey calls ntdll!ZwEnumerateKey.
func ZwEnumerateKey(KeyHandle win32foundation.HANDLE, Index uint32, KeyInformationClass KEY_INFORMATION_CLASS, KeyInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyInformation *byte
	if len(KeyInformation) > 0 {
		_KeyInformation = &KeyInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwEnumerateKey.Addr(), uintptr(KeyHandle), uintptr(Index), uintptr(KeyInformationClass), uintptr(unsafe.Pointer(_KeyInformation)), uintptr(len(KeyInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwEnumerateValueKey calls ntdll!ZwEnumerateValueKey.
func ZwEnumerateValueKey(KeyHandle win32foundation.HANDLE, Index uint32, KeyValueInformationClass KEY_VALUE_INFORMATION_CLASS, KeyValueInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyValueInformation *byte
	if len(KeyValueInformation) > 0 {
		_KeyValueInformation = &KeyValueInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwEnumerateValueKey.Addr(), uintptr(KeyHandle), uintptr(Index), uintptr(KeyValueInformationClass), uintptr(unsafe.Pointer(_KeyValueInformation)), uintptr(len(KeyValueInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwFlushKey calls ntdll!ZwFlushKey.
func ZwFlushKey(KeyHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwFlushKey.Addr(), uintptr(KeyHandle))
	return win32foundation.NTSTATUS(r1)
}

// ZwNotifyChangeMultipleKeys calls ntdll!ZwNotifyChangeMultipleKeys.
func ZwNotifyChangeMultipleKeys(MasterKeyHandle win32foundation.HANDLE, SubordinateObjects []foundation.OBJECT_ATTRIBUTES, Event win32foundation.HANDLE, ApcRoutine win32systemio.PIO_APC_ROUTINE, ApcContext unsafe.Pointer, IoStatusBlock *win32systemio.IO_STATUS_BLOCK, CompletionFilter uint32, WatchTree win32foundation.BOOLEAN, Buffer []byte, Asynchronous win32foundation.BOOLEAN) win32foundation.NTSTATUS {
	var _SubordinateObjects *foundation.OBJECT_ATTRIBUTES
	if len(SubordinateObjects) > 0 {
		_SubordinateObjects = &SubordinateObjects[0]
	}
	var _Buffer *byte
	if len(Buffer) > 0 {
		_Buffer = &Buffer[0]
	}
	r1, _, _ := syscall.SyscallN(procZwNotifyChangeMultipleKeys.Addr(), uintptr(MasterKeyHandle), uintptr(len(SubordinateObjects)), uintptr(unsafe.Pointer(_SubordinateObjects)), uintptr(Event), uintptr(ApcRoutine), uintptr(unsafe.Pointer(ApcContext)), uintptr(unsafe.Pointer(IoStatusBlock)), uintptr(CompletionFilter), uintptr(WatchTree), uintptr(unsafe.Pointer(_Buffer)), uintptr(len(Buffer)), uintptr(Asynchronous))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenKey calls ntdll!ZwOpenKey.
func ZwOpenKey(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenKey.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenKeyEx calls ntdll!ZwOpenKeyEx.
func ZwOpenKeyEx(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, OpenOptions uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenKeyEx.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(OpenOptions))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenKeyTransacted calls ntdll!ZwOpenKeyTransacted.
func ZwOpenKeyTransacted(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, TransactionHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenKeyTransacted.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(TransactionHandle))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenKeyTransactedEx calls ntdll!ZwOpenKeyTransactedEx.
func ZwOpenKeyTransactedEx(KeyHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES, OpenOptions uint32, TransactionHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenKeyTransactedEx.Addr(), uintptr(unsafe.Pointer(KeyHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)), uintptr(OpenOptions), uintptr(TransactionHandle))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenRegistryTransaction calls ntdll!ZwOpenRegistryTransaction.
func ZwOpenRegistryTransaction(TransactionHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenRegistryTransaction.Addr(), uintptr(unsafe.Pointer(TransactionHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQueryKey calls ntdll!ZwQueryKey.
func ZwQueryKey(KeyHandle win32foundation.HANDLE, KeyInformationClass KEY_INFORMATION_CLASS, KeyInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyInformation *byte
	if len(KeyInformation) > 0 {
		_KeyInformation = &KeyInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwQueryKey.Addr(), uintptr(KeyHandle), uintptr(KeyInformationClass), uintptr(unsafe.Pointer(_KeyInformation)), uintptr(len(KeyInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQueryMultipleValueKey calls ntdll!ZwQueryMultipleValueKey.
func ZwQueryMultipleValueKey(KeyHandle win32foundation.HANDLE, ValueEntries []KEY_VALUE_ENTRY, ValueBuffer unsafe.Pointer, BufferLength *uint32, RequiredBufferLength *uint32) win32foundation.NTSTATUS {
	var _ValueEntries *KEY_VALUE_ENTRY
	if len(ValueEntries) > 0 {
		_ValueEntries = &ValueEntries[0]
	}
	r1, _, _ := syscall.SyscallN(procZwQueryMultipleValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(_ValueEntries)), uintptr(len(ValueEntries)), uintptr(unsafe.Pointer(ValueBuffer)), uintptr(unsafe.Pointer(BufferLength)), uintptr(unsafe.Pointer(RequiredBufferLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwQueryValueKey calls ntdll!ZwQueryValueKey.
func ZwQueryValueKey(KeyHandle win32foundation.HANDLE, ValueName *win32foundation.UNICODE_STRING, KeyValueInformationClass KEY_VALUE_INFORMATION_CLASS, KeyValueInformation []byte, ResultLength *uint32) win32foundation.NTSTATUS {
	var _KeyValueInformation *byte
	if len(KeyValueInformation) > 0 {
		_KeyValueInformation = &KeyValueInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwQueryValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(ValueName)), uintptr(KeyValueInformationClass), uintptr(unsafe.Pointer(_KeyValueInformation)), uintptr(len(KeyValueInformation)), uintptr(unsafe.Pointer(ResultLength)))
	return win32foundation.NTSTATUS(r1)
}

// ZwRenameKey calls ntdll!ZwRenameKey.
func ZwRenameKey(KeyHandle win32foundation.HANDLE, NewName *win32foundation.UNICODE_STRING) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwRenameKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(NewName)))
	return win32foundation.NTSTATUS(r1)
}

// ZwRestoreKey calls ntdll!ZwRestoreKey.
func ZwRestoreKey(KeyHandle win32foundation.HANDLE, FileHandle win32foundation.HANDLE, Flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwRestoreKey.Addr(), uintptr(KeyHandle), uintptr(FileHandle), uintptr(Flags))
	return win32foundation.NTSTATUS(r1)
}

// ZwRollbackRegistryTransaction calls ntdll!ZwRollbackRegistryTransaction.
func ZwRollbackRegistryTransaction(TransactionHandle win32foundation.HANDLE, Flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwRollbackRegistryTransaction.Addr(), uintptr(TransactionHandle), uintptr(Flags))
	return win32foundation.NTSTATUS(r1)
}

// ZwSaveKey calls ntdll!ZwSaveKey.
func ZwSaveKey(KeyHandle win32foundation.HANDLE, FileHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwSaveKey.Addr(), uintptr(KeyHandle), uintptr(FileHandle))
	return win32foundation.NTSTATUS(r1)
}

// ZwSaveKeyEx calls ntdll!ZwSaveKeyEx.
func ZwSaveKeyEx(KeyHandle win32foundation.HANDLE, FileHandle win32foundation.HANDLE, Format uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwSaveKeyEx.Addr(), uintptr(KeyHandle), uintptr(FileHandle), uintptr(Format))
	return win32foundation.NTSTATUS(r1)
}

// ZwSetInformationKey calls ntdll!ZwSetInformationKey.
func ZwSetInformationKey(KeyHandle win32foundation.HANDLE, KeySetInformationClass KEY_SET_INFORMATION_CLASS, KeySetInformation []byte) win32foundation.NTSTATUS {
	var _KeySetInformation *byte
	if len(KeySetInformation) > 0 {
		_KeySetInformation = &KeySetInformation[0]
	}
	r1, _, _ := syscall.SyscallN(procZwSetInformationKey.Addr(), uintptr(KeyHandle), uintptr(KeySetInformationClass), uintptr(unsafe.Pointer(_KeySetInformation)), uintptr(len(KeySetInformation)))
	return win32foundation.NTSTATUS(r1)
}

// ZwSetValueKey calls ntdll!ZwSetValueKey.
func ZwSetValueKey(KeyHandle win32foundation.HANDLE, ValueName *win32foundation.UNICODE_STRING, TitleIndex uint32, Type uint32, Data []byte) win32foundation.NTSTATUS {
	var _Data *byte
	if len(Data) > 0 {
		_Data = &Data[0]
	}
	r1, _, _ := syscall.SyscallN(procZwSetValueKey.Addr(), uintptr(KeyHandle), uintptr(unsafe.Pointer(ValueName)), uintptr(TitleIndex), uintptr(Type), uintptr(unsafe.Pointer(_Data)), uintptr(len(Data)))
	return win32foundation.NTSTATUS(r1)
}
