// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package registry

import (
	"fmt"
)

type KEY_INFORMATION_CLASS int32

const (
	KeyBasicInformation          KEY_INFORMATION_CLASS = 0
	KeyNodeInformation           KEY_INFORMATION_CLASS = 1
	KeyFullInformation           KEY_INFORMATION_CLASS = 2
	KeyNameInformation           KEY_INFORMATION_CLASS = 3
	KeyCachedInformation         KEY_INFORMATION_CLASS = 4
	KeyFlagsInformation          KEY_INFORMATION_CLASS = 5
	KeyVirtualizationInformation KEY_INFORMATION_CLASS = 6
	KeyHandleTagsInformation     KEY_INFORMATION_CLASS = 7
	KeyTrustInformation          KEY_INFORMATION_CLASS = 8
	KeyLayerInformation          KEY_INFORMATION_CLASS = 9
	MaxKeyInfoClass              KEY_INFORMATION_CLASS = 10
)

// String returns the KEY_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e KEY_INFORMATION_CLASS) String() string {
	switch e {
	case KeyBasicInformation:
		return "KeyBasicInformation"
	case KeyNodeInformation:
		return "KeyNodeInformation"
	case KeyFullInformation:
		return "KeyFullInformation"
	case KeyNameInformation:
		return "KeyNameInformation"
	case KeyCachedInformation:
		return "KeyCachedInformation"
	case KeyFlagsInformation:
		return "KeyFlagsInformation"
	case KeyVirtualizationInformation:
		return "KeyVirtualizationInformation"
	case KeyHandleTagsInformation:
		return "KeyHandleTagsInformation"
	case KeyTrustInformation:
		return "KeyTrustInformation"
	case KeyLayerInformation:
		return "KeyLayerInformation"
	case MaxKeyInfoClass:
		return "MaxKeyInfoClass"
	default:
		return fmt.Sprintf("KEY_INFORMATION_CLASS(%d)", int32(e))
	}
}

type KEY_SET_INFORMATION_CLASS int32

const (
	KeyWriteTimeInformation         KEY_SET_INFORMATION_CLASS = 0
	KeyWow64FlagsInformation        KEY_SET_INFORMATION_CLASS = 1
	KeyControlFlagsInformation      KEY_SET_INFORMATION_CLASS = 2
	KeySetVirtualizationInformation KEY_SET_INFORMATION_CLASS = 3
	KeySetDebugInformation          KEY_SET_INFORMATION_CLASS = 4
	KeySetHandleTagsInformation     KEY_SET_INFORMATION_CLASS = 5
	KeySetLayerInformation          KEY_SET_INFORMATION_CLASS = 6
	MaxKeySetInfoClass              KEY_SET_INFORMATION_CLASS = 7
)

// String returns the KEY_SET_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e KEY_SET_INFORMATION_CLASS) String() string {
	switch e {
	case KeyWriteTimeInformation:
		return "KeyWriteTimeInformation"
	case KeyWow64FlagsInformation:
		return "KeyWow64FlagsInformation"
	case KeyControlFlagsInformation:
		return "KeyControlFlagsInformation"
	case KeySetVirtualizationInformation:
		return "KeySetVirtualizationInformation"
	case KeySetDebugInformation:
		return "KeySetDebugInformation"
	case KeySetHandleTagsInformation:
		return "KeySetHandleTagsInformation"
	case KeySetLayerInformation:
		return "KeySetLayerInformation"
	case MaxKeySetInfoClass:
		return "MaxKeySetInfoClass"
	default:
		return fmt.Sprintf("KEY_SET_INFORMATION_CLASS(%d)", int32(e))
	}
}

type KEY_VALUE_INFORMATION_CLASS int32

const (
	KeyValueBasicInformation          KEY_VALUE_INFORMATION_CLASS = 0
	KeyValueFullInformation           KEY_VALUE_INFORMATION_CLASS = 1
	KeyValuePartialInformation        KEY_VALUE_INFORMATION_CLASS = 2
	KeyValueFullInformationAlign64    KEY_VALUE_INFORMATION_CLASS = 3
	KeyValuePartialInformationAlign64 KEY_VALUE_INFORMATION_CLASS = 4
	KeyValueLayerInformation          KEY_VALUE_INFORMATION_CLASS = 5
	MaxKeyValueInfoClass              KEY_VALUE_INFORMATION_CLASS = 6
)

// String returns the KEY_VALUE_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e KEY_VALUE_INFORMATION_CLASS) String() string {
	switch e {
	case KeyValueBasicInformation:
		return "KeyValueBasicInformation"
	case KeyValueFullInformation:
		return "KeyValueFullInformation"
	case KeyValuePartialInformation:
		return "KeyValuePartialInformation"
	case KeyValueFullInformationAlign64:
		return "KeyValueFullInformationAlign64"
	case KeyValuePartialInformationAlign64:
		return "KeyValuePartialInformationAlign64"
	case KeyValueLayerInformation:
		return "KeyValueLayerInformation"
	case MaxKeyValueInfoClass:
		return "MaxKeyValueInfoClass"
	default:
		return fmt.Sprintf("KEY_VALUE_INFORMATION_CLASS(%d)", int32(e))
	}
}
