// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package registry

import (
	"unsafe"

	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

type KEY_VALUE_ENTRY struct {
	ValueName  *win32foundation.UNICODE_STRING
	DataLength uint32
	DataOffset uint32
	Type       uint32
}

type REG_ENUMERATE_KEY_INFORMATION struct {
	Object              unsafe.Pointer
	Index               uint32
	KeyInformationClass KEY_INFORMATION_CLASS
	KeyInformation      unsafe.Pointer
	Length              uint32
	ResultLength        *uint32
	CallContext         unsafe.Pointer
	ObjectContext       unsafe.Pointer
	Reserved            unsafe.Pointer
}

type REG_ENUMERATE_VALUE_KEY_INFORMATION struct {
	Object                   unsafe.Pointer
	Index                    uint32
	KeyValueInformationClass KEY_VALUE_INFORMATION_CLASS
	KeyValueInformation      unsafe.Pointer
	Length                   uint32
	ResultLength             *uint32
	CallContext              unsafe.Pointer
	ObjectContext            unsafe.Pointer
	Reserved                 unsafe.Pointer
}

type REG_QUERY_KEY_INFORMATION struct {
	Object              unsafe.Pointer
	KeyInformationClass KEY_INFORMATION_CLASS
	KeyInformation      unsafe.Pointer
	Length              uint32
	ResultLength        *uint32
	CallContext         unsafe.Pointer
	ObjectContext       unsafe.Pointer
	Reserved            unsafe.Pointer
}

type REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION struct {
	Object               unsafe.Pointer
	ValueEntries         *KEY_VALUE_ENTRY
	EntryCount           uint32
	ValueBuffer          unsafe.Pointer
	BufferLength         *uint32
	RequiredBufferLength *uint32
	CallContext          unsafe.Pointer
	ObjectContext        unsafe.Pointer
	Reserved             unsafe.Pointer
}

type REG_QUERY_VALUE_KEY_INFORMATION struct {
	Object                   unsafe.Pointer
	ValueName                *win32foundation.UNICODE_STRING
	KeyValueInformationClass KEY_VALUE_INFORMATION_CLASS
	KeyValueInformation      unsafe.Pointer
	Length                   uint32
	ResultLength             *uint32
	CallContext              unsafe.Pointer
	ObjectContext            unsafe.Pointer
	Reserved                 unsafe.Pointer
}

type REG_SET_INFORMATION_KEY_INFORMATION struct {
	Object                  unsafe.Pointer
	KeySetInformationClass  KEY_SET_INFORMATION_CLASS
	KeySetInformation       unsafe.Pointer
	KeySetInformationLength uint32
	CallContext             unsafe.Pointer
	ObjectContext           unsafe.Pointer
	Reserved                unsafe.Pointer
}
