// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package memory

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-wdk/bindings/wdk/foundation"
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

var (
	modntdll = win32.NewDLL("ntdll.dll")
)

var (
	procNtMapViewOfSection   = modntdll.NewProc("NtMapViewOfSection")
	procNtOpenSection        = modntdll.NewProc("NtOpenSection")
	procNtUnmapViewOfSection = modntdll.NewProc("NtUnmapViewOfSection")
	procZwMapViewOfSection   = modntdll.NewProc("ZwMapViewOfSection")
	procZwOpenSection        = modntdll.NewProc("ZwOpenSection")
	procZwUnmapViewOfSection = modntdll.NewProc("ZwUnmapViewOfSection")
)

// NtMapViewOfSection calls ntdll!NtMapViewOfSection.
func NtMapViewOfSection(SectionHandle win32foundation.HANDLE, ProcessHandle win32foundation.HANDLE, BaseAddress *unsafe.Pointer, ZeroBits uintptr, CommitSize uintptr, SectionOffset *int64, ViewSize *uintptr, InheritDisposition SECTION_INHERIT, AllocationType uint32, Win32Protect uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtMapViewOfSection.Addr(), uintptr(SectionHandle), uintptr(ProcessHandle), uintptr(unsafe.Pointer(BaseAddress)), uintptr(ZeroBits), uintptr(CommitSize), uintptr(unsafe.Pointer(SectionOffset)), uintptr(unsafe.Pointer(ViewSize)), uintptr(InheritDisposition), uintptr(AllocationType), uintptr(Win32Protect))
	return win32foundation.NTSTATUS(r1)
}

// NtOpenSection calls ntdll!NtOpenSection.
func NtOpenSection(SectionHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtOpenSection.Addr(), uintptr(unsafe.Pointer(SectionHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// NtUnmapViewOfSection calls ntdll!NtUnmapViewOfSection.
func NtUnmapViewOfSection(ProcessHandle win32foundation.HANDLE, BaseAddress unsafe.Pointer) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procNtUnmapViewOfSection.Addr(), uintptr(ProcessHandle), uintptr(unsafe.Pointer(BaseAddress)))
	return win32foundation.NTSTATUS(r1)
}

// ZwMapViewOfSection calls ntdll!ZwMapViewOfSection.
func ZwMapViewOfSection(SectionHandle win32foundation.HANDLE, ProcessHandle win32foundation.HANDLE, BaseAddress *unsafe.Pointer, ZeroBits uintptr, CommitSize uintptr, SectionOffset *int64, ViewSize *uintptr, InheritDisposition SECTION_INHERIT, AllocationType uint32, Win32Protect uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwMapViewOfSection.Addr(), uintptr(SectionHandle), uintptr(ProcessHandle), uintptr(unsafe.Pointer(BaseAddress)), uintptr(ZeroBits), uintptr(CommitSize), uintptr(unsafe.Pointer(SectionOffset)), uintptr(unsafe.Pointer(ViewSize)), uintptr(InheritDisposition), uintptr(AllocationType), uintptr(Win32Protect))
	return win32foundation.NTSTATUS(r1)
}

// ZwOpenSection calls ntdll!ZwOpenSection.
func ZwOpenSection(SectionHandle *win32foundation.HANDLE, DesiredAccess uint32, ObjectAttributes *foundation.OBJECT_ATTRIBUTES) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwOpenSection.Addr(), uintptr(unsafe.Pointer(SectionHandle)), uintptr(DesiredAccess), uintptr(unsafe.Pointer(ObjectAttributes)))
	return win32foundation.NTSTATUS(r1)
}

// ZwUnmapViewOfSection calls ntdll!ZwUnmapViewOfSection.
func ZwUnmapViewOfSection(ProcessHandle win32foundation.HANDLE, BaseAddress unsafe.Pointer) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procZwUnmapViewOfSection.Addr(), uintptr(ProcessHandle), uintptr(unsafe.Pointer(BaseAddress)))
	return win32foundation.NTSTATUS(r1)
}
