// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package bluetooth

import (
	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
)

var DEVPKEY_Bluetooth_ClassOfDevice = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 10}
var DEVPKEY_Bluetooth_ClassOfDevice_Deprecated = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 4}
var DEVPKEY_Bluetooth_DeviceAddress = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 1}
var DEVPKEY_Bluetooth_DeviceFlags = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 3}
var DEVPKEY_Bluetooth_DeviceManufacturer = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 4}
var DEVPKEY_Bluetooth_DeviceModelNumber = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 5}
var DEVPKEY_Bluetooth_DevicePID = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 8}
var DEVPKEY_Bluetooth_DeviceProductVersion = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 9}
var DEVPKEY_Bluetooth_DeviceVID = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 7}
var DEVPKEY_Bluetooth_DeviceVIDSource = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 6}
var DEVPKEY_Bluetooth_LastConnectedTime = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 11}
var DEVPKEY_Bluetooth_LastConnectedTime_Deprecated = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 5}
var DEVPKEY_Bluetooth_LastSeenTime = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 12}
var DEVPKEY_Bluetooth_ServiceGUID = win32foundation.DEVPROPKEY{Fmtid: win32.GUID{Data1: 735477131, Data2: 35819, Data3: 18645, Data4: [8]byte{135, 224, 108, 218, 52, 40, 4, 10}}, Pid: 2}
var GUID_BTHDDI_PROFILE_DRIVER_INTERFACE win32.GUID = win32.GUID{Data1: 0x94a59aa8, Data2: 0x4383, Data3: 0x4286, Data4: [8]byte{0xaa, 0x4f, 0x34, 0xa1, 0x60, 0xf4, 0x00, 0x04}}
var GUID_BTHDDI_SDP_NODE_INTERFACE win32.GUID = win32.GUID{Data1: 0x81a7fdf3, Data2: 0x86c1, Data3: 0x4be8, Data4: [8]byte{0xa8, 0xc8, 0x2a, 0x6d, 0x18, 0x8b, 0x41, 0x77}}
var GUID_BTHDDI_SDP_PARSE_INTERFACE win32.GUID = win32.GUID{Data1: 0x4e719439, Data2: 0x9cf1, Data3: 0x4bab, Data4: [8]byte{0xac, 0x1d, 0x32, 0x79, 0x86, 0x57, 0x43, 0xd2}}
var GUID_BTH_DEVICE_INTERFACE win32.GUID = win32.GUID{Data1: 0x00f40965, Data2: 0xe89d, Data3: 0x4487, Data4: [8]byte{0x98, 0x90, 0x87, 0xc3, 0xab, 0xb2, 0x11, 0xf4}}
