// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package windowsfilteringplatform

import (
	"syscall"
	"unsafe"

	"github.com/deploymenttheory/go-bindings-win32/bindings/runtime/win32"
	win32foundation "github.com/deploymenttheory/go-bindings-win32/bindings/win32/foundation"
	win32networkmanagementwindowsfilteringplatform "github.com/deploymenttheory/go-bindings-win32/bindings/win32/networkmanagement/windowsfilteringplatform"
	win32security "github.com/deploymenttheory/go-bindings-win32/bindings/win32/security"
	win32systemrpc "github.com/deploymenttheory/go-bindings-win32/bindings/win32/system/rpc"
)

var (
	modfwpkclnt_sys = win32.NewDLL("fwpkclnt.sys")
	modfwpuclnt     = win32.NewDLL("fwpuclnt.dll")
)

var (
	procFwpmBfeStateGet0                         = modfwpkclnt_sys.NewProc("FwpmBfeStateGet0")
	procFwpmBfeStateSubscribeChanges0            = modfwpkclnt_sys.NewProc("FwpmBfeStateSubscribeChanges0")
	procFwpmBfeStateUnsubscribeChanges0          = modfwpkclnt_sys.NewProc("FwpmBfeStateUnsubscribeChanges0")
	procFwpmCalloutAdd0                          = modfwpuclnt.NewProc("FwpmCalloutAdd0")
	procFwpmCalloutCreateEnumHandle0             = modfwpuclnt.NewProc("FwpmCalloutCreateEnumHandle0")
	procFwpmCalloutDeleteById0                   = modfwpuclnt.NewProc("FwpmCalloutDeleteById0")
	procFwpmCalloutDeleteByKey0                  = modfwpuclnt.NewProc("FwpmCalloutDeleteByKey0")
	procFwpmCalloutDestroyEnumHandle0            = modfwpuclnt.NewProc("FwpmCalloutDestroyEnumHandle0")
	procFwpmCalloutEnum0                         = modfwpuclnt.NewProc("FwpmCalloutEnum0")
	procFwpmCalloutGetById0                      = modfwpuclnt.NewProc("FwpmCalloutGetById0")
	procFwpmCalloutGetByKey0                     = modfwpuclnt.NewProc("FwpmCalloutGetByKey0")
	procFwpmCalloutGetSecurityInfoByKey0         = modfwpuclnt.NewProc("FwpmCalloutGetSecurityInfoByKey0")
	procFwpmCalloutSetSecurityInfoByKey0         = modfwpuclnt.NewProc("FwpmCalloutSetSecurityInfoByKey0")
	procFwpmConnectionCreateEnumHandle0          = modfwpuclnt.NewProc("FwpmConnectionCreateEnumHandle0")
	procFwpmConnectionDestroyEnumHandle0         = modfwpuclnt.NewProc("FwpmConnectionDestroyEnumHandle0")
	procFwpmConnectionEnum0                      = modfwpuclnt.NewProc("FwpmConnectionEnum0")
	procFwpmConnectionGetById0                   = modfwpuclnt.NewProc("FwpmConnectionGetById0")
	procFwpmConnectionGetSecurityInfo0           = modfwpuclnt.NewProc("FwpmConnectionGetSecurityInfo0")
	procFwpmConnectionSetSecurityInfo0           = modfwpuclnt.NewProc("FwpmConnectionSetSecurityInfo0")
	procFwpmEngineClose0                         = modfwpuclnt.NewProc("FwpmEngineClose0")
	procFwpmEngineGetOption0                     = modfwpuclnt.NewProc("FwpmEngineGetOption0")
	procFwpmEngineGetSecurityInfo0               = modfwpuclnt.NewProc("FwpmEngineGetSecurityInfo0")
	procFwpmEngineOpen0                          = modfwpuclnt.NewProc("FwpmEngineOpen0")
	procFwpmEngineSetOption0                     = modfwpuclnt.NewProc("FwpmEngineSetOption0")
	procFwpmEngineSetSecurityInfo0               = modfwpuclnt.NewProc("FwpmEngineSetSecurityInfo0")
	procFwpmFilterAdd0                           = modfwpuclnt.NewProc("FwpmFilterAdd0")
	procFwpmFilterCreateEnumHandle0              = modfwpuclnt.NewProc("FwpmFilterCreateEnumHandle0")
	procFwpmFilterDeleteById0                    = modfwpuclnt.NewProc("FwpmFilterDeleteById0")
	procFwpmFilterDeleteByKey0                   = modfwpuclnt.NewProc("FwpmFilterDeleteByKey0")
	procFwpmFilterDestroyEnumHandle0             = modfwpuclnt.NewProc("FwpmFilterDestroyEnumHandle0")
	procFwpmFilterEnum0                          = modfwpuclnt.NewProc("FwpmFilterEnum0")
	procFwpmFilterGetById0                       = modfwpuclnt.NewProc("FwpmFilterGetById0")
	procFwpmFilterGetByKey0                      = modfwpuclnt.NewProc("FwpmFilterGetByKey0")
	procFwpmFilterGetSecurityInfoByKey0          = modfwpuclnt.NewProc("FwpmFilterGetSecurityInfoByKey0")
	procFwpmFilterSetSecurityInfoByKey0          = modfwpuclnt.NewProc("FwpmFilterSetSecurityInfoByKey0")
	procFwpmFreeMemory0                          = modfwpuclnt.NewProc("FwpmFreeMemory0")
	procFwpmIPsecTunnelAdd0                      = modfwpuclnt.NewProc("FwpmIPsecTunnelAdd0")
	procFwpmIPsecTunnelAdd1                      = modfwpuclnt.NewProc("FwpmIPsecTunnelAdd1")
	procFwpmIPsecTunnelAdd2                      = modfwpuclnt.NewProc("FwpmIPsecTunnelAdd2")
	procFwpmIPsecTunnelAdd3                      = modfwpuclnt.NewProc("FwpmIPsecTunnelAdd3")
	procFwpmIPsecTunnelDeleteByKey0              = modfwpuclnt.NewProc("FwpmIPsecTunnelDeleteByKey0")
	procFwpmLayerCreateEnumHandle0               = modfwpuclnt.NewProc("FwpmLayerCreateEnumHandle0")
	procFwpmLayerDestroyEnumHandle0              = modfwpuclnt.NewProc("FwpmLayerDestroyEnumHandle0")
	procFwpmLayerEnum0                           = modfwpuclnt.NewProc("FwpmLayerEnum0")
	procFwpmLayerGetById0                        = modfwpuclnt.NewProc("FwpmLayerGetById0")
	procFwpmLayerGetByKey0                       = modfwpuclnt.NewProc("FwpmLayerGetByKey0")
	procFwpmLayerGetSecurityInfoByKey0           = modfwpuclnt.NewProc("FwpmLayerGetSecurityInfoByKey0")
	procFwpmLayerSetSecurityInfoByKey0           = modfwpuclnt.NewProc("FwpmLayerSetSecurityInfoByKey0")
	procFwpmNetEventCreateEnumHandle0            = modfwpuclnt.NewProc("FwpmNetEventCreateEnumHandle0")
	procFwpmNetEventDestroyEnumHandle0           = modfwpuclnt.NewProc("FwpmNetEventDestroyEnumHandle0")
	procFwpmNetEventEnum0                        = modfwpuclnt.NewProc("FwpmNetEventEnum0")
	procFwpmNetEventEnum1                        = modfwpuclnt.NewProc("FwpmNetEventEnum1")
	procFwpmNetEventEnum2                        = modfwpuclnt.NewProc("FwpmNetEventEnum2")
	procFwpmNetEventEnum3                        = modfwpuclnt.NewProc("FwpmNetEventEnum3")
	procFwpmNetEventEnum4                        = modfwpuclnt.NewProc("FwpmNetEventEnum4")
	procFwpmNetEventEnum5                        = modfwpuclnt.NewProc("FwpmNetEventEnum5")
	procFwpmNetEventsGetSecurityInfo0            = modfwpuclnt.NewProc("FwpmNetEventsGetSecurityInfo0")
	procFwpmNetEventsSetSecurityInfo0            = modfwpuclnt.NewProc("FwpmNetEventsSetSecurityInfo0")
	procFwpmProviderAdd0                         = modfwpuclnt.NewProc("FwpmProviderAdd0")
	procFwpmProviderContextAdd0                  = modfwpuclnt.NewProc("FwpmProviderContextAdd0")
	procFwpmProviderContextAdd1                  = modfwpuclnt.NewProc("FwpmProviderContextAdd1")
	procFwpmProviderContextAdd2                  = modfwpuclnt.NewProc("FwpmProviderContextAdd2")
	procFwpmProviderContextAdd3                  = modfwpuclnt.NewProc("FwpmProviderContextAdd3")
	procFwpmProviderContextCreateEnumHandle0     = modfwpuclnt.NewProc("FwpmProviderContextCreateEnumHandle0")
	procFwpmProviderContextDeleteById0           = modfwpuclnt.NewProc("FwpmProviderContextDeleteById0")
	procFwpmProviderContextDeleteByKey0          = modfwpuclnt.NewProc("FwpmProviderContextDeleteByKey0")
	procFwpmProviderContextDestroyEnumHandle0    = modfwpuclnt.NewProc("FwpmProviderContextDestroyEnumHandle0")
	procFwpmProviderContextEnum0                 = modfwpuclnt.NewProc("FwpmProviderContextEnum0")
	procFwpmProviderContextEnum1                 = modfwpuclnt.NewProc("FwpmProviderContextEnum1")
	procFwpmProviderContextEnum2                 = modfwpuclnt.NewProc("FwpmProviderContextEnum2")
	procFwpmProviderContextEnum3                 = modfwpuclnt.NewProc("FwpmProviderContextEnum3")
	procFwpmProviderContextGetById0              = modfwpuclnt.NewProc("FwpmProviderContextGetById0")
	procFwpmProviderContextGetById1              = modfwpuclnt.NewProc("FwpmProviderContextGetById1")
	procFwpmProviderContextGetById2              = modfwpuclnt.NewProc("FwpmProviderContextGetById2")
	procFwpmProviderContextGetById3              = modfwpuclnt.NewProc("FwpmProviderContextGetById3")
	procFwpmProviderContextGetByKey0             = modfwpuclnt.NewProc("FwpmProviderContextGetByKey0")
	procFwpmProviderContextGetByKey1             = modfwpuclnt.NewProc("FwpmProviderContextGetByKey1")
	procFwpmProviderContextGetByKey2             = modfwpuclnt.NewProc("FwpmProviderContextGetByKey2")
	procFwpmProviderContextGetByKey3             = modfwpuclnt.NewProc("FwpmProviderContextGetByKey3")
	procFwpmProviderContextGetSecurityInfoByKey0 = modfwpuclnt.NewProc("FwpmProviderContextGetSecurityInfoByKey0")
	procFwpmProviderContextSetSecurityInfoByKey0 = modfwpuclnt.NewProc("FwpmProviderContextSetSecurityInfoByKey0")
	procFwpmProviderCreateEnumHandle0            = modfwpuclnt.NewProc("FwpmProviderCreateEnumHandle0")
	procFwpmProviderDeleteByKey0                 = modfwpuclnt.NewProc("FwpmProviderDeleteByKey0")
	procFwpmProviderDestroyEnumHandle0           = modfwpuclnt.NewProc("FwpmProviderDestroyEnumHandle0")
	procFwpmProviderEnum0                        = modfwpuclnt.NewProc("FwpmProviderEnum0")
	procFwpmProviderGetByKey0                    = modfwpuclnt.NewProc("FwpmProviderGetByKey0")
	procFwpmProviderGetSecurityInfoByKey0        = modfwpuclnt.NewProc("FwpmProviderGetSecurityInfoByKey0")
	procFwpmProviderSetSecurityInfoByKey0        = modfwpuclnt.NewProc("FwpmProviderSetSecurityInfoByKey0")
	procFwpmSessionCreateEnumHandle0             = modfwpuclnt.NewProc("FwpmSessionCreateEnumHandle0")
	procFwpmSessionDestroyEnumHandle0            = modfwpuclnt.NewProc("FwpmSessionDestroyEnumHandle0")
	procFwpmSessionEnum0                         = modfwpuclnt.NewProc("FwpmSessionEnum0")
	procFwpmSubLayerAdd0                         = modfwpuclnt.NewProc("FwpmSubLayerAdd0")
	procFwpmSubLayerCreateEnumHandle0            = modfwpuclnt.NewProc("FwpmSubLayerCreateEnumHandle0")
	procFwpmSubLayerDeleteByKey0                 = modfwpuclnt.NewProc("FwpmSubLayerDeleteByKey0")
	procFwpmSubLayerDestroyEnumHandle0           = modfwpuclnt.NewProc("FwpmSubLayerDestroyEnumHandle0")
	procFwpmSubLayerEnum0                        = modfwpuclnt.NewProc("FwpmSubLayerEnum0")
	procFwpmSubLayerGetByKey0                    = modfwpuclnt.NewProc("FwpmSubLayerGetByKey0")
	procFwpmSubLayerGetSecurityInfoByKey0        = modfwpuclnt.NewProc("FwpmSubLayerGetSecurityInfoByKey0")
	procFwpmSubLayerSetSecurityInfoByKey0        = modfwpuclnt.NewProc("FwpmSubLayerSetSecurityInfoByKey0")
	procFwpmTransactionAbort0                    = modfwpuclnt.NewProc("FwpmTransactionAbort0")
	procFwpmTransactionBegin0                    = modfwpuclnt.NewProc("FwpmTransactionBegin0")
	procFwpmTransactionCommit0                   = modfwpuclnt.NewProc("FwpmTransactionCommit0")
	procFwpmvSwitchEventsGetSecurityInfo0        = modfwpuclnt.NewProc("FwpmvSwitchEventsGetSecurityInfo0")
	procFwpmvSwitchEventsSetSecurityInfo0        = modfwpuclnt.NewProc("FwpmvSwitchEventsSetSecurityInfo0")
	procIPsecDospGetSecurityInfo0                = modfwpuclnt.NewProc("IPsecDospGetSecurityInfo0")
	procIPsecDospGetStatistics0                  = modfwpuclnt.NewProc("IPsecDospGetStatistics0")
	procIPsecDospSetSecurityInfo0                = modfwpuclnt.NewProc("IPsecDospSetSecurityInfo0")
	procIPsecDospStateCreateEnumHandle0          = modfwpuclnt.NewProc("IPsecDospStateCreateEnumHandle0")
	procIPsecDospStateDestroyEnumHandle0         = modfwpuclnt.NewProc("IPsecDospStateDestroyEnumHandle0")
	procIPsecDospStateEnum0                      = modfwpuclnt.NewProc("IPsecDospStateEnum0")
	procIPsecGetStatistics0                      = modfwpuclnt.NewProc("IPsecGetStatistics0")
	procIPsecGetStatistics1                      = modfwpuclnt.NewProc("IPsecGetStatistics1")
	procIPsecSaContextAddInbound0                = modfwpuclnt.NewProc("IPsecSaContextAddInbound0")
	procIPsecSaContextAddInbound1                = modfwpuclnt.NewProc("IPsecSaContextAddInbound1")
	procIPsecSaContextAddOutbound0               = modfwpuclnt.NewProc("IPsecSaContextAddOutbound0")
	procIPsecSaContextAddOutbound1               = modfwpuclnt.NewProc("IPsecSaContextAddOutbound1")
	procIPsecSaContextCreate0                    = modfwpuclnt.NewProc("IPsecSaContextCreate0")
	procIPsecSaContextCreate1                    = modfwpuclnt.NewProc("IPsecSaContextCreate1")
	procIPsecSaContextCreateEnumHandle0          = modfwpuclnt.NewProc("IPsecSaContextCreateEnumHandle0")
	procIPsecSaContextDeleteById0                = modfwpuclnt.NewProc("IPsecSaContextDeleteById0")
	procIPsecSaContextDestroyEnumHandle0         = modfwpuclnt.NewProc("IPsecSaContextDestroyEnumHandle0")
	procIPsecSaContextEnum0                      = modfwpuclnt.NewProc("IPsecSaContextEnum0")
	procIPsecSaContextEnum1                      = modfwpuclnt.NewProc("IPsecSaContextEnum1")
	procIPsecSaContextExpire0                    = modfwpuclnt.NewProc("IPsecSaContextExpire0")
	procIPsecSaContextGetById0                   = modfwpuclnt.NewProc("IPsecSaContextGetById0")
	procIPsecSaContextGetById1                   = modfwpuclnt.NewProc("IPsecSaContextGetById1")
	procIPsecSaContextGetSpi0                    = modfwpuclnt.NewProc("IPsecSaContextGetSpi0")
	procIPsecSaContextGetSpi1                    = modfwpuclnt.NewProc("IPsecSaContextGetSpi1")
	procIPsecSaContextSetSpi0                    = modfwpuclnt.NewProc("IPsecSaContextSetSpi0")
	procIPsecSaContextUpdate0                    = modfwpuclnt.NewProc("IPsecSaContextUpdate0")
	procIPsecSaCreateEnumHandle0                 = modfwpuclnt.NewProc("IPsecSaCreateEnumHandle0")
	procIPsecSaDbGetSecurityInfo0                = modfwpuclnt.NewProc("IPsecSaDbGetSecurityInfo0")
	procIPsecSaDbSetSecurityInfo0                = modfwpuclnt.NewProc("IPsecSaDbSetSecurityInfo0")
	procIPsecSaDestroyEnumHandle0                = modfwpuclnt.NewProc("IPsecSaDestroyEnumHandle0")
	procIPsecSaEnum0                             = modfwpuclnt.NewProc("IPsecSaEnum0")
	procIPsecSaEnum1                             = modfwpuclnt.NewProc("IPsecSaEnum1")
	procIkeextGetStatistics0                     = modfwpuclnt.NewProc("IkeextGetStatistics0")
	procIkeextGetStatistics1                     = modfwpuclnt.NewProc("IkeextGetStatistics1")
	procIkeextSaCreateEnumHandle0                = modfwpuclnt.NewProc("IkeextSaCreateEnumHandle0")
	procIkeextSaDbGetSecurityInfo0               = modfwpuclnt.NewProc("IkeextSaDbGetSecurityInfo0")
	procIkeextSaDbSetSecurityInfo0               = modfwpuclnt.NewProc("IkeextSaDbSetSecurityInfo0")
	procIkeextSaDeleteById0                      = modfwpuclnt.NewProc("IkeextSaDeleteById0")
	procIkeextSaDestroyEnumHandle0               = modfwpuclnt.NewProc("IkeextSaDestroyEnumHandle0")
	procIkeextSaEnum0                            = modfwpuclnt.NewProc("IkeextSaEnum0")
	procIkeextSaEnum1                            = modfwpuclnt.NewProc("IkeextSaEnum1")
	procIkeextSaEnum2                            = modfwpuclnt.NewProc("IkeextSaEnum2")
	procIkeextSaGetById0                         = modfwpuclnt.NewProc("IkeextSaGetById0")
	procIkeextSaGetById1                         = modfwpuclnt.NewProc("IkeextSaGetById1")
	procIkeextSaGetById2                         = modfwpuclnt.NewProc("IkeextSaGetById2")
)

// FwpmBfeStateGet0 calls fwpkclnt.sys!FwpmBfeStateGet0.
func FwpmBfeStateGet0() win32networkmanagementwindowsfilteringplatform.FWPM_SERVICE_STATE {
	r1, _, _ := syscall.SyscallN(procFwpmBfeStateGet0.Addr())
	return win32networkmanagementwindowsfilteringplatform.FWPM_SERVICE_STATE(r1)
}

// FwpmBfeStateSubscribeChanges0 calls fwpkclnt.sys!FwpmBfeStateSubscribeChanges0.
func FwpmBfeStateSubscribeChanges0(deviceObject unsafe.Pointer, callback FWPM_SERVICE_STATE_CHANGE_CALLBACK0, context unsafe.Pointer, changeHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmBfeStateSubscribeChanges0.Addr(), uintptr(unsafe.Pointer(deviceObject)), uintptr(callback), uintptr(unsafe.Pointer(context)), uintptr(unsafe.Pointer(changeHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmBfeStateUnsubscribeChanges0 calls fwpkclnt.sys!FwpmBfeStateUnsubscribeChanges0.
func FwpmBfeStateUnsubscribeChanges0(changeHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmBfeStateUnsubscribeChanges0.Addr(), uintptr(changeHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutAdd0 calls fwpuclnt!FwpmCalloutAdd0.
func FwpmCalloutAdd0(engineHandle win32foundation.HANDLE, callout *win32networkmanagementwindowsfilteringplatform.FWPM_CALLOUT0, sd win32security.PSECURITY_DESCRIPTOR, id *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutAdd0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(callout)), uintptr(sd), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutCreateEnumHandle0 calls fwpuclnt!FwpmCalloutCreateEnumHandle0.
func FwpmCalloutCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_CALLOUT_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutDeleteById0 calls fwpuclnt!FwpmCalloutDeleteById0.
func FwpmCalloutDeleteById0(engineHandle win32foundation.HANDLE, id uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutDeleteById0.Addr(), uintptr(engineHandle), uintptr(id))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutDeleteByKey0 calls fwpuclnt!FwpmCalloutDeleteByKey0.
func FwpmCalloutDeleteByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutDeleteByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutDestroyEnumHandle0 calls fwpuclnt!FwpmCalloutDestroyEnumHandle0.
func FwpmCalloutDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutEnum0 calls fwpuclnt!FwpmCalloutEnum0.
func FwpmCalloutEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_CALLOUT0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutGetById0 calls fwpuclnt!FwpmCalloutGetById0.
func FwpmCalloutGetById0(engineHandle win32foundation.HANDLE, id uint32, callout **win32networkmanagementwindowsfilteringplatform.FWPM_CALLOUT0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(callout)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutGetByKey0 calls fwpuclnt!FwpmCalloutGetByKey0.
func FwpmCalloutGetByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, callout **win32networkmanagementwindowsfilteringplatform.FWPM_CALLOUT0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutGetByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(callout)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutGetSecurityInfoByKey0 calls fwpuclnt!FwpmCalloutGetSecurityInfoByKey0.
func FwpmCalloutGetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutGetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmCalloutSetSecurityInfoByKey0 calls fwpuclnt!FwpmCalloutSetSecurityInfoByKey0.
func FwpmCalloutSetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmCalloutSetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmConnectionCreateEnumHandle0 calls fwpuclnt!FwpmConnectionCreateEnumHandle0.
func FwpmConnectionCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_CONNECTION_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmConnectionCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmConnectionDestroyEnumHandle0 calls fwpuclnt!FwpmConnectionDestroyEnumHandle0.
func FwpmConnectionDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmConnectionDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmConnectionEnum0 calls fwpuclnt!FwpmConnectionEnum0.
func FwpmConnectionEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_CONNECTION0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmConnectionEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmConnectionGetById0 calls fwpuclnt!FwpmConnectionGetById0.
func FwpmConnectionGetById0(engineHandle win32foundation.HANDLE, id uint64, connection **win32networkmanagementwindowsfilteringplatform.FWPM_CONNECTION0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmConnectionGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(connection)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmConnectionGetSecurityInfo0 calls fwpuclnt!FwpmConnectionGetSecurityInfo0.
func FwpmConnectionGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmConnectionGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmConnectionSetSecurityInfo0 calls fwpuclnt!FwpmConnectionSetSecurityInfo0.
func FwpmConnectionSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmConnectionSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmEngineClose0 calls fwpuclnt!FwpmEngineClose0.
func FwpmEngineClose0(engineHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmEngineClose0.Addr(), uintptr(engineHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmEngineGetOption0 calls fwpuclnt!FwpmEngineGetOption0.
func FwpmEngineGetOption0(engineHandle win32foundation.HANDLE, option win32networkmanagementwindowsfilteringplatform.FWPM_ENGINE_OPTION, value **win32networkmanagementwindowsfilteringplatform.FWP_VALUE0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmEngineGetOption0.Addr(), uintptr(engineHandle), uintptr(option), uintptr(unsafe.Pointer(value)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmEngineGetSecurityInfo0 calls fwpuclnt!FwpmEngineGetSecurityInfo0.
func FwpmEngineGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmEngineGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmEngineOpen0 calls fwpuclnt!FwpmEngineOpen0.
func FwpmEngineOpen0(serverName string, authnService uint32, authIdentity *win32systemrpc.SEC_WINNT_AUTH_IDENTITY_W, session *win32networkmanagementwindowsfilteringplatform.FWPM_SESSION0, engineHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	_serverName := win32.UTF16Ptr(serverName)
	r1, _, _ := syscall.SyscallN(procFwpmEngineOpen0.Addr(), uintptr(unsafe.Pointer(_serverName)), uintptr(authnService), uintptr(unsafe.Pointer(authIdentity)), uintptr(unsafe.Pointer(session)), uintptr(unsafe.Pointer(engineHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmEngineSetOption0 calls fwpuclnt!FwpmEngineSetOption0.
func FwpmEngineSetOption0(engineHandle win32foundation.HANDLE, option win32networkmanagementwindowsfilteringplatform.FWPM_ENGINE_OPTION, newValue *win32networkmanagementwindowsfilteringplatform.FWP_VALUE0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmEngineSetOption0.Addr(), uintptr(engineHandle), uintptr(option), uintptr(unsafe.Pointer(newValue)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmEngineSetSecurityInfo0 calls fwpuclnt!FwpmEngineSetSecurityInfo0.
func FwpmEngineSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmEngineSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterAdd0 calls fwpuclnt!FwpmFilterAdd0.
func FwpmFilterAdd0(engineHandle win32foundation.HANDLE, filter *win32networkmanagementwindowsfilteringplatform.FWPM_FILTER0, sd win32security.PSECURITY_DESCRIPTOR, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterAdd0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(filter)), uintptr(sd), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterCreateEnumHandle0 calls fwpuclnt!FwpmFilterCreateEnumHandle0.
func FwpmFilterCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterDeleteById0 calls fwpuclnt!FwpmFilterDeleteById0.
func FwpmFilterDeleteById0(engineHandle win32foundation.HANDLE, id uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterDeleteById0.Addr(), uintptr(engineHandle), uintptr(id))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterDeleteByKey0 calls fwpuclnt!FwpmFilterDeleteByKey0.
func FwpmFilterDeleteByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterDeleteByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterDestroyEnumHandle0 calls fwpuclnt!FwpmFilterDestroyEnumHandle0.
func FwpmFilterDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterEnum0 calls fwpuclnt!FwpmFilterEnum0.
func FwpmFilterEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_FILTER0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterGetById0 calls fwpuclnt!FwpmFilterGetById0.
func FwpmFilterGetById0(engineHandle win32foundation.HANDLE, id uint64, filter **win32networkmanagementwindowsfilteringplatform.FWPM_FILTER0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(filter)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterGetByKey0 calls fwpuclnt!FwpmFilterGetByKey0.
func FwpmFilterGetByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, filter **win32networkmanagementwindowsfilteringplatform.FWPM_FILTER0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterGetByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(filter)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterGetSecurityInfoByKey0 calls fwpuclnt!FwpmFilterGetSecurityInfoByKey0.
func FwpmFilterGetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterGetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFilterSetSecurityInfoByKey0 calls fwpuclnt!FwpmFilterSetSecurityInfoByKey0.
func FwpmFilterSetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmFilterSetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmFreeMemory0 calls fwpuclnt!FwpmFreeMemory0.
func FwpmFreeMemory0(p *unsafe.Pointer) {
	syscall.SyscallN(procFwpmFreeMemory0.Addr(), uintptr(unsafe.Pointer(p)))
}

// FwpmIPsecTunnelAdd0 calls fwpuclnt!FwpmIPsecTunnelAdd0.
func FwpmIPsecTunnelAdd0(engineHandle win32foundation.HANDLE, flags uint32, mainModePolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT0, tunnelPolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT0, filterConditions []win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0, sd win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	var _filterConditions *win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0
	if len(filterConditions) > 0 {
		_filterConditions = &filterConditions[0]
	}
	r1, _, _ := syscall.SyscallN(procFwpmIPsecTunnelAdd0.Addr(), uintptr(engineHandle), uintptr(flags), uintptr(unsafe.Pointer(mainModePolicy)), uintptr(unsafe.Pointer(tunnelPolicy)), uintptr(len(filterConditions)), uintptr(unsafe.Pointer(_filterConditions)), uintptr(sd))
	return win32foundation.NTSTATUS(r1)
}

// FwpmIPsecTunnelAdd1 calls fwpuclnt!FwpmIPsecTunnelAdd1.
func FwpmIPsecTunnelAdd1(engineHandle win32foundation.HANDLE, flags uint32, mainModePolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT1, tunnelPolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT1, filterConditions []win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0, keyModKey *win32.GUID, sd win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	var _filterConditions *win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0
	if len(filterConditions) > 0 {
		_filterConditions = &filterConditions[0]
	}
	r1, _, _ := syscall.SyscallN(procFwpmIPsecTunnelAdd1.Addr(), uintptr(engineHandle), uintptr(flags), uintptr(unsafe.Pointer(mainModePolicy)), uintptr(unsafe.Pointer(tunnelPolicy)), uintptr(len(filterConditions)), uintptr(unsafe.Pointer(_filterConditions)), uintptr(unsafe.Pointer(keyModKey)), uintptr(sd))
	return win32foundation.NTSTATUS(r1)
}

// FwpmIPsecTunnelAdd2 calls fwpuclnt!FwpmIPsecTunnelAdd2.
func FwpmIPsecTunnelAdd2(engineHandle win32foundation.HANDLE, flags uint32, mainModePolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT2, tunnelPolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT2, filterConditions []win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0, keyModKey *win32.GUID, sd win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	var _filterConditions *win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0
	if len(filterConditions) > 0 {
		_filterConditions = &filterConditions[0]
	}
	r1, _, _ := syscall.SyscallN(procFwpmIPsecTunnelAdd2.Addr(), uintptr(engineHandle), uintptr(flags), uintptr(unsafe.Pointer(mainModePolicy)), uintptr(unsafe.Pointer(tunnelPolicy)), uintptr(len(filterConditions)), uintptr(unsafe.Pointer(_filterConditions)), uintptr(unsafe.Pointer(keyModKey)), uintptr(sd))
	return win32foundation.NTSTATUS(r1)
}

// FwpmIPsecTunnelAdd3 calls fwpuclnt!FwpmIPsecTunnelAdd3.
func FwpmIPsecTunnelAdd3(engineHandle win32foundation.HANDLE, flags uint32, mainModePolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT3, tunnelPolicy *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT3, filterConditions []win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0, keyModKey *win32.GUID, sd win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	var _filterConditions *win32networkmanagementwindowsfilteringplatform.FWPM_FILTER_CONDITION0
	if len(filterConditions) > 0 {
		_filterConditions = &filterConditions[0]
	}
	r1, _, _ := syscall.SyscallN(procFwpmIPsecTunnelAdd3.Addr(), uintptr(engineHandle), uintptr(flags), uintptr(unsafe.Pointer(mainModePolicy)), uintptr(unsafe.Pointer(tunnelPolicy)), uintptr(len(filterConditions)), uintptr(unsafe.Pointer(_filterConditions)), uintptr(unsafe.Pointer(keyModKey)), uintptr(sd))
	return win32foundation.NTSTATUS(r1)
}

// FwpmIPsecTunnelDeleteByKey0 calls fwpuclnt!FwpmIPsecTunnelDeleteByKey0.
func FwpmIPsecTunnelDeleteByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmIPsecTunnelDeleteByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerCreateEnumHandle0 calls fwpuclnt!FwpmLayerCreateEnumHandle0.
func FwpmLayerCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_LAYER_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerDestroyEnumHandle0 calls fwpuclnt!FwpmLayerDestroyEnumHandle0.
func FwpmLayerDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerEnum0 calls fwpuclnt!FwpmLayerEnum0.
func FwpmLayerEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_LAYER0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerGetById0 calls fwpuclnt!FwpmLayerGetById0.
func FwpmLayerGetById0(engineHandle win32foundation.HANDLE, id uint16, layer **win32networkmanagementwindowsfilteringplatform.FWPM_LAYER0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(layer)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerGetByKey0 calls fwpuclnt!FwpmLayerGetByKey0.
func FwpmLayerGetByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, layer **win32networkmanagementwindowsfilteringplatform.FWPM_LAYER0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerGetByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(layer)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerGetSecurityInfoByKey0 calls fwpuclnt!FwpmLayerGetSecurityInfoByKey0.
func FwpmLayerGetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerGetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmLayerSetSecurityInfoByKey0 calls fwpuclnt!FwpmLayerSetSecurityInfoByKey0.
func FwpmLayerSetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmLayerSetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventCreateEnumHandle0 calls fwpuclnt!FwpmNetEventCreateEnumHandle0.
func FwpmNetEventCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventDestroyEnumHandle0 calls fwpuclnt!FwpmNetEventDestroyEnumHandle0.
func FwpmNetEventDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventEnum0 calls fwpuclnt!FwpmNetEventEnum0.
func FwpmNetEventEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventEnum1 calls fwpuclnt!FwpmNetEventEnum1.
func FwpmNetEventEnum1(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT1, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventEnum1.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventEnum2 calls fwpuclnt!FwpmNetEventEnum2.
func FwpmNetEventEnum2(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT2, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventEnum2.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventEnum3 calls fwpuclnt!FwpmNetEventEnum3.
func FwpmNetEventEnum3(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT3, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventEnum3.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventEnum4 calls fwpuclnt!FwpmNetEventEnum4.
func FwpmNetEventEnum4(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT4, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventEnum4.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventEnum5 calls fwpuclnt!FwpmNetEventEnum5.
func FwpmNetEventEnum5(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_NET_EVENT5, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventEnum5.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventsGetSecurityInfo0 calls fwpuclnt!FwpmNetEventsGetSecurityInfo0.
func FwpmNetEventsGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventsGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmNetEventsSetSecurityInfo0 calls fwpuclnt!FwpmNetEventsSetSecurityInfo0.
func FwpmNetEventsSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmNetEventsSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderAdd0 calls fwpuclnt!FwpmProviderAdd0.
func FwpmProviderAdd0(engineHandle win32foundation.HANDLE, provider *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER0, sd win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderAdd0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(provider)), uintptr(sd))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextAdd0 calls fwpuclnt!FwpmProviderContextAdd0.
func FwpmProviderContextAdd0(engineHandle win32foundation.HANDLE, providerContext *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT0, sd win32security.PSECURITY_DESCRIPTOR, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextAdd0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(providerContext)), uintptr(sd), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextAdd1 calls fwpuclnt!FwpmProviderContextAdd1.
func FwpmProviderContextAdd1(engineHandle win32foundation.HANDLE, providerContext *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT1, sd win32security.PSECURITY_DESCRIPTOR, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextAdd1.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(providerContext)), uintptr(sd), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextAdd2 calls fwpuclnt!FwpmProviderContextAdd2.
func FwpmProviderContextAdd2(engineHandle win32foundation.HANDLE, providerContext *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT2, sd win32security.PSECURITY_DESCRIPTOR, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextAdd2.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(providerContext)), uintptr(sd), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextAdd3 calls fwpuclnt!FwpmProviderContextAdd3.
func FwpmProviderContextAdd3(engineHandle win32foundation.HANDLE, providerContext *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT3, sd win32security.PSECURITY_DESCRIPTOR, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextAdd3.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(providerContext)), uintptr(sd), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextCreateEnumHandle0 calls fwpuclnt!FwpmProviderContextCreateEnumHandle0.
func FwpmProviderContextCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextDeleteById0 calls fwpuclnt!FwpmProviderContextDeleteById0.
func FwpmProviderContextDeleteById0(engineHandle win32foundation.HANDLE, id uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextDeleteById0.Addr(), uintptr(engineHandle), uintptr(id))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextDeleteByKey0 calls fwpuclnt!FwpmProviderContextDeleteByKey0.
func FwpmProviderContextDeleteByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextDeleteByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextDestroyEnumHandle0 calls fwpuclnt!FwpmProviderContextDestroyEnumHandle0.
func FwpmProviderContextDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextEnum0 calls fwpuclnt!FwpmProviderContextEnum0.
func FwpmProviderContextEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextEnum1 calls fwpuclnt!FwpmProviderContextEnum1.
func FwpmProviderContextEnum1(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT1, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextEnum1.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextEnum2 calls fwpuclnt!FwpmProviderContextEnum2.
func FwpmProviderContextEnum2(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT2, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextEnum2.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextEnum3 calls fwpuclnt!FwpmProviderContextEnum3.
func FwpmProviderContextEnum3(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT3, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextEnum3.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetById0 calls fwpuclnt!FwpmProviderContextGetById0.
func FwpmProviderContextGetById0(engineHandle win32foundation.HANDLE, id uint64, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetById1 calls fwpuclnt!FwpmProviderContextGetById1.
func FwpmProviderContextGetById1(engineHandle win32foundation.HANDLE, id uint64, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetById1.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetById2 calls fwpuclnt!FwpmProviderContextGetById2.
func FwpmProviderContextGetById2(engineHandle win32foundation.HANDLE, id uint64, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetById2.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetById3 calls fwpuclnt!FwpmProviderContextGetById3.
func FwpmProviderContextGetById3(engineHandle win32foundation.HANDLE, id uint64, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT3) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetById3.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetByKey0 calls fwpuclnt!FwpmProviderContextGetByKey0.
func FwpmProviderContextGetByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetByKey1 calls fwpuclnt!FwpmProviderContextGetByKey1.
func FwpmProviderContextGetByKey1(engineHandle win32foundation.HANDLE, key *win32.GUID, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetByKey1.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetByKey2 calls fwpuclnt!FwpmProviderContextGetByKey2.
func FwpmProviderContextGetByKey2(engineHandle win32foundation.HANDLE, key *win32.GUID, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetByKey2.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetByKey3 calls fwpuclnt!FwpmProviderContextGetByKey3.
func FwpmProviderContextGetByKey3(engineHandle win32foundation.HANDLE, key *win32.GUID, providerContext **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_CONTEXT3) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetByKey3.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(providerContext)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextGetSecurityInfoByKey0 calls fwpuclnt!FwpmProviderContextGetSecurityInfoByKey0.
func FwpmProviderContextGetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextGetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderContextSetSecurityInfoByKey0 calls fwpuclnt!FwpmProviderContextSetSecurityInfoByKey0.
func FwpmProviderContextSetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderContextSetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderCreateEnumHandle0 calls fwpuclnt!FwpmProviderCreateEnumHandle0.
func FwpmProviderCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderDeleteByKey0 calls fwpuclnt!FwpmProviderDeleteByKey0.
func FwpmProviderDeleteByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderDeleteByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderDestroyEnumHandle0 calls fwpuclnt!FwpmProviderDestroyEnumHandle0.
func FwpmProviderDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderEnum0 calls fwpuclnt!FwpmProviderEnum0.
func FwpmProviderEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderGetByKey0 calls fwpuclnt!FwpmProviderGetByKey0.
func FwpmProviderGetByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, provider **win32networkmanagementwindowsfilteringplatform.FWPM_PROVIDER0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderGetByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(provider)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderGetSecurityInfoByKey0 calls fwpuclnt!FwpmProviderGetSecurityInfoByKey0.
func FwpmProviderGetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderGetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmProviderSetSecurityInfoByKey0 calls fwpuclnt!FwpmProviderSetSecurityInfoByKey0.
func FwpmProviderSetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmProviderSetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSessionCreateEnumHandle0 calls fwpuclnt!FwpmSessionCreateEnumHandle0.
func FwpmSessionCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_SESSION_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSessionCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSessionDestroyEnumHandle0 calls fwpuclnt!FwpmSessionDestroyEnumHandle0.
func FwpmSessionDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSessionDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSessionEnum0 calls fwpuclnt!FwpmSessionEnum0.
func FwpmSessionEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_SESSION0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSessionEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerAdd0 calls fwpuclnt!FwpmSubLayerAdd0.
func FwpmSubLayerAdd0(engineHandle win32foundation.HANDLE, subLayer *win32networkmanagementwindowsfilteringplatform.FWPM_SUBLAYER0, sd win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerAdd0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(subLayer)), uintptr(sd))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerCreateEnumHandle0 calls fwpuclnt!FwpmSubLayerCreateEnumHandle0.
func FwpmSubLayerCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.FWPM_SUBLAYER_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerDeleteByKey0 calls fwpuclnt!FwpmSubLayerDeleteByKey0.
func FwpmSubLayerDeleteByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerDeleteByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerDestroyEnumHandle0 calls fwpuclnt!FwpmSubLayerDestroyEnumHandle0.
func FwpmSubLayerDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerEnum0 calls fwpuclnt!FwpmSubLayerEnum0.
func FwpmSubLayerEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.FWPM_SUBLAYER0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerGetByKey0 calls fwpuclnt!FwpmSubLayerGetByKey0.
func FwpmSubLayerGetByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, subLayer **win32networkmanagementwindowsfilteringplatform.FWPM_SUBLAYER0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerGetByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(unsafe.Pointer(subLayer)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerGetSecurityInfoByKey0 calls fwpuclnt!FwpmSubLayerGetSecurityInfoByKey0.
func FwpmSubLayerGetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerGetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmSubLayerSetSecurityInfoByKey0 calls fwpuclnt!FwpmSubLayerSetSecurityInfoByKey0.
func FwpmSubLayerSetSecurityInfoByKey0(engineHandle win32foundation.HANDLE, key *win32.GUID, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmSubLayerSetSecurityInfoByKey0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(key)), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmTransactionAbort0 calls fwpuclnt!FwpmTransactionAbort0.
func FwpmTransactionAbort0(engineHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmTransactionAbort0.Addr(), uintptr(engineHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmTransactionBegin0 calls fwpuclnt!FwpmTransactionBegin0.
func FwpmTransactionBegin0(engineHandle win32foundation.HANDLE, flags uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmTransactionBegin0.Addr(), uintptr(engineHandle), uintptr(flags))
	return win32foundation.NTSTATUS(r1)
}

// FwpmTransactionCommit0 calls fwpuclnt!FwpmTransactionCommit0.
func FwpmTransactionCommit0(engineHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmTransactionCommit0.Addr(), uintptr(engineHandle))
	return win32foundation.NTSTATUS(r1)
}

// FwpmvSwitchEventsGetSecurityInfo0 calls fwpuclnt!FwpmvSwitchEventsGetSecurityInfo0.
func FwpmvSwitchEventsGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmvSwitchEventsGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// FwpmvSwitchEventsSetSecurityInfo0 calls fwpuclnt!FwpmvSwitchEventsSetSecurityInfo0.
func FwpmvSwitchEventsSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procFwpmvSwitchEventsSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecDospGetSecurityInfo0 calls fwpuclnt!IPsecDospGetSecurityInfo0.
func IPsecDospGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecDospGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecDospGetStatistics0 calls fwpuclnt!IPsecDospGetStatistics0.
func IPsecDospGetStatistics0(engineHandle win32foundation.HANDLE, idpStatistics *win32networkmanagementwindowsfilteringplatform.IPSEC_DOSP_STATISTICS0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecDospGetStatistics0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(idpStatistics)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecDospSetSecurityInfo0 calls fwpuclnt!IPsecDospSetSecurityInfo0.
func IPsecDospSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecDospSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecDospStateCreateEnumHandle0 calls fwpuclnt!IPsecDospStateCreateEnumHandle0.
func IPsecDospStateCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.IPSEC_DOSP_STATE_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecDospStateCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecDospStateDestroyEnumHandle0 calls fwpuclnt!IPsecDospStateDestroyEnumHandle0.
func IPsecDospStateDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecDospStateDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// IPsecDospStateEnum0 calls fwpuclnt!IPsecDospStateEnum0.
func IPsecDospStateEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IPSEC_DOSP_STATE0, numEntries *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecDospStateEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntries)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecGetStatistics0 calls fwpuclnt!IPsecGetStatistics0.
func IPsecGetStatistics0(engineHandle win32foundation.HANDLE, ipsecStatistics *win32networkmanagementwindowsfilteringplatform.IPSEC_STATISTICS0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecGetStatistics0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(ipsecStatistics)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecGetStatistics1 calls fwpuclnt!IPsecGetStatistics1.
func IPsecGetStatistics1(engineHandle win32foundation.HANDLE, ipsecStatistics *win32networkmanagementwindowsfilteringplatform.IPSEC_STATISTICS1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecGetStatistics1.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(ipsecStatistics)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextAddInbound0 calls fwpuclnt!IPsecSaContextAddInbound0.
func IPsecSaContextAddInbound0(engineHandle win32foundation.HANDLE, id uint64, inboundBundle *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_BUNDLE0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextAddInbound0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(inboundBundle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextAddInbound1 calls fwpuclnt!IPsecSaContextAddInbound1.
func IPsecSaContextAddInbound1(engineHandle win32foundation.HANDLE, id uint64, inboundBundle *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_BUNDLE1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextAddInbound1.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(inboundBundle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextAddOutbound0 calls fwpuclnt!IPsecSaContextAddOutbound0.
func IPsecSaContextAddOutbound0(engineHandle win32foundation.HANDLE, id uint64, outboundBundle *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_BUNDLE0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextAddOutbound0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(outboundBundle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextAddOutbound1 calls fwpuclnt!IPsecSaContextAddOutbound1.
func IPsecSaContextAddOutbound1(engineHandle win32foundation.HANDLE, id uint64, outboundBundle *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_BUNDLE1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextAddOutbound1.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(outboundBundle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextCreate0 calls fwpuclnt!IPsecSaContextCreate0.
func IPsecSaContextCreate0(engineHandle win32foundation.HANDLE, outboundTraffic *win32networkmanagementwindowsfilteringplatform.IPSEC_TRAFFIC0, inboundFilterId *uint64, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextCreate0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(outboundTraffic)), uintptr(unsafe.Pointer(inboundFilterId)), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextCreate1 calls fwpuclnt!IPsecSaContextCreate1.
func IPsecSaContextCreate1(engineHandle win32foundation.HANDLE, outboundTraffic *win32networkmanagementwindowsfilteringplatform.IPSEC_TRAFFIC1, virtualIfTunnelInfo *win32networkmanagementwindowsfilteringplatform.IPSEC_VIRTUAL_IF_TUNNEL_INFO0, inboundFilterId *uint64, id *uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextCreate1.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(outboundTraffic)), uintptr(unsafe.Pointer(virtualIfTunnelInfo)), uintptr(unsafe.Pointer(inboundFilterId)), uintptr(unsafe.Pointer(id)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextCreateEnumHandle0 calls fwpuclnt!IPsecSaContextCreateEnumHandle0.
func IPsecSaContextCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_CONTEXT_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextDeleteById0 calls fwpuclnt!IPsecSaContextDeleteById0.
func IPsecSaContextDeleteById0(engineHandle win32foundation.HANDLE, id uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextDeleteById0.Addr(), uintptr(engineHandle), uintptr(id))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextDestroyEnumHandle0 calls fwpuclnt!IPsecSaContextDestroyEnumHandle0.
func IPsecSaContextDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextEnum0 calls fwpuclnt!IPsecSaContextEnum0.
func IPsecSaContextEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IPSEC_SA_CONTEXT0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextEnum1 calls fwpuclnt!IPsecSaContextEnum1.
func IPsecSaContextEnum1(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IPSEC_SA_CONTEXT1, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextEnum1.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextExpire0 calls fwpuclnt!IPsecSaContextExpire0.
func IPsecSaContextExpire0(engineHandle win32foundation.HANDLE, id uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextExpire0.Addr(), uintptr(engineHandle), uintptr(id))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextGetById0 calls fwpuclnt!IPsecSaContextGetById0.
func IPsecSaContextGetById0(engineHandle win32foundation.HANDLE, id uint64, saContext **win32networkmanagementwindowsfilteringplatform.IPSEC_SA_CONTEXT0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(saContext)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextGetById1 calls fwpuclnt!IPsecSaContextGetById1.
func IPsecSaContextGetById1(engineHandle win32foundation.HANDLE, id uint64, saContext **win32networkmanagementwindowsfilteringplatform.IPSEC_SA_CONTEXT1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextGetById1.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(saContext)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextGetSpi0 calls fwpuclnt!IPsecSaContextGetSpi0.
func IPsecSaContextGetSpi0(engineHandle win32foundation.HANDLE, id uint64, getSpi *win32networkmanagementwindowsfilteringplatform.IPSEC_GETSPI0, inboundSpi *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextGetSpi0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(getSpi)), uintptr(unsafe.Pointer(inboundSpi)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextGetSpi1 calls fwpuclnt!IPsecSaContextGetSpi1.
func IPsecSaContextGetSpi1(engineHandle win32foundation.HANDLE, id uint64, getSpi *win32networkmanagementwindowsfilteringplatform.IPSEC_GETSPI1, inboundSpi *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextGetSpi1.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(getSpi)), uintptr(unsafe.Pointer(inboundSpi)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextSetSpi0 calls fwpuclnt!IPsecSaContextSetSpi0.
func IPsecSaContextSetSpi0(engineHandle win32foundation.HANDLE, id uint64, getSpi *win32networkmanagementwindowsfilteringplatform.IPSEC_GETSPI1, inboundSpi uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextSetSpi0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(getSpi)), uintptr(inboundSpi))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaContextUpdate0 calls fwpuclnt!IPsecSaContextUpdate0.
func IPsecSaContextUpdate0(engineHandle win32foundation.HANDLE, flags uint64, newValues *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_CONTEXT1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaContextUpdate0.Addr(), uintptr(engineHandle), uintptr(flags), uintptr(unsafe.Pointer(newValues)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaCreateEnumHandle0 calls fwpuclnt!IPsecSaCreateEnumHandle0.
func IPsecSaCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.IPSEC_SA_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaDbGetSecurityInfo0 calls fwpuclnt!IPsecSaDbGetSecurityInfo0.
func IPsecSaDbGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaDbGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaDbSetSecurityInfo0 calls fwpuclnt!IPsecSaDbSetSecurityInfo0.
func IPsecSaDbSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaDbSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaDestroyEnumHandle0 calls fwpuclnt!IPsecSaDestroyEnumHandle0.
func IPsecSaDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaEnum0 calls fwpuclnt!IPsecSaEnum0.
func IPsecSaEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IPSEC_SA_DETAILS0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IPsecSaEnum1 calls fwpuclnt!IPsecSaEnum1.
func IPsecSaEnum1(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IPSEC_SA_DETAILS1, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIPsecSaEnum1.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextGetStatistics0 calls fwpuclnt!IkeextGetStatistics0.
func IkeextGetStatistics0(engineHandle win32foundation.HANDLE, ikeextStatistics *win32networkmanagementwindowsfilteringplatform.IKEEXT_STATISTICS0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextGetStatistics0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(ikeextStatistics)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextGetStatistics1 calls fwpuclnt!IkeextGetStatistics1.
func IkeextGetStatistics1(engineHandle win32foundation.HANDLE, ikeextStatistics *win32networkmanagementwindowsfilteringplatform.IKEEXT_STATISTICS1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextGetStatistics1.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(ikeextStatistics)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaCreateEnumHandle0 calls fwpuclnt!IkeextSaCreateEnumHandle0.
func IkeextSaCreateEnumHandle0(engineHandle win32foundation.HANDLE, enumTemplate *win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_ENUM_TEMPLATE0, enumHandle *win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaCreateEnumHandle0.Addr(), uintptr(engineHandle), uintptr(unsafe.Pointer(enumTemplate)), uintptr(unsafe.Pointer(enumHandle)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaDbGetSecurityInfo0 calls fwpuclnt!IkeextSaDbGetSecurityInfo0.
func IkeextSaDbGetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.PSID, sidGroup *win32security.PSID, dacl **win32security.ACL, sacl **win32security.ACL, securityDescriptor *win32security.PSECURITY_DESCRIPTOR) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaDbGetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)), uintptr(unsafe.Pointer(securityDescriptor)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaDbSetSecurityInfo0 calls fwpuclnt!IkeextSaDbSetSecurityInfo0.
func IkeextSaDbSetSecurityInfo0(engineHandle win32foundation.HANDLE, securityInfo uint32, sidOwner *win32security.SID, sidGroup *win32security.SID, dacl *win32security.ACL, sacl *win32security.ACL) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaDbSetSecurityInfo0.Addr(), uintptr(engineHandle), uintptr(securityInfo), uintptr(unsafe.Pointer(sidOwner)), uintptr(unsafe.Pointer(sidGroup)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(sacl)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaDeleteById0 calls fwpuclnt!IkeextSaDeleteById0.
func IkeextSaDeleteById0(engineHandle win32foundation.HANDLE, id uint64) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaDeleteById0.Addr(), uintptr(engineHandle), uintptr(id))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaDestroyEnumHandle0 calls fwpuclnt!IkeextSaDestroyEnumHandle0.
func IkeextSaDestroyEnumHandle0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaDestroyEnumHandle0.Addr(), uintptr(engineHandle), uintptr(enumHandle))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaEnum0 calls fwpuclnt!IkeextSaEnum0.
func IkeextSaEnum0(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_DETAILS0, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaEnum0.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaEnum1 calls fwpuclnt!IkeextSaEnum1.
func IkeextSaEnum1(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_DETAILS1, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaEnum1.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaEnum2 calls fwpuclnt!IkeextSaEnum2.
func IkeextSaEnum2(engineHandle win32foundation.HANDLE, enumHandle win32foundation.HANDLE, numEntriesRequested uint32, entries ***win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_DETAILS2, numEntriesReturned *uint32) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaEnum2.Addr(), uintptr(engineHandle), uintptr(enumHandle), uintptr(numEntriesRequested), uintptr(unsafe.Pointer(entries)), uintptr(unsafe.Pointer(numEntriesReturned)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaGetById0 calls fwpuclnt!IkeextSaGetById0.
func IkeextSaGetById0(engineHandle win32foundation.HANDLE, id uint64, sa **win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_DETAILS0) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaGetById0.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(sa)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaGetById1 calls fwpuclnt!IkeextSaGetById1.
func IkeextSaGetById1(engineHandle win32foundation.HANDLE, id uint64, saLookupContext *win32.GUID, sa **win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_DETAILS1) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaGetById1.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(saLookupContext)), uintptr(unsafe.Pointer(sa)))
	return win32foundation.NTSTATUS(r1)
}

// IkeextSaGetById2 calls fwpuclnt!IkeextSaGetById2.
func IkeextSaGetById2(engineHandle win32foundation.HANDLE, id uint64, saLookupContext *win32.GUID, sa **win32networkmanagementwindowsfilteringplatform.IKEEXT_SA_DETAILS2) win32foundation.NTSTATUS {
	r1, _, _ := syscall.SyscallN(procIkeextSaGetById2.Addr(), uintptr(engineHandle), uintptr(id), uintptr(unsafe.Pointer(saLookupContext)), uintptr(unsafe.Pointer(sa)))
	return win32foundation.NTSTATUS(r1)
}
