// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package windowsfilteringplatform

// FWPM_SERVICE_STATE_CHANGE_CALLBACK0 is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, win32networkmanagementwindowsfilteringplatform.FWPM_SERVICE_STATE).
type FWPM_SERVICE_STATE_CHANGE_CALLBACK0 uintptr
