// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package filesystem

// ALLOCATE_VIRTUAL_MEMORY_EX_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.HANDLE, win32foundation.HANDLE, *unsafe.Pointer, *uintptr, uint32, uint32, *win32systemmemory.MEM_EXTENDED_PARAMETER, uint32) win32foundation.NTSTATUS.
type ALLOCATE_VIRTUAL_MEMORY_EX_CALLBACK uintptr

// FREE_VIRTUAL_MEMORY_EX_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.HANDLE, win32foundation.HANDLE, *unsafe.Pointer, *uintptr, uint32) win32foundation.NTSTATUS.
type FREE_VIRTUAL_MEMORY_EX_CALLBACK uintptr

// PACQUIRE_FOR_LAZY_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, win32foundation.BOOLEAN) win32foundation.BOOLEAN.
type PACQUIRE_FOR_LAZY_WRITE uintptr

// PACQUIRE_FOR_LAZY_WRITE_EX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, uint32, *uint32) win32foundation.BOOLEAN.
type PACQUIRE_FOR_LAZY_WRITE_EX uintptr

// PACQUIRE_FOR_READ_AHEAD is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, win32foundation.BOOLEAN) win32foundation.BOOLEAN.
type PACQUIRE_FOR_READ_AHEAD uintptr

// PALLOCATE_VIRTUAL_MEMORY_EX_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PALLOCATE_VIRTUAL_MEMORY_EX_CALLBACK uintptr

// PASYNC_READ_COMPLETION_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer) win32foundation.BOOLEAN.
type PASYNC_READ_COMPLETION_CALLBACK uintptr

// PCC_POST_DEFERRED_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer).
type PCC_POST_DEFERRED_WRITE uintptr

// PCHECK_FOR_TRAVERSE_ACCESS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer, *foundation.SECURITY_SUBJECT_CONTEXT) win32foundation.BOOLEAN.
type PCHECK_FOR_TRAVERSE_ACCESS uintptr

// PCOMPLETE_LOCK_IRP_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *foundation.IRP) win32foundation.NTSTATUS.
type PCOMPLETE_LOCK_IRP_ROUTINE uintptr

// PDIRTY_PAGE_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*foundation.FILE_OBJECT, *int64, uint32, *int64, *int64, unsafe.Pointer, unsafe.Pointer).
type PDIRTY_PAGE_ROUTINE uintptr

// PFILTER_REPORT_CHANGE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, unsafe.Pointer) win32foundation.BOOLEAN.
type PFILTER_REPORT_CHANGE uintptr

// PFLUSH_TO_LSN is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, int64).
type PFLUSH_TO_LSN uintptr

// PFN_FSRTLTEARDOWNPERSTREAMCONTEXTS is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FSRTL_ADVANCED_FCB_HEADER).
type PFN_FSRTLTEARDOWNPERSTREAMCONTEXTS uintptr

// PFREE_VIRTUAL_MEMORY_EX_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PFREE_VIRTUAL_MEMORY_EX_CALLBACK uintptr

// PFSRTL_EXTRA_CREATE_PARAMETER_CLEANUP_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *win32.GUID).
type PFSRTL_EXTRA_CREATE_PARAMETER_CLEANUP_CALLBACK uintptr

// PFSRTL_STACK_OVERFLOW_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *foundation.KEVENT).
type PFSRTL_STACK_OVERFLOW_ROUTINE uintptr

// PFS_FILTER_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FS_FILTER_CALLBACK_DATA, *unsafe.Pointer) win32foundation.NTSTATUS.
type PFS_FILTER_CALLBACK uintptr

// PFS_FILTER_COMPLETION_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*FS_FILTER_CALLBACK_DATA, win32foundation.NTSTATUS, unsafe.Pointer).
type PFS_FILTER_COMPLETION_CALLBACK uintptr

// POPLOCK_FS_PREPOST_IRP is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *foundation.IRP).
type POPLOCK_FS_PREPOST_IRP uintptr

// POPLOCK_NOTIFY_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*OPLOCK_NOTIFY_PARAMS) win32foundation.NTSTATUS.
type POPLOCK_NOTIFY_ROUTINE uintptr

// POPLOCK_WAIT_COMPLETE_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *foundation.IRP).
type POPLOCK_WAIT_COMPLETE_ROUTINE uintptr

// PQUERY_LOG_USAGE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *uint16).
type PQUERY_LOG_USAGE uintptr

// PQUERY_VIRTUAL_MEMORY_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PQUERY_VIRTUAL_MEMORY_CALLBACK uintptr

// PRELEASE_FROM_LAZY_WRITE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer).
type PRELEASE_FROM_LAZY_WRITE uintptr

// PRELEASE_FROM_READ_AHEAD is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer).
type PRELEASE_FROM_READ_AHEAD uintptr

// PRTL_ALLOCATE_STRING_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() unsafe.Pointer.
type PRTL_ALLOCATE_STRING_ROUTINE uintptr

// PRTL_FREE_STRING_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func().
type PRTL_FREE_STRING_ROUTINE uintptr

// PRTL_HEAP_COMMIT_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PRTL_HEAP_COMMIT_ROUTINE uintptr

// PRTL_REALLOCATE_STRING_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() unsafe.Pointer.
type PRTL_REALLOCATE_STRING_ROUTINE uintptr

// PSE_LOGON_SESSION_TERMINATED_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PSE_LOGON_SESSION_TERMINATED_ROUTINE uintptr

// PSE_LOGON_SESSION_TERMINATED_ROUTINE_EX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func() win32foundation.NTSTATUS.
type PSE_LOGON_SESSION_TERMINATED_ROUTINE_EX uintptr

// PUNLOCK_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *FILE_LOCK_INFO).
type PUNLOCK_ROUTINE uintptr

// QUERY_VIRTUAL_MEMORY_CALLBACK is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(win32foundation.HANDLE, win32foundation.HANDLE, unsafe.Pointer, HEAP_MEMORY_INFO_CLASS, unsafe.Pointer, uintptr, *uintptr) win32foundation.NTSTATUS.
type QUERY_VIRTUAL_MEMORY_CALLBACK uintptr

// RTL_ALLOCATE_STRING_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uintptr) unsafe.Pointer.
type RTL_ALLOCATE_STRING_ROUTINE uintptr

// RTL_FREE_STRING_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer).
type RTL_FREE_STRING_ROUTINE uintptr

// RTL_HEAP_COMMIT_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(unsafe.Pointer, *unsafe.Pointer, *uintptr) win32foundation.NTSTATUS.
type RTL_HEAP_COMMIT_ROUTINE uintptr

// RTL_REALLOCATE_STRING_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(uintptr, unsafe.Pointer) unsafe.Pointer.
type RTL_REALLOCATE_STRING_ROUTINE uintptr

// SE_LOGON_SESSION_TERMINATED_ROUTINE is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*win32foundation.LUID) win32foundation.NTSTATUS.
type SE_LOGON_SESSION_TERMINATED_ROUTINE uintptr

// SE_LOGON_SESSION_TERMINATED_ROUTINE_EX is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*win32foundation.LUID, foundation.PESILO, unsafe.Pointer) win32foundation.NTSTATUS.
type SE_LOGON_SESSION_TERMINATED_ROUTINE_EX uintptr

// SspiAsyncNotifyCallback is a callback pointer: create one with NewCallback (package
// syscall) using the shape func(*foundation.SspiAsyncContext, unsafe.Pointer).
type SspiAsyncNotifyCallback uintptr
