// Code generated by go-bindings-wdk-codegen. DO NOT EDIT.

//go:build windows && (amd64 || arm64)

package filesystem

import (
	"fmt"
	"strings"
)

type CSV_DOWN_LEVEL_FILE_TYPE int32

const (
	CsvDownLevelFileObject     CSV_DOWN_LEVEL_FILE_TYPE = 0
	CsvCsvFsInternalFileObject CSV_DOWN_LEVEL_FILE_TYPE = 1
)

// String returns the CSV_DOWN_LEVEL_FILE_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e CSV_DOWN_LEVEL_FILE_TYPE) String() string {
	switch e {
	case CsvDownLevelFileObject:
		return "CsvDownLevelFileObject"
	case CsvCsvFsInternalFileObject:
		return "CsvCsvFsInternalFileObject"
	default:
		return fmt.Sprintf("CSV_DOWN_LEVEL_FILE_TYPE(%d)", int32(e))
	}
}

type FAST_IO_POSSIBLE int32

const (
	FastIoIsNotPossible  FAST_IO_POSSIBLE = 0
	FastIoIsPossible     FAST_IO_POSSIBLE = 1
	FastIoIsQuestionable FAST_IO_POSSIBLE = 2
)

// String returns the FAST_IO_POSSIBLE constant's name, or its numeric form when
// the value is not a known constant.
func (e FAST_IO_POSSIBLE) String() string {
	switch e {
	case FastIoIsNotPossible:
		return "FastIoIsNotPossible"
	case FastIoIsPossible:
		return "FastIoIsPossible"
	case FastIoIsQuestionable:
		return "FastIoIsQuestionable"
	default:
		return fmt.Sprintf("FAST_IO_POSSIBLE(%d)", int32(e))
	}
}

type FILE_DISPOSITION_INFORMATION_EX_FLAGS uint32

const (
	FILE_DISPOSITION_DO_NOT_DELETE             FILE_DISPOSITION_INFORMATION_EX_FLAGS = 0
	FILE_DISPOSITION_DELETE                    FILE_DISPOSITION_INFORMATION_EX_FLAGS = 1
	FILE_DISPOSITION_POSIX_SEMANTICS           FILE_DISPOSITION_INFORMATION_EX_FLAGS = 2
	FILE_DISPOSITION_FORCE_IMAGE_SECTION_CHECK FILE_DISPOSITION_INFORMATION_EX_FLAGS = 4
	FILE_DISPOSITION_ON_CLOSE                  FILE_DISPOSITION_INFORMATION_EX_FLAGS = 8
	FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE FILE_DISPOSITION_INFORMATION_EX_FLAGS = 16
)

// String returns the FILE_DISPOSITION_INFORMATION_EX_FLAGS constant's name, or its numeric form when
// the value is not a known constant.
func (e FILE_DISPOSITION_INFORMATION_EX_FLAGS) String() string {
	switch e {
	case FILE_DISPOSITION_DO_NOT_DELETE:
		return "FILE_DISPOSITION_DO_NOT_DELETE"
	case FILE_DISPOSITION_DELETE:
		return "FILE_DISPOSITION_DELETE"
	case FILE_DISPOSITION_POSIX_SEMANTICS:
		return "FILE_DISPOSITION_POSIX_SEMANTICS"
	case FILE_DISPOSITION_FORCE_IMAGE_SECTION_CHECK:
		return "FILE_DISPOSITION_FORCE_IMAGE_SECTION_CHECK"
	case FILE_DISPOSITION_ON_CLOSE:
		return "FILE_DISPOSITION_ON_CLOSE"
	case FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE:
		return "FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE"
	default:
		return fmt.Sprintf("FILE_DISPOSITION_INFORMATION_EX_FLAGS(%d)", uint32(e))
	}
}

type FILE_INFORMATION_CLASS int32

const (
	FileDirectoryInformation                     FILE_INFORMATION_CLASS = 1
	FileFullDirectoryInformation                 FILE_INFORMATION_CLASS = 2
	FileBothDirectoryInformation                 FILE_INFORMATION_CLASS = 3
	FileBasicInformation                         FILE_INFORMATION_CLASS = 4
	FileStandardInformation                      FILE_INFORMATION_CLASS = 5
	FileInternalInformation                      FILE_INFORMATION_CLASS = 6
	FileEaInformation                            FILE_INFORMATION_CLASS = 7
	FileAccessInformation                        FILE_INFORMATION_CLASS = 8
	FileNameInformation                          FILE_INFORMATION_CLASS = 9
	FileRenameInformation                        FILE_INFORMATION_CLASS = 10
	FileLinkInformation                          FILE_INFORMATION_CLASS = 11
	FileNamesInformation                         FILE_INFORMATION_CLASS = 12
	FileDispositionInformation                   FILE_INFORMATION_CLASS = 13
	FilePositionInformation                      FILE_INFORMATION_CLASS = 14
	FileFullEaInformation                        FILE_INFORMATION_CLASS = 15
	FileModeInformation                          FILE_INFORMATION_CLASS = 16
	FileAlignmentInformation                     FILE_INFORMATION_CLASS = 17
	FileAllInformation                           FILE_INFORMATION_CLASS = 18
	FileAllocationInformation                    FILE_INFORMATION_CLASS = 19
	FileEndOfFileInformation                     FILE_INFORMATION_CLASS = 20
	FileAlternateNameInformation                 FILE_INFORMATION_CLASS = 21
	FileStreamInformation                        FILE_INFORMATION_CLASS = 22
	FilePipeInformation                          FILE_INFORMATION_CLASS = 23
	FilePipeLocalInformation                     FILE_INFORMATION_CLASS = 24
	FilePipeRemoteInformation                    FILE_INFORMATION_CLASS = 25
	FileMailslotQueryInformation                 FILE_INFORMATION_CLASS = 26
	FileMailslotSetInformation                   FILE_INFORMATION_CLASS = 27
	FileCompressionInformation                   FILE_INFORMATION_CLASS = 28
	FileObjectIdInformation                      FILE_INFORMATION_CLASS = 29
	FileCompletionInformation                    FILE_INFORMATION_CLASS = 30
	FileMoveClusterInformation                   FILE_INFORMATION_CLASS = 31
	FileQuotaInformation                         FILE_INFORMATION_CLASS = 32
	FileReparsePointInformation                  FILE_INFORMATION_CLASS = 33
	FileNetworkOpenInformation                   FILE_INFORMATION_CLASS = 34
	FileAttributeTagInformation                  FILE_INFORMATION_CLASS = 35
	FileTrackingInformation                      FILE_INFORMATION_CLASS = 36
	FileIdBothDirectoryInformation               FILE_INFORMATION_CLASS = 37
	FileIdFullDirectoryInformation               FILE_INFORMATION_CLASS = 38
	FileValidDataLengthInformation               FILE_INFORMATION_CLASS = 39
	FileShortNameInformation                     FILE_INFORMATION_CLASS = 40
	FileIoCompletionNotificationInformation      FILE_INFORMATION_CLASS = 41
	FileIoStatusBlockRangeInformation            FILE_INFORMATION_CLASS = 42
	FileIoPriorityHintInformation                FILE_INFORMATION_CLASS = 43
	FileSfioReserveInformation                   FILE_INFORMATION_CLASS = 44
	FileSfioVolumeInformation                    FILE_INFORMATION_CLASS = 45
	FileHardLinkInformation                      FILE_INFORMATION_CLASS = 46
	FileProcessIdsUsingFileInformation           FILE_INFORMATION_CLASS = 47
	FileNormalizedNameInformation                FILE_INFORMATION_CLASS = 48
	FileNetworkPhysicalNameInformation           FILE_INFORMATION_CLASS = 49
	FileIdGlobalTxDirectoryInformation           FILE_INFORMATION_CLASS = 50
	FileIsRemoteDeviceInformation                FILE_INFORMATION_CLASS = 51
	FileUnusedInformation                        FILE_INFORMATION_CLASS = 52
	FileNumaNodeInformation                      FILE_INFORMATION_CLASS = 53
	FileStandardLinkInformation                  FILE_INFORMATION_CLASS = 54
	FileRemoteProtocolInformation                FILE_INFORMATION_CLASS = 55
	FileRenameInformationBypassAccessCheck       FILE_INFORMATION_CLASS = 56
	FileLinkInformationBypassAccessCheck         FILE_INFORMATION_CLASS = 57
	FileVolumeNameInformation                    FILE_INFORMATION_CLASS = 58
	FileIdInformation                            FILE_INFORMATION_CLASS = 59
	FileIdExtdDirectoryInformation               FILE_INFORMATION_CLASS = 60
	FileReplaceCompletionInformation             FILE_INFORMATION_CLASS = 61
	FileHardLinkFullIdInformation                FILE_INFORMATION_CLASS = 62
	FileIdExtdBothDirectoryInformation           FILE_INFORMATION_CLASS = 63
	FileDispositionInformationEx                 FILE_INFORMATION_CLASS = 64
	FileRenameInformationEx                      FILE_INFORMATION_CLASS = 65
	FileRenameInformationExBypassAccessCheck     FILE_INFORMATION_CLASS = 66
	FileDesiredStorageClassInformation           FILE_INFORMATION_CLASS = 67
	FileStatInformation                          FILE_INFORMATION_CLASS = 68
	FileMemoryPartitionInformation               FILE_INFORMATION_CLASS = 69
	FileStatLxInformation                        FILE_INFORMATION_CLASS = 70
	FileCaseSensitiveInformation                 FILE_INFORMATION_CLASS = 71
	FileLinkInformationEx                        FILE_INFORMATION_CLASS = 72
	FileLinkInformationExBypassAccessCheck       FILE_INFORMATION_CLASS = 73
	FileStorageReserveIdInformation              FILE_INFORMATION_CLASS = 74
	FileCaseSensitiveInformationForceAccessCheck FILE_INFORMATION_CLASS = 75
	FileKnownFolderInformation                   FILE_INFORMATION_CLASS = 76
	FileMaximumInformation                       FILE_INFORMATION_CLASS = 77
)

// String returns the FILE_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e FILE_INFORMATION_CLASS) String() string {
	switch e {
	case FileDirectoryInformation:
		return "FileDirectoryInformation"
	case FileFullDirectoryInformation:
		return "FileFullDirectoryInformation"
	case FileBothDirectoryInformation:
		return "FileBothDirectoryInformation"
	case FileBasicInformation:
		return "FileBasicInformation"
	case FileStandardInformation:
		return "FileStandardInformation"
	case FileInternalInformation:
		return "FileInternalInformation"
	case FileEaInformation:
		return "FileEaInformation"
	case FileAccessInformation:
		return "FileAccessInformation"
	case FileNameInformation:
		return "FileNameInformation"
	case FileRenameInformation:
		return "FileRenameInformation"
	case FileLinkInformation:
		return "FileLinkInformation"
	case FileNamesInformation:
		return "FileNamesInformation"
	case FileDispositionInformation:
		return "FileDispositionInformation"
	case FilePositionInformation:
		return "FilePositionInformation"
	case FileFullEaInformation:
		return "FileFullEaInformation"
	case FileModeInformation:
		return "FileModeInformation"
	case FileAlignmentInformation:
		return "FileAlignmentInformation"
	case FileAllInformation:
		return "FileAllInformation"
	case FileAllocationInformation:
		return "FileAllocationInformation"
	case FileEndOfFileInformation:
		return "FileEndOfFileInformation"
	case FileAlternateNameInformation:
		return "FileAlternateNameInformation"
	case FileStreamInformation:
		return "FileStreamInformation"
	case FilePipeInformation:
		return "FilePipeInformation"
	case FilePipeLocalInformation:
		return "FilePipeLocalInformation"
	case FilePipeRemoteInformation:
		return "FilePipeRemoteInformation"
	case FileMailslotQueryInformation:
		return "FileMailslotQueryInformation"
	case FileMailslotSetInformation:
		return "FileMailslotSetInformation"
	case FileCompressionInformation:
		return "FileCompressionInformation"
	case FileObjectIdInformation:
		return "FileObjectIdInformation"
	case FileCompletionInformation:
		return "FileCompletionInformation"
	case FileMoveClusterInformation:
		return "FileMoveClusterInformation"
	case FileQuotaInformation:
		return "FileQuotaInformation"
	case FileReparsePointInformation:
		return "FileReparsePointInformation"
	case FileNetworkOpenInformation:
		return "FileNetworkOpenInformation"
	case FileAttributeTagInformation:
		return "FileAttributeTagInformation"
	case FileTrackingInformation:
		return "FileTrackingInformation"
	case FileIdBothDirectoryInformation:
		return "FileIdBothDirectoryInformation"
	case FileIdFullDirectoryInformation:
		return "FileIdFullDirectoryInformation"
	case FileValidDataLengthInformation:
		return "FileValidDataLengthInformation"
	case FileShortNameInformation:
		return "FileShortNameInformation"
	case FileIoCompletionNotificationInformation:
		return "FileIoCompletionNotificationInformation"
	case FileIoStatusBlockRangeInformation:
		return "FileIoStatusBlockRangeInformation"
	case FileIoPriorityHintInformation:
		return "FileIoPriorityHintInformation"
	case FileSfioReserveInformation:
		return "FileSfioReserveInformation"
	case FileSfioVolumeInformation:
		return "FileSfioVolumeInformation"
	case FileHardLinkInformation:
		return "FileHardLinkInformation"
	case FileProcessIdsUsingFileInformation:
		return "FileProcessIdsUsingFileInformation"
	case FileNormalizedNameInformation:
		return "FileNormalizedNameInformation"
	case FileNetworkPhysicalNameInformation:
		return "FileNetworkPhysicalNameInformation"
	case FileIdGlobalTxDirectoryInformation:
		return "FileIdGlobalTxDirectoryInformation"
	case FileIsRemoteDeviceInformation:
		return "FileIsRemoteDeviceInformation"
	case FileUnusedInformation:
		return "FileUnusedInformation"
	case FileNumaNodeInformation:
		return "FileNumaNodeInformation"
	case FileStandardLinkInformation:
		return "FileStandardLinkInformation"
	case FileRemoteProtocolInformation:
		return "FileRemoteProtocolInformation"
	case FileRenameInformationBypassAccessCheck:
		return "FileRenameInformationBypassAccessCheck"
	case FileLinkInformationBypassAccessCheck:
		return "FileLinkInformationBypassAccessCheck"
	case FileVolumeNameInformation:
		return "FileVolumeNameInformation"
	case FileIdInformation:
		return "FileIdInformation"
	case FileIdExtdDirectoryInformation:
		return "FileIdExtdDirectoryInformation"
	case FileReplaceCompletionInformation:
		return "FileReplaceCompletionInformation"
	case FileHardLinkFullIdInformation:
		return "FileHardLinkFullIdInformation"
	case FileIdExtdBothDirectoryInformation:
		return "FileIdExtdBothDirectoryInformation"
	case FileDispositionInformationEx:
		return "FileDispositionInformationEx"
	case FileRenameInformationEx:
		return "FileRenameInformationEx"
	case FileRenameInformationExBypassAccessCheck:
		return "FileRenameInformationExBypassAccessCheck"
	case FileDesiredStorageClassInformation:
		return "FileDesiredStorageClassInformation"
	case FileStatInformation:
		return "FileStatInformation"
	case FileMemoryPartitionInformation:
		return "FileMemoryPartitionInformation"
	case FileStatLxInformation:
		return "FileStatLxInformation"
	case FileCaseSensitiveInformation:
		return "FileCaseSensitiveInformation"
	case FileLinkInformationEx:
		return "FileLinkInformationEx"
	case FileLinkInformationExBypassAccessCheck:
		return "FileLinkInformationExBypassAccessCheck"
	case FileStorageReserveIdInformation:
		return "FileStorageReserveIdInformation"
	case FileCaseSensitiveInformationForceAccessCheck:
		return "FileCaseSensitiveInformationForceAccessCheck"
	case FileKnownFolderInformation:
		return "FileKnownFolderInformation"
	case FileMaximumInformation:
		return "FileMaximumInformation"
	default:
		return fmt.Sprintf("FILE_INFORMATION_CLASS(%d)", int32(e))
	}
}

type FILE_KNOWN_FOLDER_TYPE int32

const (
	KnownFolderNone      FILE_KNOWN_FOLDER_TYPE = 0
	KnownFolderDesktop   FILE_KNOWN_FOLDER_TYPE = 1
	KnownFolderDocuments FILE_KNOWN_FOLDER_TYPE = 2
	KnownFolderDownloads FILE_KNOWN_FOLDER_TYPE = 3
	KnownFolderMusic     FILE_KNOWN_FOLDER_TYPE = 4
	KnownFolderPictures  FILE_KNOWN_FOLDER_TYPE = 5
	KnownFolderVideos    FILE_KNOWN_FOLDER_TYPE = 6
	KnownFolderOther     FILE_KNOWN_FOLDER_TYPE = 7
	KnownFolderMax       FILE_KNOWN_FOLDER_TYPE = 7
)

// String returns the FILE_KNOWN_FOLDER_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e FILE_KNOWN_FOLDER_TYPE) String() string {
	switch e {
	case KnownFolderNone:
		return "KnownFolderNone"
	case KnownFolderDesktop:
		return "KnownFolderDesktop"
	case KnownFolderDocuments:
		return "KnownFolderDocuments"
	case KnownFolderDownloads:
		return "KnownFolderDownloads"
	case KnownFolderMusic:
		return "KnownFolderMusic"
	case KnownFolderPictures:
		return "KnownFolderPictures"
	case KnownFolderVideos:
		return "KnownFolderVideos"
	case KnownFolderOther:
		return "KnownFolderOther"
	default:
		return fmt.Sprintf("FILE_KNOWN_FOLDER_TYPE(%d)", int32(e))
	}
}

type FSRTL_CHANGE_BACKING_TYPE int32

const (
	ChangeDataControlArea  FSRTL_CHANGE_BACKING_TYPE = 0
	ChangeImageControlArea FSRTL_CHANGE_BACKING_TYPE = 1
	ChangeSharedCacheMap   FSRTL_CHANGE_BACKING_TYPE = 2
)

// String returns the FSRTL_CHANGE_BACKING_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e FSRTL_CHANGE_BACKING_TYPE) String() string {
	switch e {
	case ChangeDataControlArea:
		return "ChangeDataControlArea"
	case ChangeImageControlArea:
		return "ChangeImageControlArea"
	case ChangeSharedCacheMap:
		return "ChangeSharedCacheMap"
	default:
		return fmt.Sprintf("FSRTL_CHANGE_BACKING_TYPE(%d)", int32(e))
	}
}

type FSRTL_COMPARISON_RESULT int32

const (
	LessThan    FSRTL_COMPARISON_RESULT = -1
	EqualTo     FSRTL_COMPARISON_RESULT = 0
	GreaterThan FSRTL_COMPARISON_RESULT = 1
)

// String returns the FSRTL_COMPARISON_RESULT constant's name, or its numeric form when
// the value is not a known constant.
func (e FSRTL_COMPARISON_RESULT) String() string {
	switch e {
	case LessThan:
		return "LessThan"
	case EqualTo:
		return "EqualTo"
	case GreaterThan:
		return "GreaterThan"
	default:
		return fmt.Sprintf("FSRTL_COMPARISON_RESULT(%d)", int32(e))
	}
}

type FS_FILTER_SECTION_SYNC_TYPE int32

const (
	SyncTypeOther         FS_FILTER_SECTION_SYNC_TYPE = 0
	SyncTypeCreateSection FS_FILTER_SECTION_SYNC_TYPE = 1
)

// String returns the FS_FILTER_SECTION_SYNC_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e FS_FILTER_SECTION_SYNC_TYPE) String() string {
	switch e {
	case SyncTypeOther:
		return "SyncTypeOther"
	case SyncTypeCreateSection:
		return "SyncTypeCreateSection"
	default:
		return fmt.Sprintf("FS_FILTER_SECTION_SYNC_TYPE(%d)", int32(e))
	}
}

type FS_FILTER_STREAM_FO_NOTIFICATION_TYPE int32

const (
	NotifyTypeCreate  FS_FILTER_STREAM_FO_NOTIFICATION_TYPE = 0
	NotifyTypeRetired FS_FILTER_STREAM_FO_NOTIFICATION_TYPE = 1
)

// String returns the FS_FILTER_STREAM_FO_NOTIFICATION_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e FS_FILTER_STREAM_FO_NOTIFICATION_TYPE) String() string {
	switch e {
	case NotifyTypeCreate:
		return "NotifyTypeCreate"
	case NotifyTypeRetired:
		return "NotifyTypeRetired"
	default:
		return fmt.Sprintf("FS_FILTER_STREAM_FO_NOTIFICATION_TYPE(%d)", int32(e))
	}
}

type FS_INFORMATION_CLASS int32

const (
	FileFsVolumeInformation       FS_INFORMATION_CLASS = 1
	FileFsLabelInformation        FS_INFORMATION_CLASS = 2
	FileFsSizeInformation         FS_INFORMATION_CLASS = 3
	FileFsDeviceInformation       FS_INFORMATION_CLASS = 4
	FileFsAttributeInformation    FS_INFORMATION_CLASS = 5
	FileFsControlInformation      FS_INFORMATION_CLASS = 6
	FileFsFullSizeInformation     FS_INFORMATION_CLASS = 7
	FileFsObjectIdInformation     FS_INFORMATION_CLASS = 8
	FileFsDriverPathInformation   FS_INFORMATION_CLASS = 9
	FileFsVolumeFlagsInformation  FS_INFORMATION_CLASS = 10
	FileFsSectorSizeInformation   FS_INFORMATION_CLASS = 11
	FileFsDataCopyInformation     FS_INFORMATION_CLASS = 12
	FileFsMetadataSizeInformation FS_INFORMATION_CLASS = 13
	FileFsFullSizeInformationEx   FS_INFORMATION_CLASS = 14
	FileFsMaximumInformation      FS_INFORMATION_CLASS = 15
)

// String returns the FS_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e FS_INFORMATION_CLASS) String() string {
	switch e {
	case FileFsVolumeInformation:
		return "FileFsVolumeInformation"
	case FileFsLabelInformation:
		return "FileFsLabelInformation"
	case FileFsSizeInformation:
		return "FileFsSizeInformation"
	case FileFsDeviceInformation:
		return "FileFsDeviceInformation"
	case FileFsAttributeInformation:
		return "FileFsAttributeInformation"
	case FileFsControlInformation:
		return "FileFsControlInformation"
	case FileFsFullSizeInformation:
		return "FileFsFullSizeInformation"
	case FileFsObjectIdInformation:
		return "FileFsObjectIdInformation"
	case FileFsDriverPathInformation:
		return "FileFsDriverPathInformation"
	case FileFsVolumeFlagsInformation:
		return "FileFsVolumeFlagsInformation"
	case FileFsSectorSizeInformation:
		return "FileFsSectorSizeInformation"
	case FileFsDataCopyInformation:
		return "FileFsDataCopyInformation"
	case FileFsMetadataSizeInformation:
		return "FileFsMetadataSizeInformation"
	case FileFsFullSizeInformationEx:
		return "FileFsFullSizeInformationEx"
	case FileFsMaximumInformation:
		return "FileFsMaximumInformation"
	default:
		return fmt.Sprintf("FS_INFORMATION_CLASS(%d)", int32(e))
	}
}

type HEAP_MEMORY_INFO_CLASS int32

const (
	HeapMemoryBasicInformation HEAP_MEMORY_INFO_CLASS = 0
)

// String returns the HEAP_MEMORY_INFO_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e HEAP_MEMORY_INFO_CLASS) String() string {
	switch e {
	case HeapMemoryBasicInformation:
		return "HeapMemoryBasicInformation"
	default:
		return fmt.Sprintf("HEAP_MEMORY_INFO_CLASS(%d)", int32(e))
	}
}

type LINK_TRACKING_INFORMATION_TYPE int32

const (
	NtfsLinkTrackingInformation LINK_TRACKING_INFORMATION_TYPE = 0
	DfsLinkTrackingInformation  LINK_TRACKING_INFORMATION_TYPE = 1
)

// String returns the LINK_TRACKING_INFORMATION_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e LINK_TRACKING_INFORMATION_TYPE) String() string {
	switch e {
	case NtfsLinkTrackingInformation:
		return "NtfsLinkTrackingInformation"
	case DfsLinkTrackingInformation:
		return "DfsLinkTrackingInformation"
	default:
		return fmt.Sprintf("LINK_TRACKING_INFORMATION_TYPE(%d)", int32(e))
	}
}

type MEMORY_INFORMATION_CLASS int32

const (
	MemoryBasicInformation MEMORY_INFORMATION_CLASS = 0
)

// String returns the MEMORY_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e MEMORY_INFORMATION_CLASS) String() string {
	switch e {
	case MemoryBasicInformation:
		return "MemoryBasicInformation"
	default:
		return fmt.Sprintf("MEMORY_INFORMATION_CLASS(%d)", int32(e))
	}
}

type MMFLUSH_TYPE int32

const (
	MmFlushForDelete MMFLUSH_TYPE = 0
	MmFlushForWrite  MMFLUSH_TYPE = 1
)

// String returns the MMFLUSH_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e MMFLUSH_TYPE) String() string {
	switch e {
	case MmFlushForDelete:
		return "MmFlushForDelete"
	case MmFlushForWrite:
		return "MmFlushForWrite"
	default:
		return fmt.Sprintf("MMFLUSH_TYPE(%d)", int32(e))
	}
}

type MSV1_0_AVID int32

const (
	MsvAvEOL             MSV1_0_AVID = 0
	MsvAvNbComputerName  MSV1_0_AVID = 1
	MsvAvNbDomainName    MSV1_0_AVID = 2
	MsvAvDnsComputerName MSV1_0_AVID = 3
	MsvAvDnsDomainName   MSV1_0_AVID = 4
	MsvAvDnsTreeName     MSV1_0_AVID = 5
	MsvAvFlags           MSV1_0_AVID = 6
	MsvAvTimestamp       MSV1_0_AVID = 7
	MsvAvRestrictions    MSV1_0_AVID = 8
	MsvAvTargetName      MSV1_0_AVID = 9
	MsvAvChannelBindings MSV1_0_AVID = 10
)

// String returns the MSV1_0_AVID constant's name, or its numeric form when
// the value is not a known constant.
func (e MSV1_0_AVID) String() string {
	switch e {
	case MsvAvEOL:
		return "MsvAvEOL"
	case MsvAvNbComputerName:
		return "MsvAvNbComputerName"
	case MsvAvNbDomainName:
		return "MsvAvNbDomainName"
	case MsvAvDnsComputerName:
		return "MsvAvDnsComputerName"
	case MsvAvDnsDomainName:
		return "MsvAvDnsDomainName"
	case MsvAvDnsTreeName:
		return "MsvAvDnsTreeName"
	case MsvAvFlags:
		return "MsvAvFlags"
	case MsvAvTimestamp:
		return "MsvAvTimestamp"
	case MsvAvRestrictions:
		return "MsvAvRestrictions"
	case MsvAvTargetName:
		return "MsvAvTargetName"
	case MsvAvChannelBindings:
		return "MsvAvChannelBindings"
	default:
		return fmt.Sprintf("MSV1_0_AVID(%d)", int32(e))
	}
}

type NETWORK_OPEN_INTEGRITY_QUALIFIER int32

const (
	NetworkOpenIntegrityAny       NETWORK_OPEN_INTEGRITY_QUALIFIER = 0
	NetworkOpenIntegrityNone      NETWORK_OPEN_INTEGRITY_QUALIFIER = 1
	NetworkOpenIntegritySigned    NETWORK_OPEN_INTEGRITY_QUALIFIER = 2
	NetworkOpenIntegrityEncrypted NETWORK_OPEN_INTEGRITY_QUALIFIER = 3
	NetworkOpenIntegrityMaximum   NETWORK_OPEN_INTEGRITY_QUALIFIER = 4
)

// String returns the NETWORK_OPEN_INTEGRITY_QUALIFIER constant's name, or its numeric form when
// the value is not a known constant.
func (e NETWORK_OPEN_INTEGRITY_QUALIFIER) String() string {
	switch e {
	case NetworkOpenIntegrityAny:
		return "NetworkOpenIntegrityAny"
	case NetworkOpenIntegrityNone:
		return "NetworkOpenIntegrityNone"
	case NetworkOpenIntegritySigned:
		return "NetworkOpenIntegritySigned"
	case NetworkOpenIntegrityEncrypted:
		return "NetworkOpenIntegrityEncrypted"
	case NetworkOpenIntegrityMaximum:
		return "NetworkOpenIntegrityMaximum"
	default:
		return fmt.Sprintf("NETWORK_OPEN_INTEGRITY_QUALIFIER(%d)", int32(e))
	}
}

type NETWORK_OPEN_LOCATION_QUALIFIER int32

const (
	NetworkOpenLocationAny      NETWORK_OPEN_LOCATION_QUALIFIER = 0
	NetworkOpenLocationRemote   NETWORK_OPEN_LOCATION_QUALIFIER = 1
	NetworkOpenLocationLoopback NETWORK_OPEN_LOCATION_QUALIFIER = 2
)

// String returns the NETWORK_OPEN_LOCATION_QUALIFIER constant's name, or its numeric form when
// the value is not a known constant.
func (e NETWORK_OPEN_LOCATION_QUALIFIER) String() string {
	switch e {
	case NetworkOpenLocationAny:
		return "NetworkOpenLocationAny"
	case NetworkOpenLocationRemote:
		return "NetworkOpenLocationRemote"
	case NetworkOpenLocationLoopback:
		return "NetworkOpenLocationLoopback"
	default:
		return fmt.Sprintf("NETWORK_OPEN_LOCATION_QUALIFIER(%d)", int32(e))
	}
}

type NTCREATEFILE_CREATE_DISPOSITION uint32

const (
	FILE_SUPERSEDE    NTCREATEFILE_CREATE_DISPOSITION = 0
	FILE_CREATE       NTCREATEFILE_CREATE_DISPOSITION = 2
	FILE_OPEN         NTCREATEFILE_CREATE_DISPOSITION = 1
	FILE_OPEN_IF      NTCREATEFILE_CREATE_DISPOSITION = 3
	FILE_OVERWRITE    NTCREATEFILE_CREATE_DISPOSITION = 4
	FILE_OVERWRITE_IF NTCREATEFILE_CREATE_DISPOSITION = 5
)

// String returns the NTCREATEFILE_CREATE_DISPOSITION constant's name, or its numeric form when
// the value is not a known constant.
func (e NTCREATEFILE_CREATE_DISPOSITION) String() string {
	switch e {
	case FILE_SUPERSEDE:
		return "FILE_SUPERSEDE"
	case FILE_CREATE:
		return "FILE_CREATE"
	case FILE_OPEN:
		return "FILE_OPEN"
	case FILE_OPEN_IF:
		return "FILE_OPEN_IF"
	case FILE_OVERWRITE:
		return "FILE_OVERWRITE"
	case FILE_OVERWRITE_IF:
		return "FILE_OVERWRITE_IF"
	default:
		return fmt.Sprintf("NTCREATEFILE_CREATE_DISPOSITION(%d)", uint32(e))
	}
}

// Bitmask — values may be combined with |.
type NTCREATEFILE_CREATE_OPTIONS uint32

const (
	FILE_DIRECTORY_FILE                       NTCREATEFILE_CREATE_OPTIONS = 1
	FILE_NON_DIRECTORY_FILE                   NTCREATEFILE_CREATE_OPTIONS = 64
	FILE_WRITE_THROUGH                        NTCREATEFILE_CREATE_OPTIONS = 2
	FILE_SEQUENTIAL_ONLY                      NTCREATEFILE_CREATE_OPTIONS = 4
	FILE_RANDOM_ACCESS                        NTCREATEFILE_CREATE_OPTIONS = 2048
	FILE_NO_INTERMEDIATE_BUFFERING            NTCREATEFILE_CREATE_OPTIONS = 8
	FILE_SYNCHRONOUS_IO_ALERT                 NTCREATEFILE_CREATE_OPTIONS = 16
	FILE_SYNCHRONOUS_IO_NONALERT              NTCREATEFILE_CREATE_OPTIONS = 32
	FILE_CREATE_TREE_CONNECTION               NTCREATEFILE_CREATE_OPTIONS = 128
	FILE_NO_EA_KNOWLEDGE                      NTCREATEFILE_CREATE_OPTIONS = 512
	FILE_OPEN_REPARSE_POINT                   NTCREATEFILE_CREATE_OPTIONS = 2097152
	FILE_DELETE_ON_CLOSE                      NTCREATEFILE_CREATE_OPTIONS = 4096
	FILE_OPEN_BY_FILE_ID                      NTCREATEFILE_CREATE_OPTIONS = 8192
	FILE_OPEN_FOR_BACKUP_INTENT               NTCREATEFILE_CREATE_OPTIONS = 16384
	FILE_RESERVE_OPFILTER                     NTCREATEFILE_CREATE_OPTIONS = 1048576
	FILE_OPEN_REQUIRING_OPLOCK                NTCREATEFILE_CREATE_OPTIONS = 65536
	FILE_COMPLETE_IF_OPLOCKED                 NTCREATEFILE_CREATE_OPTIONS = 256
	FILE_OPEN_FOR_FREE_SPACE_QUERY            NTCREATEFILE_CREATE_OPTIONS = 8388608
	FILE_CONTAINS_EXTENDED_CREATE_INFORMATION NTCREATEFILE_CREATE_OPTIONS = 268435456
	FILE_NO_COMPRESSION                       NTCREATEFILE_CREATE_OPTIONS = 32768
	FILE_DISALLOW_EXCLUSIVE                   NTCREATEFILE_CREATE_OPTIONS = 131072
	FILE_SESSION_AWARE                        NTCREATEFILE_CREATE_OPTIONS = 262144
	FILE_OPEN_NO_RECALL                       NTCREATEFILE_CREATE_OPTIONS = 4194304
)

// String returns the NTCREATEFILE_CREATE_OPTIONS constant's name, or its numeric form when
// the value is not a known constant.
func (e NTCREATEFILE_CREATE_OPTIONS) String() string {
	var parts []string
	if e&FILE_DIRECTORY_FILE != 0 {
		parts = append(parts, "FILE_DIRECTORY_FILE")
	}
	if e&FILE_NON_DIRECTORY_FILE != 0 {
		parts = append(parts, "FILE_NON_DIRECTORY_FILE")
	}
	if e&FILE_WRITE_THROUGH != 0 {
		parts = append(parts, "FILE_WRITE_THROUGH")
	}
	if e&FILE_SEQUENTIAL_ONLY != 0 {
		parts = append(parts, "FILE_SEQUENTIAL_ONLY")
	}
	if e&FILE_RANDOM_ACCESS != 0 {
		parts = append(parts, "FILE_RANDOM_ACCESS")
	}
	if e&FILE_NO_INTERMEDIATE_BUFFERING != 0 {
		parts = append(parts, "FILE_NO_INTERMEDIATE_BUFFERING")
	}
	if e&FILE_SYNCHRONOUS_IO_ALERT != 0 {
		parts = append(parts, "FILE_SYNCHRONOUS_IO_ALERT")
	}
	if e&FILE_SYNCHRONOUS_IO_NONALERT != 0 {
		parts = append(parts, "FILE_SYNCHRONOUS_IO_NONALERT")
	}
	if e&FILE_CREATE_TREE_CONNECTION != 0 {
		parts = append(parts, "FILE_CREATE_TREE_CONNECTION")
	}
	if e&FILE_NO_EA_KNOWLEDGE != 0 {
		parts = append(parts, "FILE_NO_EA_KNOWLEDGE")
	}
	if e&FILE_OPEN_REPARSE_POINT != 0 {
		parts = append(parts, "FILE_OPEN_REPARSE_POINT")
	}
	if e&FILE_DELETE_ON_CLOSE != 0 {
		parts = append(parts, "FILE_DELETE_ON_CLOSE")
	}
	if e&FILE_OPEN_BY_FILE_ID != 0 {
		parts = append(parts, "FILE_OPEN_BY_FILE_ID")
	}
	if e&FILE_OPEN_FOR_BACKUP_INTENT != 0 {
		parts = append(parts, "FILE_OPEN_FOR_BACKUP_INTENT")
	}
	if e&FILE_RESERVE_OPFILTER != 0 {
		parts = append(parts, "FILE_RESERVE_OPFILTER")
	}
	if e&FILE_OPEN_REQUIRING_OPLOCK != 0 {
		parts = append(parts, "FILE_OPEN_REQUIRING_OPLOCK")
	}
	if e&FILE_COMPLETE_IF_OPLOCKED != 0 {
		parts = append(parts, "FILE_COMPLETE_IF_OPLOCKED")
	}
	if e&FILE_OPEN_FOR_FREE_SPACE_QUERY != 0 {
		parts = append(parts, "FILE_OPEN_FOR_FREE_SPACE_QUERY")
	}
	if e&FILE_CONTAINS_EXTENDED_CREATE_INFORMATION != 0 {
		parts = append(parts, "FILE_CONTAINS_EXTENDED_CREATE_INFORMATION")
	}
	if e&FILE_NO_COMPRESSION != 0 {
		parts = append(parts, "FILE_NO_COMPRESSION")
	}
	if e&FILE_DISALLOW_EXCLUSIVE != 0 {
		parts = append(parts, "FILE_DISALLOW_EXCLUSIVE")
	}
	if e&FILE_SESSION_AWARE != 0 {
		parts = append(parts, "FILE_SESSION_AWARE")
	}
	if e&FILE_OPEN_NO_RECALL != 0 {
		parts = append(parts, "FILE_OPEN_NO_RECALL")
	}
	if len(parts) == 0 {
		return "0"
	}
	return strings.Join(parts, "|")
}

type OPLOCK_NOTIFY_REASON int32

const (
	OPLOCK_NOTIFY_BREAK_WAIT_INTERIM_TIMEOUT OPLOCK_NOTIFY_REASON = 0
	OPLOCK_NOTIFY_BREAK_WAIT_TERMINATED      OPLOCK_NOTIFY_REASON = 1
)

// String returns the OPLOCK_NOTIFY_REASON constant's name, or its numeric form when
// the value is not a known constant.
func (e OPLOCK_NOTIFY_REASON) String() string {
	switch e {
	case OPLOCK_NOTIFY_BREAK_WAIT_INTERIM_TIMEOUT:
		return "OPLOCK_NOTIFY_BREAK_WAIT_INTERIM_TIMEOUT"
	case OPLOCK_NOTIFY_BREAK_WAIT_TERMINATED:
		return "OPLOCK_NOTIFY_BREAK_WAIT_TERMINATED"
	default:
		return fmt.Sprintf("OPLOCK_NOTIFY_REASON(%d)", int32(e))
	}
}

type REFS_COMPRESSION_FORMATS int32

const (
	REFS_COMPRESSION_FORMAT_UNCOMPRESSED REFS_COMPRESSION_FORMATS = 0
	REFS_COMPRESSION_FORMAT_LZ4          REFS_COMPRESSION_FORMATS = 1
	REFS_COMPRESSION_FORMAT_ZSTD         REFS_COMPRESSION_FORMATS = 2
	REFS_COMPRESSION_FORMAT_MAX          REFS_COMPRESSION_FORMATS = 3
)

// String returns the REFS_COMPRESSION_FORMATS constant's name, or its numeric form when
// the value is not a known constant.
func (e REFS_COMPRESSION_FORMATS) String() string {
	switch e {
	case REFS_COMPRESSION_FORMAT_UNCOMPRESSED:
		return "REFS_COMPRESSION_FORMAT_UNCOMPRESSED"
	case REFS_COMPRESSION_FORMAT_LZ4:
		return "REFS_COMPRESSION_FORMAT_LZ4"
	case REFS_COMPRESSION_FORMAT_ZSTD:
		return "REFS_COMPRESSION_FORMAT_ZSTD"
	case REFS_COMPRESSION_FORMAT_MAX:
		return "REFS_COMPRESSION_FORMAT_MAX"
	default:
		return fmt.Sprintf("REFS_COMPRESSION_FORMATS(%d)", int32(e))
	}
}

type REFS_DEALLOCATE_RANGES_ALLOCATOR int32

const (
	REFS_DEALLOCATE_RANGES_ALLOCATOR_NONE REFS_DEALLOCATE_RANGES_ALLOCATOR = 0
	REFS_DEALLOCATE_RANGES_ALLOCATOR_SAA  REFS_DEALLOCATE_RANGES_ALLOCATOR = 1
	REFS_DEALLOCATE_RANGES_ALLOCATOR_CAA  REFS_DEALLOCATE_RANGES_ALLOCATOR = 2
	REFS_DEALLOCATE_RANGES_ALLOCATOR_MAA  REFS_DEALLOCATE_RANGES_ALLOCATOR = 3
)

// String returns the REFS_DEALLOCATE_RANGES_ALLOCATOR constant's name, or its numeric form when
// the value is not a known constant.
func (e REFS_DEALLOCATE_RANGES_ALLOCATOR) String() string {
	switch e {
	case REFS_DEALLOCATE_RANGES_ALLOCATOR_NONE:
		return "REFS_DEALLOCATE_RANGES_ALLOCATOR_NONE"
	case REFS_DEALLOCATE_RANGES_ALLOCATOR_SAA:
		return "REFS_DEALLOCATE_RANGES_ALLOCATOR_SAA"
	case REFS_DEALLOCATE_RANGES_ALLOCATOR_CAA:
		return "REFS_DEALLOCATE_RANGES_ALLOCATOR_CAA"
	case REFS_DEALLOCATE_RANGES_ALLOCATOR_MAA:
		return "REFS_DEALLOCATE_RANGES_ALLOCATOR_MAA"
	default:
		return fmt.Sprintf("REFS_DEALLOCATE_RANGES_ALLOCATOR(%d)", int32(e))
	}
}

type REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS int32

const (
	REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_COMPRESS_SYNC REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS = 1
	REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_MAX           REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS = 1
)

// String returns the REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS constant's name, or its numeric form when
// the value is not a known constant.
func (e REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS) String() string {
	switch e {
	case REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_COMPRESS_SYNC:
		return "REFS_SET_VOLUME_COMPRESSION_INFO_FLAG_COMPRESS_SYNC"
	default:
		return fmt.Sprintf("REFS_SET_VOLUME_COMPRESSION_INFO_FLAGS(%d)", int32(e))
	}
}

type REFS_STREAM_SNAPSHOT_OPERATION int32

const (
	REFS_STREAM_SNAPSHOT_OPERATION_INVALID            REFS_STREAM_SNAPSHOT_OPERATION = 0
	REFS_STREAM_SNAPSHOT_OPERATION_CREATE             REFS_STREAM_SNAPSHOT_OPERATION = 1
	REFS_STREAM_SNAPSHOT_OPERATION_LIST               REFS_STREAM_SNAPSHOT_OPERATION = 2
	REFS_STREAM_SNAPSHOT_OPERATION_QUERY_DELTAS       REFS_STREAM_SNAPSHOT_OPERATION = 3
	REFS_STREAM_SNAPSHOT_OPERATION_REVERT             REFS_STREAM_SNAPSHOT_OPERATION = 4
	REFS_STREAM_SNAPSHOT_OPERATION_SET_SHADOW_BTREE   REFS_STREAM_SNAPSHOT_OPERATION = 5
	REFS_STREAM_SNAPSHOT_OPERATION_CLEAR_SHADOW_BTREE REFS_STREAM_SNAPSHOT_OPERATION = 6
	REFS_STREAM_SNAPSHOT_OPERATION_MAX                REFS_STREAM_SNAPSHOT_OPERATION = 6
)

// String returns the REFS_STREAM_SNAPSHOT_OPERATION constant's name, or its numeric form when
// the value is not a known constant.
func (e REFS_STREAM_SNAPSHOT_OPERATION) String() string {
	switch e {
	case REFS_STREAM_SNAPSHOT_OPERATION_INVALID:
		return "REFS_STREAM_SNAPSHOT_OPERATION_INVALID"
	case REFS_STREAM_SNAPSHOT_OPERATION_CREATE:
		return "REFS_STREAM_SNAPSHOT_OPERATION_CREATE"
	case REFS_STREAM_SNAPSHOT_OPERATION_LIST:
		return "REFS_STREAM_SNAPSHOT_OPERATION_LIST"
	case REFS_STREAM_SNAPSHOT_OPERATION_QUERY_DELTAS:
		return "REFS_STREAM_SNAPSHOT_OPERATION_QUERY_DELTAS"
	case REFS_STREAM_SNAPSHOT_OPERATION_REVERT:
		return "REFS_STREAM_SNAPSHOT_OPERATION_REVERT"
	case REFS_STREAM_SNAPSHOT_OPERATION_SET_SHADOW_BTREE:
		return "REFS_STREAM_SNAPSHOT_OPERATION_SET_SHADOW_BTREE"
	case REFS_STREAM_SNAPSHOT_OPERATION_CLEAR_SHADOW_BTREE:
		return "REFS_STREAM_SNAPSHOT_OPERATION_CLEAR_SHADOW_BTREE"
	default:
		return fmt.Sprintf("REFS_STREAM_SNAPSHOT_OPERATION(%d)", int32(e))
	}
}

type RTL_MEMORY_TYPE int32

const (
	MemoryTypePaged     RTL_MEMORY_TYPE = 0
	MemoryTypeNonPaged  RTL_MEMORY_TYPE = 1
	MemoryType64KPage   RTL_MEMORY_TYPE = 2
	MemoryTypeLargePage RTL_MEMORY_TYPE = 3
	MemoryTypeHugePage  RTL_MEMORY_TYPE = 4
	MemoryTypeCustom    RTL_MEMORY_TYPE = 5
	MemoryTypeMax       RTL_MEMORY_TYPE = 6
)

// String returns the RTL_MEMORY_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e RTL_MEMORY_TYPE) String() string {
	switch e {
	case MemoryTypePaged:
		return "MemoryTypePaged"
	case MemoryTypeNonPaged:
		return "MemoryTypeNonPaged"
	case MemoryType64KPage:
		return "MemoryType64KPage"
	case MemoryTypeLargePage:
		return "MemoryTypeLargePage"
	case MemoryTypeHugePage:
		return "MemoryTypeHugePage"
	case MemoryTypeCustom:
		return "MemoryTypeCustom"
	case MemoryTypeMax:
		return "MemoryTypeMax"
	default:
		return fmt.Sprintf("RTL_MEMORY_TYPE(%d)", int32(e))
	}
}

type SE_AUDIT_OPERATION int32

const (
	AuditPrivilegeObject                    SE_AUDIT_OPERATION = 0
	AuditPrivilegeService                   SE_AUDIT_OPERATION = 1
	AuditAccessCheck                        SE_AUDIT_OPERATION = 2
	AuditOpenObject                         SE_AUDIT_OPERATION = 3
	AuditOpenObjectWithTransaction          SE_AUDIT_OPERATION = 4
	AuditCloseObject                        SE_AUDIT_OPERATION = 5
	AuditDeleteObject                       SE_AUDIT_OPERATION = 6
	AuditOpenObjectForDelete                SE_AUDIT_OPERATION = 7
	AuditOpenObjectForDeleteWithTransaction SE_AUDIT_OPERATION = 8
	AuditCloseNonObject                     SE_AUDIT_OPERATION = 9
	AuditOpenNonObject                      SE_AUDIT_OPERATION = 10
	AuditObjectReference                    SE_AUDIT_OPERATION = 11
	AuditHandleCreation                     SE_AUDIT_OPERATION = 12
)

// String returns the SE_AUDIT_OPERATION constant's name, or its numeric form when
// the value is not a known constant.
func (e SE_AUDIT_OPERATION) String() string {
	switch e {
	case AuditPrivilegeObject:
		return "AuditPrivilegeObject"
	case AuditPrivilegeService:
		return "AuditPrivilegeService"
	case AuditAccessCheck:
		return "AuditAccessCheck"
	case AuditOpenObject:
		return "AuditOpenObject"
	case AuditOpenObjectWithTransaction:
		return "AuditOpenObjectWithTransaction"
	case AuditCloseObject:
		return "AuditCloseObject"
	case AuditDeleteObject:
		return "AuditDeleteObject"
	case AuditOpenObjectForDelete:
		return "AuditOpenObjectForDelete"
	case AuditOpenObjectForDeleteWithTransaction:
		return "AuditOpenObjectForDeleteWithTransaction"
	case AuditCloseNonObject:
		return "AuditCloseNonObject"
	case AuditOpenNonObject:
		return "AuditOpenNonObject"
	case AuditObjectReference:
		return "AuditObjectReference"
	case AuditHandleCreation:
		return "AuditHandleCreation"
	default:
		return fmt.Sprintf("SE_AUDIT_OPERATION(%d)", int32(e))
	}
}

type SRV_INSTANCE_TYPE int32

const (
	SrvInstanceTypeUndefined SRV_INSTANCE_TYPE = 0
	SrvInstanceTypePrimary   SRV_INSTANCE_TYPE = 1
	SrvInstanceTypeCsv       SRV_INSTANCE_TYPE = 2
	SrvInstanceTypeSBL       SRV_INSTANCE_TYPE = 3
	SrvInstanceTypeSR        SRV_INSTANCE_TYPE = 4
	SrvInstanceTypeVSMB      SRV_INSTANCE_TYPE = 5
)

// String returns the SRV_INSTANCE_TYPE constant's name, or its numeric form when
// the value is not a known constant.
func (e SRV_INSTANCE_TYPE) String() string {
	switch e {
	case SrvInstanceTypeUndefined:
		return "SrvInstanceTypeUndefined"
	case SrvInstanceTypePrimary:
		return "SrvInstanceTypePrimary"
	case SrvInstanceTypeCsv:
		return "SrvInstanceTypeCsv"
	case SrvInstanceTypeSBL:
		return "SrvInstanceTypeSBL"
	case SrvInstanceTypeSR:
		return "SrvInstanceTypeSR"
	case SrvInstanceTypeVSMB:
		return "SrvInstanceTypeVSMB"
	default:
		return fmt.Sprintf("SRV_INSTANCE_TYPE(%d)", int32(e))
	}
}

type SharedVirtualDiskHandleState int32

const (
	SharedVirtualDiskHandleStateNone         SharedVirtualDiskHandleState = 0
	SharedVirtualDiskHandleStateFileShared   SharedVirtualDiskHandleState = 1
	SharedVirtualDiskHandleStateHandleShared SharedVirtualDiskHandleState = 3
)

// String returns the SharedVirtualDiskHandleState constant's name, or its numeric form when
// the value is not a known constant.
func (e SharedVirtualDiskHandleState) String() string {
	switch e {
	case SharedVirtualDiskHandleStateNone:
		return "SharedVirtualDiskHandleStateNone"
	case SharedVirtualDiskHandleStateFileShared:
		return "SharedVirtualDiskHandleStateFileShared"
	case SharedVirtualDiskHandleStateHandleShared:
		return "SharedVirtualDiskHandleStateHandleShared"
	default:
		return fmt.Sprintf("SharedVirtualDiskHandleState(%d)", int32(e))
	}
}

type SharedVirtualDiskSupportType int32

const (
	SharedVirtualDisksUnsupported          SharedVirtualDiskSupportType = 0
	SharedVirtualDisksSupported            SharedVirtualDiskSupportType = 1
	SharedVirtualDiskSnapshotsSupported    SharedVirtualDiskSupportType = 3
	SharedVirtualDiskCDPSnapshotsSupported SharedVirtualDiskSupportType = 7
)

// String returns the SharedVirtualDiskSupportType constant's name, or its numeric form when
// the value is not a known constant.
func (e SharedVirtualDiskSupportType) String() string {
	switch e {
	case SharedVirtualDisksUnsupported:
		return "SharedVirtualDisksUnsupported"
	case SharedVirtualDisksSupported:
		return "SharedVirtualDisksSupported"
	case SharedVirtualDiskSnapshotsSupported:
		return "SharedVirtualDiskSnapshotsSupported"
	case SharedVirtualDiskCDPSnapshotsSupported:
		return "SharedVirtualDiskCDPSnapshotsSupported"
	default:
		return fmt.Sprintf("SharedVirtualDiskSupportType(%d)", int32(e))
	}
}

type VIRTUAL_MEMORY_INFORMATION_CLASS int32

const (
	VmPrefetchInformation VIRTUAL_MEMORY_INFORMATION_CLASS = 0
)

// String returns the VIRTUAL_MEMORY_INFORMATION_CLASS constant's name, or its numeric form when
// the value is not a known constant.
func (e VIRTUAL_MEMORY_INFORMATION_CLASS) String() string {
	switch e {
	case VmPrefetchInformation:
		return "VmPrefetchInformation"
	default:
		return fmt.Sprintf("VIRTUAL_MEMORY_INFORMATION_CLASS(%d)", int32(e))
	}
}

type LCN_WEAK_REFERENCE_STATE int32

const (
	LCN_WEAK_REFERENCE_VALID LCN_WEAK_REFERENCE_STATE = 1
	LCN_CHECKSUM_VALID       LCN_WEAK_REFERENCE_STATE = 2
)

// String returns the LCN_WEAK_REFERENCE_STATE constant's name, or its numeric form when
// the value is not a known constant.
func (e LCN_WEAK_REFERENCE_STATE) String() string {
	switch e {
	case LCN_WEAK_REFERENCE_VALID:
		return "LCN_WEAK_REFERENCE_VALID"
	case LCN_CHECKSUM_VALID:
		return "LCN_CHECKSUM_VALID"
	default:
		return fmt.Sprintf("LCN_WEAK_REFERENCE_STATE(%d)", int32(e))
	}
}

type REFS_STREAM_EXTENT_PROPERTIES int32

const (
	REFS_STREAM_EXTENT_PROPERTY_VALID           REFS_STREAM_EXTENT_PROPERTIES = 16
	REFS_STREAM_EXTENT_PROPERTY_STREAM_RESERVED REFS_STREAM_EXTENT_PROPERTIES = 32
	REFS_STREAM_EXTENT_PROPERTY_CRC32           REFS_STREAM_EXTENT_PROPERTIES = 128
	REFS_STREAM_EXTENT_PROPERTY_CRC64           REFS_STREAM_EXTENT_PROPERTIES = 256
	REFS_STREAM_EXTENT_PROPERTY_GHOSTED         REFS_STREAM_EXTENT_PROPERTIES = 512
	REFS_STREAM_EXTENT_PROPERTY_READONLY        REFS_STREAM_EXTENT_PROPERTIES = 1024
	REFS_STREAM_EXTENT_PROPERTY_SPARSE          REFS_STREAM_EXTENT_PROPERTIES = 8
)

// String returns the REFS_STREAM_EXTENT_PROPERTIES constant's name, or its numeric form when
// the value is not a known constant.
func (e REFS_STREAM_EXTENT_PROPERTIES) String() string {
	switch e {
	case REFS_STREAM_EXTENT_PROPERTY_VALID:
		return "REFS_STREAM_EXTENT_PROPERTY_VALID"
	case REFS_STREAM_EXTENT_PROPERTY_STREAM_RESERVED:
		return "REFS_STREAM_EXTENT_PROPERTY_STREAM_RESERVED"
	case REFS_STREAM_EXTENT_PROPERTY_CRC32:
		return "REFS_STREAM_EXTENT_PROPERTY_CRC32"
	case REFS_STREAM_EXTENT_PROPERTY_CRC64:
		return "REFS_STREAM_EXTENT_PROPERTY_CRC64"
	case REFS_STREAM_EXTENT_PROPERTY_GHOSTED:
		return "REFS_STREAM_EXTENT_PROPERTY_GHOSTED"
	case REFS_STREAM_EXTENT_PROPERTY_READONLY:
		return "REFS_STREAM_EXTENT_PROPERTY_READONLY"
	case REFS_STREAM_EXTENT_PROPERTY_SPARSE:
		return "REFS_STREAM_EXTENT_PROPERTY_SPARSE"
	default:
		return fmt.Sprintf("REFS_STREAM_EXTENT_PROPERTIES(%d)", int32(e))
	}
}
